# Generated by Django 5.2 on 2026-08-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0002_seed_initial_eligibility_policies'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fundinginstruction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('financial_account', 'kind'), name='payment_instruction_one_open_kind_uniq'),
        ),
    ]
