# Generated by Django 5.2 on 2026-09-05 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0004_remove_duplicate_confio_fee_fields'),
        ('users', '0042_add_bnb_unified_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBridgeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_id', models.UUIDField()),
                ('source_address', models.CharField(max_length=42)),
                ('destination_address', models.CharField(max_length=42)),
                ('source_token_id', models.CharField(default='BSC:USDT', max_length=24)),
                ('destination_token_id', models.CharField(default='POL:USDC', max_length=24)),
                ('amount_units', models.CharField(max_length=78)),
                ('routes', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confio_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.account')),
                ('funding_instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_accounts.fundinginstruction')),
                ('money_flow', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bridge_quote', to='payment_accounts.moneyflow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('confio_account', 'request_id'), name='payment_bridge_quote_request_uniq')],
            },
        ),
    ]
