# Generated by Django 5.2 on 2026-09-05 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0014_send_unique_by_source'),
        ('payment_accounts', '0005_paymentbridgequote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBridgeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('prepared', 'Awaiting authorization'), ('submitted', 'Source submitted'), ('bridging', 'Bridging'), ('delivered', 'Delivered on chain'), ('refunded', 'Refunded'), ('failed', 'Source failed'), ('expired', 'Authorization expired'), ('needs_review', 'Needs review')], default='prepared', max_length=24)),
                ('deposit_address', models.CharField(max_length=42, unique=True)),
                ('amount_out_min', models.CharField(max_length=78)),
                ('amount_out', models.CharField(max_length=78)),
                ('deadline', models.BigIntegerField()),
                ('calls', models.JSONField(default=list)),
                ('binding', models.JSONField(default=dict)),
                ('source_tx_hash', models.CharField(blank=True, max_length=66)),
                ('destination_tx_hash', models.CharField(blank=True, max_length=66)),
                ('signed_raw_tx', models.TextField(blank=True)),
                ('sponsor_address', models.CharField(blank=True, max_length=42)),
                ('sponsor_nonce', models.BigIntegerField(blank=True, null=True)),
                ('actual_out_units', models.CharField(blank=True, max_length=78)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.sponsoredbatch')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='payment_accounts.paymentbridgequote')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'updated_at'], name='pay_bridge_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sponsor_nonce__isnull', False)), fields=('sponsor_address', 'sponsor_nonce'), name='payment_bridge_polygon_nonce_uniq')],
            },
        ),
    ]
