# Generated by Django 5.2 on 2026-09-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0006_paymentbridgetransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbridgetransfer',
            name='provider_credit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bridge_transfer', to='payment_accounts.ledgerentry'),
        ),
    ]
