# Generated by Django 5.2 on 2026-09-05 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0007_paymentbridgetransfer_provider_credit'),
        ('users', '0042_add_bnb_unified_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfiniaJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_id', models.UUIDField()),
                ('direction', models.CharField(choices=[('to_bank', 'To bank'), ('to_wallet', 'To wallet')], max_length=16)),
                ('stage', models.CharField(default='awaiting_credit', max_length=32)),
                ('minimum_fx_output', models.DecimalField(decimal_places=18, max_digits=38)),
                ('destination_snapshot', models.JSONField(default=dict)),
                ('wallet_address', models.CharField(max_length=42)),
                ('fx_quote', models.JSONField(default=dict)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bridge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infinia_journey', to='payment_accounts.paymentbridgetransfer')),
                ('confio_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.account')),
                ('crypto_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payment_accounts.financialaccount')),
                ('funding_credit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funded_journey', to='payment_accounts.ledgerentry')),
                ('fx_operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payment_accounts.moneyoperation')),
                ('local_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payment_accounts.financialaccount')),
                ('money_flow', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='infinia_journey', to='payment_accounts.moneyflow')),
                ('payout_operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payment_accounts.moneyoperation')),
            ],
            options={
                'indexes': [models.Index(fields=['stage', 'updated_at'], name='infinia_journey_stage_idx')],
                'constraints': [models.UniqueConstraint(fields=('confio_account', 'request_id'), name='infinia_journey_request_uniq')],
            },
        ),
    ]
