# Generated by Django 5.2 on 2026-09-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0008_infiniajourney'),
    ]

    operations = [
        migrations.AddField(
            model_name='infiniajourney',
            name='wallet_arrival_tx_hash',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name='infiniajourney',
            name='wallet_arrival_units',
            field=models.CharField(blank=True, max_length=78),
        ),
    ]
