# Generated by Django 5.2 on 2026-09-14 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0010_cobrejourney'),
        ('users', '0043_bankinfo_breb_key_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='payin_document_country',
            field=models.CharField(blank=True, default='', help_text='Verified jurisdiction of sender document numbers on this rail (ISO-2). Blank disables automatic same-owner matching.', max_length=2),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='payin_rail',
            field=models.CharField(blank=True, default='', help_text='Verified receiving rail, e.g. SPEI or PIX. Leave blank if ambiguous.', max_length=50),
        ),
        migrations.CreateModel(
            name='PayinAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=80)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('rail', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payin_admission', to='payment_accounts.ledgerentry')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyPayinSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('cobre', 'Cobre'), ('infinia', 'Infinia')], max_length=20)),
                ('country', models.CharField(help_text='Receiving country, ISO-2; not phone country.', max_length=2)),
                ('rail', models.CharField(blank=True, default='', help_text='Blank for country switch; otherwise verified rail code.', max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('evidence', models.TextField(help_text='Approval reference, including required enhanced KYC/KYB review for user grants.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confio_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('confio_account__isnull', True)), fields=('provider', 'country', 'rail'), name='payin_switch_global_uniq'), models.UniqueConstraint(condition=models.Q(('confio_account__isnull', False)), fields=('provider', 'country', 'rail', 'confio_account'), name='payin_switch_owner_uniq'), models.CheckConstraint(condition=models.Q(('confio_account__isnull', True), models.Q(('rail', ''), _negated=True), _connector='OR'), name='payin_switch_owner_rail')],
            },
        ),
    ]
