# Generated by Django 5.2 on 2026-09-15 01:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


def preserve_existing_accounts(apps, schema_editor):
    Account = apps.get_model('payment_accounts', 'FinancialAccount')
    Activation = apps.get_model('payment_accounts', 'AccountActivation')
    db = schema_editor.connection.alias
    rows = Account.objects.using(db).filter(provider_profile__provider='infinia').exclude(
        country='XXX').exclude(provider_account_id__isnull=True).exclude(provider_account_id='')
    for account in rows.select_related('provider_profile').iterator():
        Activation.objects.using(db).get_or_create(
            confio_account_id=account.provider_profile.confio_account_id,
            country=account.country, asset=account.asset,
            defaults={'status': 'legacy', 'amount': '0.00', 'method_id': ''})


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0014_limitincreaserequest'),
        ('send', '0017_sendtransaction_exact_fee'),
        ('users', '0043_bankinfo_breb_key_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('country', models.CharField(max_length=3)),
                ('asset', models.CharField(max_length=12)),
                ('method_id', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default='10.00', max_digits=12)),
                ('status', models.CharField(choices=[('provisioning', 'Opening account'), ('awaiting_payment', 'Account ready, payment due'), ('payment_pending', 'Payment pending'), ('active', 'Active'), ('legacy', 'Existing account'), ('failed', 'Opening failed')], default='provisioning', max_length=24)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('collector_address', models.CharField(blank=True, default='', max_length=42)),
                ('settlement_token_address', models.CharField(blank=True, default='', max_length=42)),
                ('chain_id', models.PositiveIntegerField(default=56)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confio_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.account')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_activation', to='send.sendtransaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('confio_account', 'country', 'asset'), name='activation_owner_country_asset_uniq')],
            },
        ),
        migrations.RunPython(preserve_existing_accounts, migrations.RunPython.noop),
    ]
