# Generated by Django 5.2 on 2026-09-15 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0017_cobre_breb_outside_venezuela'),
        ('users', '0043_bankinfo_breb_key_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrebLocationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('platform', models.CharField(blank=True, max_length=8)),
                ('passed', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_country', models.CharField(blank=True, max_length=2)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('reading_at', models.DateTimeField(blank=True, null=True)),
                ('confio_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.account')),
            ],
            options={
                'indexes': [models.Index(fields=['confio_account', '-created_at'], name='payment_acc_confio__b6e495_idx')],
            },
        ),
    ]
