# Generated by Django 5.2 on 2026-09-24 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0024_payin_document_country_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfiniaMaintenanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_period', models.DateField()),
                ('enabled', models.BooleanField(default=True)),
                ('monthly_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payment_accounts.financialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='InfiniaMaintenanceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('collected_tx_hash', models.CharField(blank=True, max_length=66)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_accounts.financialaccount')),
                ('reserved_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_accounts.moneyflow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'period'), name='infinia_maintenance_month_uniq')],
            },
        ),
    ]
