# Generated by Django 5.2 on 2026-09-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0025_infiniamaintenancestate_infiniamaintenancecharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfiniaFeeDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=18, max_digits=36)),
                ('settled_tx_hash', models.CharField(blank=True, max_length=66)),
                ('reserved_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_infinia_debts', to='payment_accounts.moneyflow')),
                ('source_flow', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='infinia_fee_debt', to='payment_accounts.moneyflow')),
            ],
        ),
    ]
