# Generated by Django 5.2 on 2026-09-24 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0026_infiniafeedebt'),
        ('users', '0046_user_wallet_recovery_drive_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfiniaPayoutEstimateBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_units', models.CharField(max_length=78)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confio_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_accounts.payoutdestination')),
                ('funding_instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_accounts.fundinginstruction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('confio_account', 'funding_instruction', 'amount_units'), name='infinia_payout_estimate_binding_uniq')],
            },
        ),
    ]
