# Generated by Django 5.2 on 2026-09-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0027_infiniapayoutestimatebinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticpayin',
            name='awaiting_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automaticpayin',
            name='return_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='automaticpayin',
            name='return_idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='automaticpayin',
            name='return_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='automaticpayin',
            name='return_provider_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='automaticpayin',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automaticpayin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('review', 'Review'), ('awaiting_face', 'Awaiting Confío Face'), ('returning', 'Returning to payer'), ('returned', 'Returned to payer'), ('return_failed', 'Return failed')], default='pending', max_length=20),
        ),
    ]
