# Generated by Django 5.2 on 2026-09-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_accounts', '0028_payin_face_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticpayin',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
