# Generated by Django 5.2 on 2026-06-10 22:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financieras', '0001_initial'),
        ('send', '0006_alter_phoneinvite_token_type'),
        ('usdc_transactions', '0006_alter_guardariantransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financierareview',
            name='send_transaction',
            field=models.ForeignKey(blank=True, help_text='Confirmed USDC send backing this review (XOR usdc_withdrawal)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiera_reviews', to='send.sendtransaction'),
        ),
        migrations.AddField(
            model_name='financierareview',
            name='usdc_withdrawal',
            field=models.ForeignKey(blank=True, help_text='Completed USDC withdrawal backing this review (XOR send_transaction)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiera_reviews', to='usdc_transactions.usdcwithdrawal'),
        ),
        migrations.AlterField(
            model_name='financierareview',
            name='sent_usdc',
            field=models.DecimalField(decimal_places=6, help_text='USDC amount copied from the backing transaction', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AddConstraint(
            model_name='financierareview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('send_transaction__isnull', False), ('usdc_withdrawal__isnull', True)), models.Q(('send_transaction__isnull', True), ('usdc_withdrawal__isnull', False)), _connector='OR'), name='review_backed_by_exactly_one_transaction'),
        ),
        migrations.AddConstraint(
            model_name='financierareview',
            constraint=models.UniqueConstraint(condition=models.Q(('send_transaction__isnull', False)), fields=('send_transaction',), name='unique_review_per_send_transaction'),
        ),
        migrations.AddConstraint(
            model_name='financierareview',
            constraint=models.UniqueConstraint(condition=models.Q(('usdc_withdrawal__isnull', False)), fields=('usdc_withdrawal',), name='unique_review_per_usdc_withdrawal'),
        ),
    ]
