# Generated by Django 5.2 on 2026-06-10 22:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financieras', '0002_financierareview_send_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financierareview',
            name='sent_token',
            field=models.CharField(choices=[('USDC', 'USD Coin'), ('CUSD', 'Confío Dollar')], default='USDC', help_text='Token of the backing transaction; both are $1-pegged so the derived rate math is identical', max_length=8),
        ),
        migrations.AlterField(
            model_name='financierareview',
            name='sent_usdc',
            field=models.DecimalField(decimal_places=6, help_text='Dollar-stable amount copied from the backing transaction', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
