# Generated by Django 5.2 on 2026-08-02 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financieras', '0004_financiera_location_and_payout_options'),
        ('send', '0011_phoneinvite_inviter_address'),
        ('usdc_transactions', '0007_guardariantransaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiera',
            name='supports_usdc_algorand',
            field=models.BooleanField(default=False, help_text='Mandatory: accepts USDT over BNB Smart Chain (BEP-20)'),
        ),
        migrations.AlterField(
            model_name='financierareview',
            name='send_transaction',
            field=models.ForeignKey(blank=True, help_text='Confirmed dollar-stable send backing this review (XOR usdc_withdrawal)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiera_reviews', to='send.sendtransaction'),
        ),
        migrations.AlterField(
            model_name='financierareview',
            name='sent_token',
            field=models.CharField(choices=[('USDT', 'Tether USD'), ('CUSD_PLUS', 'Confío Dollar Plus'), ('USDC', 'USD Coin'), ('CUSD', 'Confío Dollar')], default='USDT', help_text='Token of the backing transaction; all are $1-denominated so the derived rate math is identical', max_length=10),
        ),
        migrations.AlterField(
            model_name='financierareview',
            name='usdc_withdrawal',
            field=models.ForeignKey(blank=True, help_text='Completed legacy USDC withdrawal backing this review (XOR send_transaction)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiera_reviews', to='usdc_transactions.usdcwithdrawal'),
        ),
    ]
