# Generated by Django 5.2 on 2025-09-02 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='telegramverification',
            index=models.Index(fields=['phone_number', 'request_id'], name='telegram_ve_phone_n_899005_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramverification',
            index=models.Index(fields=['user'], name='telegram_ve_user_id_30fa63_idx'),
        ),
    ]
