# Generated by Django 5.2 on 2025-09-02 02:45

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('invoice_id', models.CharField(default=payments.models.generate_invoice_id, editable=False, max_length=32, unique=True)),
                ('merchant_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], default='business', help_text='Type of merchant (always business for invoices)', max_length=10)),
                ('merchant_display_name', models.CharField(blank=True, help_text='Display name for the merchant', max_length=255)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('token_type', models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('payment_transaction_id', models.CharField(default=payments.models.generate_payment_transaction_id, editable=False, max_length=32, unique=True)),
                ('payer_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], default='user', help_text='Type of payer (user or business)', max_length=10)),
                ('merchant_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], default='business', help_text='Type of merchant (always business for payments)', max_length=10)),
                ('payer_display_name', models.CharField(blank=True, help_text='Display name for the payer', max_length=255)),
                ('merchant_display_name', models.CharField(blank=True, help_text='Display name for the merchant', max_length=255)),
                ('payer_phone', models.CharField(blank=True, help_text='Payer phone number at transaction time', max_length=30)),
                ('payer_address', models.CharField(max_length=66)),
                ('merchant_address', models.CharField(max_length=66)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('token_type', models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_BLOCKCHAIN', 'Pending Blockchain'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66, unique=True)),
                ('error_message', models.TextField(blank=True)),
                ('blockchain_data', models.JSONField(blank=True, help_text='Unsigned blockchain transactions for client signing', null=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Optional key to prevent duplicate payments', max_length=64, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
