# Generated by Django 4.2.20 on 2025-07-19 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_add_soft_delete_fields'),
        ('send', '0005_rename_transaction_to_sendtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('invoice_id', models.CharField(default=payments.models.generate_invoice_id, editable=False, max_length=32, unique=True)),
                ('amount', models.CharField(max_length=32)),
                ('token_type', models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('merchant_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_created', to='users.account')),
                ('merchant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_paid', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='send.sendtransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice_id'], name='payments_in_invoice_440ec1_idx'), models.Index(fields=['merchant_user', 'status'], name='payments_in_merchan_ec64f3_idx'), models.Index(fields=['status', 'expires_at'], name='payments_in_status_ba8402_idx'), models.Index(fields=['created_at'], name='payments_in_created_a76cc7_idx')],
            },
        ),
    ]
