# Generated by Django 5.2 on 2025-09-02 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_by_user',
            field=models.ForeignKey(help_text='User who created this invoice (business owner or cashier)', on_delete=django.db.models.deletion.CASCADE, related_name='invoices_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='merchant_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_created', to='users.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='merchant_business',
            field=models.ForeignKey(help_text='Business entity that is the actual merchant', on_delete=django.db.models.deletion.CASCADE, related_name='invoices_received', to='users.business'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_by_business',
            field=models.ForeignKey(blank=True, help_text='Business that paid the invoice (if payer is business)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_paid', to='users.business'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='payments.invoice'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_received', to='users.account'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_account_user',
            field=models.ForeignKey(blank=True, help_text='User associated with the merchant business (owner or cashier)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_merchant_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_business',
            field=models.ForeignKey(help_text='Business entity that received the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_received', to='users.business'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_sent', to='users.account'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_business',
            field=models.ForeignKey(blank=True, help_text='Business that made the payment (if payer is business account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_sent', to='users.business'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_user',
            field=models.ForeignKey(help_text='User who initiated the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_id'], name='payments_in_invoice_056d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['merchant_business', 'status'], name='payments_in_merchan_c18eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'expires_at'], name='payments_in_status_56554b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='payments_in_created_d4aa22_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_transaction_id'], name='payments_pa_payment_72dff5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_hash'], name='payments_pa_transac_69f33f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payer_user', 'status'], name='payments_pa_payer_u_9c7110_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['merchant_account_user', 'status'], name='payments_pa_merchan_0807ac_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payer_address'], name='payments_pa_payer_a_0875f6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['merchant_address'], name='payments_pa_merchan_dbb173_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='payments_pa_created_a246c6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['idempotency_key'], name='payments_pa_idempot_056689_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('idempotency_key__isnull', False)), fields=('payer_user', 'invoice', 'idempotency_key'), name='unique_payment_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['CONFIRMED'])), fields=('invoice',), name='unique_confirmed_payment_per_invoice'),
        ),
    ]
