# Generated by Django 4.2.20 on 2025-07-19 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
    ]
