# Generated by Django 4.2.20 on 2025-07-20 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_soft_delete_fields'),
        ('send', '0005_rename_transaction_to_sendtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_auto_20250719_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('payment_transaction_id', models.CharField(default=payments.models.generate_payment_transaction_id, editable=False, max_length=32, unique=True)),
                ('payer_address', models.CharField(max_length=66)),
                ('merchant_address', models.CharField(max_length=66)),
                ('amount', models.CharField(max_length=32)),
                ('token_type', models.CharField(choices=[('cUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('transaction_hash', models.CharField(blank=True, help_text='Sui transaction digest (0x + 32 bytes, 66 hex characters total)', max_length=66, unique=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='token_type',
            field=models.CharField(choices=[('cUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use payment_transactions instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='send.sendtransaction'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='payments.invoice'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_received', to='users.account'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_sent', to='users.account'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_transaction_id'], name='payments_pa_payment_72dff5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_hash'], name='payments_pa_transac_69f33f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payer_user', 'status'], name='payments_pa_payer_u_9c7110_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['merchant_user', 'status'], name='payments_pa_merchan_38d1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payer_address'], name='payments_pa_payer_a_0875f6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['merchant_address'], name='payments_pa_merchan_dbb173_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='payments_pa_created_a246c6_idx'),
        ),
    ]
