# Generated by Django 4.2.20 on 2025-07-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20250719_2318'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE payments_paymentrequest RENAME TO payments_invoice;',
            reverse_sql='ALTER TABLE payments_invoice RENAME TO payments_paymentrequest;',
        ),
    ]
