# Generated by Django 5.2 on 2025-12-17 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('users', '0013_user_platform_os'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_payment_72dff5_idx',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='payment_transaction_id',
            new_name='internal_id',
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['internal_id'], name='payments_pa_interna_450739_idx'),
        ),
    ]
