# Generated by Django 4.2.20 on 2025-07-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_table_paymentrequest_to_invoice'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE payments_invoice RENAME COLUMN request_id TO invoice_id;',
            reverse_sql='ALTER TABLE payments_invoice RENAME COLUMN invoice_id TO request_id;',
        ),
    ]
