# Generated by Django 5.2 on 2025-12-19 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_invoice_internal_id'),
        ('users', '0015_add_presale_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='payments_in_invoice_056d7c_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['internal_id'], name='payments_in_interna_1ce457_idx'),
        ),
    ]
