# Generated by Django 4.2.20 on 2025-07-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_update_transaction_reference'),
        ('users', '0005_account_business_delete_userprofile_account_business_and_more'),
    ]

    operations = [
        # Update PaymentTransaction model
        # Payer can be Personal OR Business (nullable business field)
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_business',
            field=models.ForeignKey(
                blank=True,
                help_text='Business that made the payment (if payer is business)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payment_transactions_sent',
                to='users.business'
            ),
        ),
        # Merchant is ALWAYS Business (temporarily nullable for migration)
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_business',
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text='Business that received the payment (merchant is always business)',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payment_transactions_received',
                to='users.business'
            ),
        ),
        
        # Add computed fields for GraphQL
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_type',
            field=models.CharField(
                choices=[('user', 'Personal'), ('business', 'Business')],
                default='user',
                max_length=10,
                help_text='Type of payer (user or business)'
            ),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_type',
            field=models.CharField(
                choices=[('user', 'Personal'), ('business', 'Business')],
                default='business',
                max_length=10,
                help_text='Type of merchant (always business for payments)'
            ),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_display_name',
            field=models.CharField(
                blank=True,
                max_length=255,
                help_text='Display name for the payer'
            ),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_display_name',
            field=models.CharField(
                blank=True,
                max_length=255,
                help_text='Display name for the merchant'
            ),
        ),
        
        # Update Invoice model  
        # Merchant is ALWAYS Business (temporarily nullable for migration)
        migrations.AddField(
            model_name='invoice',
            name='merchant_business',
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text='Business that created the invoice (merchant is always business)',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices_created',
                to='users.business'
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_by_business',
            field=models.ForeignKey(
                blank=True,
                help_text='Business that paid the invoice (if payer is business)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='invoices_paid',
                to='users.business'
            ),
        ),
        
        # Add computed fields for Invoice
        migrations.AddField(
            model_name='invoice',
            name='merchant_type',
            field=models.CharField(
                choices=[('user', 'Personal'), ('business', 'Business')],
                default='business',
                max_length=10,
                help_text='Type of merchant (always business for invoices)'
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='merchant_display_name',
            field=models.CharField(
                blank=True,
                max_length=255,
                help_text='Display name for the merchant'
            ),
        ),
        
        # Add indexes for the new fields
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payer_business'], name='payments_paymenttransaction_payer_business_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['merchant_business'], name='payments_paymenttransaction_merchant_business_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['merchant_business'], name='payments_invoice_merchant_business_idx'),
        ),
    ]
