# Generated by Django 5.2 on 2026-07-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_invoice_payments_in_invoice_056d7c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='token_type',
            field=models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin'), ('CUSD_PLUS', 'Confío Dollar Plus'), ('USDT', 'Tether USD')], max_length=10),
        ),
    ]
