# Generated by Django 4.2.20 on 2025-07-21 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_business_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add new user fields to PaymentTransaction
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_account_user',
            field=models.ForeignKey(
                blank=True,
                help_text='User associated with the merchant business (owner or cashier)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payment_transactions_merchant_account',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        
        # Add new user field to Invoice  
        migrations.AddField(
            model_name='invoice',
            name='created_by_user',
            field=models.ForeignKey(
                blank=True,
                help_text='User who created this invoice (business owner or cashier)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices_created_by',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        
        # Update merchant_user to be nullable and change related_name to avoid conflicts
        migrations.AlterField(
            model_name='paymenttransaction',
            name='merchant_user',
            field=models.ForeignKey(
                blank=True,
                help_text='DEPRECATED: Use merchant_account_user instead',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payment_transactions_received_legacy',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='merchant_user',
            field=models.ForeignKey(
                blank=True,
                help_text='DEPRECATED: Use created_by_user instead',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices_created_legacy',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
