# Generated by Django 5.2 on 2026-08-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymenttransaction_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='token_type',
            field=models.CharField(choices=[('CUSD_PLUS', 'Confío Dollar Plus'), ('CONFIO', 'Confío Token'), ('CUSD', 'Confío Dollar (legacy)'), ('USDC', 'USD Coin (legacy)')], max_length=10),
        ),
    ]
