# Generated by Django 4.2.20 on 2025-07-21 22:34

from django.db import migrations


def populate_new_user_fields(apps, schema_editor):
    """Populate the new user fields from existing data"""
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    Invoice = apps.get_model('payments', 'Invoice')
    
    # Populate PaymentTransaction.merchant_account_user from merchant_user
    for payment in PaymentTransaction.objects.filter(merchant_account_user__isnull=True):
        if payment.merchant_user:
            payment.merchant_account_user = payment.merchant_user
            payment.save(update_fields=['merchant_account_user'])
    
    # Populate Invoice.created_by_user from merchant_user  
    for invoice in Invoice.objects.filter(created_by_user__isnull=True):
        if invoice.merchant_user:
            invoice.created_by_user = invoice.merchant_user
            invoice.save(update_fields=['created_by_user'])


def reverse_populate_user_fields(apps, schema_editor):
    """Reverse the population (clear new fields)"""
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    Invoice = apps.get_model('payments', 'Invoice')
    
    PaymentTransaction.objects.update(merchant_account_user=None)
    Invoice.objects.update(created_by_user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_add_new_user_fields'),
    ]

    operations = [
        migrations.RunPython(
            populate_new_user_fields,
            reverse_populate_user_fields,
            elidable=True,
        ),
    ]
