# Generated by Django 5.2 on 2026-08-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_invoice_token_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='settlement_chain',
            field=models.CharField(choices=[('BSC', 'BNB Smart Chain'), ('ALGORAND', 'Algorand (legacy)')], default='ALGORAND', help_text='The only chain allowed to settle this invoice', max_length=10),
        ),
    ]
