# Generated by Django 4.2.20 on 2025-07-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_populate_new_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Optional key to prevent duplicate payments', max_length=64, null=True),
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS payments_pa_idempot_056689_idx ON payments_paymenttransaction (idempotency_key);",
            reverse_sql="DROP INDEX IF EXISTS payments_pa_idempot_056689_idx;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX IF NOT EXISTS unique_confirmed_payment_per_invoice 
            ON payments_paymenttransaction (invoice_id) 
            WHERE status = 'CONFIRMED' AND deleted_at IS NULL
            """,
            reverse_sql="DROP INDEX IF EXISTS unique_confirmed_payment_per_invoice;"
        ),
    ]