# Generated by Django 4.2.20 on 2025-07-25 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_populate_payment_method_for_existing_bankinfo'),
        ('payments', '0009_add_idempotency_field_only'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='payments_invoice_merchant_business_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_paymenttransaction_payer_business_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_paymenttransaction_merchant_business_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='payments_in_invoice_056d7c_idx',
            old_name='payments_in_invoice_440ec1_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='payments_in_merchan_d147ab_idx',
            old_name='payments_in_merchan_ec64f3_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='payments_in_status_56554b_idx',
            old_name='payments_in_status_ba8402_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='payments_in_created_d4aa22_idx',
            old_name='payments_in_created_a76cc7_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='merchant_business',
            field=models.ForeignKey(blank=True, help_text='Business entity that is the actual merchant (will be required after migration)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_received', to='users.business'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='merchant_business',
            field=models.ForeignKey(blank=True, help_text='Business entity that received the payment (will be required after migration)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_received', to='users.business'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payer_business',
            field=models.ForeignKey(blank=True, help_text='Business that made the payment (if payer is business account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_sent', to='users.business'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payer_user',
            field=models.ForeignKey(help_text='User who initiated the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['idempotency_key'], name='payments_pa_idempot_056689_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('idempotency_key__isnull', False)), fields=('payer_user', 'invoice', 'idempotency_key'), name='unique_payment_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['CONFIRMED'])), fields=('invoice',), name='unique_confirmed_payment_per_invoice'),
        ),
    ]
