# Generated by Django 4.2.20 on 2025-07-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_invoice_payments_invoice_merchant_business_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_phone',
            field=models.CharField(blank=True, help_text='Merchant phone number at transaction time (for personal businesses)', max_length=30),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_phone',
            field=models.CharField(blank=True, help_text='Payer phone number at transaction time', max_length=30),
        ),
    ]
