# Generated by Django 4.2.20 on 2025-07-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_remove_legacy_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='payments_in_merchan_d147ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_merchan_38d1c7_idx',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['merchant_business', 'status'], name='payments_in_merchan_c18eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['merchant_account_user', 'status'], name='payments_pa_merchan_0807ac_idx'),
        ),
    ]
