# Generated by Django 4.2.20 on 2025-07-28 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0029_add_business_employee_model'),
        ('payments', '0016_create_unified_transaction_table'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='unique_payment_idempotency',
        ),
        migrations.AddField(
            model_name='invoice',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='accepted_by_employee',
            field=models.ForeignKey(blank=True, help_text='Employee who accepted the cash payment for this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='accepted_by_employee',
            field=models.ForeignKey(blank=True, help_text='Employee who accepted this cash payment on behalf of the business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('ACCEPTED_BY_EMPLOYEE', 'Accepted by Employee'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='merchant_type',
            field=models.CharField(choices=[('user', 'Personal'), ('business', 'Business'), ('cash', 'Cash')], default='business', help_text='Type of merchant (always business for payments)', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_sent', to='users.account'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payer_address',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payer_type',
            field=models.CharField(choices=[('user', 'Personal'), ('business', 'Business'), ('cash', 'Cash')], default='user', help_text='Type of payer (user or business)', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payer_user',
            field=models.ForeignKey(blank=True, help_text='User who initiated the payment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=25),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('idempotency_key__isnull', False), ('payer_user__isnull', False)), fields=('payer_user', 'invoice', 'idempotency_key'), name='unique_payment_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_by_employee__isnull', False), ('deleted_at__isnull', True), ('idempotency_key__isnull', False)), fields=('accepted_by_employee', 'invoice', 'idempotency_key'), name='unique_employee_payment_idempotency'),
        ),
    ]
