# Generated by Django 4.2.20 on 2025-07-28 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0029_add_business_employee_model'),
        ('payments', '0017_remove_paymenttransaction_unique_payment_idempotency_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='unique_payment_idempotency',
        ),
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='unique_employee_payment_idempotency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='accepted_by_employee',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='accepted_by_employee',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='merchant_type',
            field=models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], default='business', help_text='Type of merchant (always business for payments)', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_sent', to='users.account'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payer_address',
            field=models.CharField(max_length=66),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payer_type',
            field=models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], default='user', help_text='Type of payer (user or business)', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payer_user',
            field=models.ForeignKey(help_text='User who initiated the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('idempotency_key__isnull', False)), fields=('payer_user', 'invoice', 'idempotency_key'), name='unique_payment_idempotency'),
        ),
    ]
