# Generated by Django 4.2.20 on 2025-07-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_remove_paymenttransaction_unique_payment_idempotency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
    ]
