# Generated by Django 5.2 on 2025-08-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_convert_amount_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='blockchain_data',
            field=models.JSONField(blank=True, help_text='Unsigned blockchain transactions for client signing', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66, unique=True),
        ),
    ]
