# Generated by Django 5.2 on 2025-08-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_add_blockchain_data_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_BLOCKCHAIN', 'Pending Blockchain'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
