# Generated by Django 5.2 on 2026-09-23 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def grant_confio_channels(apps, schema_editor):
    # Confío's own channels are verified by construction. Business and
    # institution channels wait for a staff grant against a verified KYB.
    Channel = apps.get_model('inbox', 'Channel')
    Channel.objects.filter(owner_type='SYSTEM', kind__in=['FOUNDER', 'NEWS']).update(
        official_granted_at=timezone.now(),
        official_note='Canal propio de Confío.',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0012_contentpollvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='official_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='official_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='official_note',
            field=models.CharField(blank=True, help_text='How staff confirmed who controls this channel (required to grant Oficial).', max_length=255),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('FOUNDER', 'Founder'), ('NEWS', 'News'), ('BUSINESS', 'Business'), ('INSTITUTION', 'Institution'), ('SYSTEM', 'System')], max_length=32),
        ),
        migrations.RunPython(grant_confio_channels, migrations.RunPython.noop),
    ]
