# Generated by Django 5.2 on 2026-10-04 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0013_channel_official'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('REMOVED', 'Removed')], default='PENDING', max_length=16)),
                ('decided_by_model', models.CharField(blank=True, default='', max_length=64)),
                ('escalated', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=280)),
                ('verdicts', models.JSONField(blank=True, default=list)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('rereviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='inbox.contentitem')),
                ('mentions', models.ManyToManyField(blank=True, related_name='community_mentions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='inbox.communitycomment')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_community_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SCAM', 'Estafa o fraude'), ('SPAM', 'Spam o publicidad'), ('OFFENSIVE', 'Ofensivo o acoso'), ('PERSONAL_DATA', 'Datos personales'), ('OTHER', 'Otro')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='inbox.communitycomment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comment_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SCAM', 'Estafa o fraude'), ('SPAM', 'Spam o publicidad'), ('OFFENSIVE', 'Ofensivo o acoso'), ('PERSONAL_DATA', 'Datos personales'), ('OTHER', 'Otro')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to='inbox.contentitem')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPostReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('REMOVED', 'Removed')], default='PENDING', max_length=16)),
                ('pending_image_key', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('decided_by_model', models.CharField(blank=True, default='', max_length=64)),
                ('escalated', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=280)),
                ('verdicts', models.JSONField(blank=True, default=list)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('rereviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_review', to='inbox.contentitem')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_community_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['content_item', 'parent', 'status', 'created_at'], name='inbox_cc_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['author', '-created_at'], name='inbox_cc_author_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['status', '-updated_at'], name='inbox_cc_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitycommentreport',
            constraint=models.UniqueConstraint(fields=('comment', 'reporter'), name='inbox_comment_report_uniq'),
        ),
        migrations.AddConstraint(
            model_name='communitypostreport',
            constraint=models.UniqueConstraint(fields=('content_item', 'reporter'), name='inbox_community_report_uniq'),
        ),
        migrations.AddIndex(
            model_name='communitypostreview',
            index=models.Index(fields=['status', '-created_at'], name='inbox_cpr_status_idx'),
        ),
    ]
