# Generated by Django 5.2 on 2026-10-04 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0014_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='inbox.communitycomment')),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_comment_reactions', to='inbox.reactiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('comment', 'user'), name='inbox_comment_reaction_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ProfilePictureSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('REPLACED', 'Replaced'), ('REMOVED', 'Removed')], default='PENDING', max_length=16)),
                ('pending_key', models.CharField(max_length=512, unique=True)),
                ('public_url', models.CharField(blank=True, default='', max_length=512)),
                ('decided_by_model', models.CharField(blank=True, default='', max_length=64)),
                ('escalated', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=280)),
                ('verdicts', models.JSONField(blank=True, default=list)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_profile_pictures', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pictures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='inbox_pp_user_status_idx'), models.Index(fields=['status', '-updated_at'], name='inbox_pp_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user',), name='inbox_pp_one_active_per_user')],
            },
        ),
    ]
