# Generated by Django 5.2 on 2026-10-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0015_community_reactions_profile_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='claim_token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='communitypostreview',
            name='claim_token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profilepicturesubmission',
            name='claim_token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
