# Generated by Django 5.2 on 2026-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0016_review_claim_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicturesubmission',
            name='public_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
