# Generated by Django 5.2 on 2026-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0017_profile_picture_public_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=512)),
                ('state', models.CharField(choices=[('RESERVED', 'Reserved'), ('LIVE', 'Live'), ('DOOMED', 'Doomed'), ('DELETED', 'Deleted')], default='RESERVED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'updated_at'], name='inbox_public_object_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('bucket', 'key'), name='inbox_public_object_uniq')],
            },
        ),
    ]
