# Generated by Django 4.2.20 on 2025-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_country_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token_version',
            field=models.IntegerField(default=1, help_text='Version number for JWT tokens. Incrementing this invalidates all existing tokens.'),
        ),
    ]
