# Generated by Django 5.2 on 2025-11-30 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_rename_payrollitem_item_id_e5e3f2_idx_payroll_pay_item_id_ebac96_idx_and_more'),
        ('users', '0005_employee_invitation_username_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedtransactiontable',
            name='payroll_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_transaction', to='payroll.payrollitem'),
        ),
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='transaction_type',
            field=models.CharField(choices=[('send', 'Send/Receive'), ('payment', 'Payment'), ('payroll', 'Payroll'), ('conversion', 'Conversion'), ('exchange', 'P2P Exchange'), ('reward', 'Reward'), ('presale', 'Presale Purchase')], db_index=True, max_length=10),
        ),
    ]
