# Generated by Django 4.2.20 on 2025-07-02 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account_business_delete_userprofile_account_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_first_name', models.CharField(help_text='First name as verified from documents', max_length=100)),
                ('verified_last_name', models.CharField(help_text='Last name as verified from documents', max_length=100)),
                ('verified_date_of_birth', models.DateField(help_text='Date of birth as verified from documents')),
                ('verified_nationality', models.CharField(help_text='Nationality ISO code (e.g., VEN, ARG, COL)', max_length=3)),
                ('verified_address', models.TextField(help_text='Full address as verified from documents')),
                ('verified_city', models.CharField(help_text='City as verified from documents', max_length=100)),
                ('verified_state', models.CharField(help_text='State/Province as verified from documents', max_length=100)),
                ('verified_country', models.CharField(help_text='Country ISO code as verified from documents', max_length=3)),
                ('verified_postal_code', models.CharField(blank=True, help_text='Postal code as verified from documents', max_length=20, null=True)),
                ('document_type', models.CharField(choices=[('national_id', 'Cédula de Identidad'), ('passport', 'Pasaporte'), ('drivers_license', 'Licencia de Conducir'), ('foreign_id', 'Documento de Identidad Extranjero')], help_text='Type of identification document', max_length=20)),
                ('document_number', models.CharField(help_text='Document number/ID', max_length=50)),
                ('document_issuing_country', models.CharField(help_text='Country that issued the document', max_length=3)),
                ('document_expiry_date', models.DateField(blank=True, help_text='Document expiry date if applicable', null=True)),
                ('document_front_image', models.FileField(help_text='Front side of identification document', upload_to='verification_documents/')),
                ('document_back_image', models.FileField(blank=True, help_text='Back side of identification document', null=True, upload_to='verification_documents/')),
                ('selfie_with_document', models.FileField(help_text='Selfie holding the identification document', upload_to='verification_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', help_text='Current verification status', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date and time when verification was approved', null=True)),
                ('rejected_reason', models.TextField(blank=True, help_text='Reason for rejection if verification was rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User being verified', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin user who approved the verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity Verification',
                'verbose_name_plural': 'Identity Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
