# Generated by Django 5.2 on 2025-12-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_analytics_models'),
        ('users', '0006_add_payroll_to_unified_transactions'),
    ]

    operations = [
    ]
