# Generated by Django 5.2 on 2025-12-13 06:54

import users.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20251208_0321'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='countrymetrics',
            new_name='users_count_date_14278e_idx',
            old_name='users_country_date_country_idx',
        ),
        migrations.RenameIndex(
            model_name='countrymetrics',
            new_name='users_count_country_e24c0d_idx',
            old_name='users_country_country_date_idx',
        ),
        migrations.RenameIndex(
            model_name='countrymetrics',
            new_name='users_count_created_8a8ebb_idx',
            old_name='users_country_created_idx',
        ),
        migrations.RenameIndex(
            model_name='dailymetrics',
            new_name='users_daily_date_a7ccdb_idx',
            old_name='users_daily_date_idx',
        ),
        migrations.RenameIndex(
            model_name='dailymetrics',
            new_name='users_daily_created_5f89fd_idx',
            old_name='users_daily_created_idx',
        ),
        migrations.AddField(
            model_name='walletderivationpepper',
            name='encrypted_pepper',
            field=users.fields.EncryptedCharField(blank=True, help_text='Encrypted version of the pepper (migration phase)', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='walletpepper',
            name='encrypted_pepper',
            field=users.fields.EncryptedCharField(blank=True, help_text='Encrypted version of the pepper (migration phase)', max_length=512, null=True),
        ),
    ]
