# Generated by Django 4.2.20 on 2025-07-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0012_add_payment_method_fields'),
        ('users', '0008_country_bank_bankinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankinfo',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterUniqueTogether(
            name='bankinfo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Type of payment method (bank, fintech, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_accounts', to='p2p_exchange.p2ppaymentmethod'),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='username',
            field=models.CharField(blank=True, help_text='Username/handle (for some fintech platforms)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='account',
            field=models.ForeignKey(help_text='Account that owns this payment method', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.account'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='account_holder_name',
            field=models.CharField(help_text='Full name of the account/payment method holder', max_length=200),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account number (for banks) or identifier (for some fintech)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='account_type',
            field=models.CharField(blank=True, choices=[('ahorro', 'Cuenta de Ahorros'), ('corriente', 'Cuenta Corriente'), ('nomina', 'Cuenta Nómina')], help_text='Type of bank account (only for banks)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use payment_method.bank instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.bank'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='country',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use payment_method.country_code instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.country'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address (for PayPal, Wise, etc.)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='identification_number',
            field=models.CharField(blank=True, help_text='Identification number (required for some countries/banks)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number (for mobile wallets like Nequi, Yape, Pago Móvil)', max_length=20, null=True),
        ),
    ]
