# Generated by Django 5.2 on 2025-12-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_users_country_date_country_idx_users_count_date_14278e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_keyless_migrated',
            field=models.BooleanField(default=False, help_text='Whether this account has migrated to V2 keyless wallet (server-side tracking)'),
        ),
    ]
