# Generated by Django 5.2 on 2025-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_account_is_keyless_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_device_name',
            field=models.CharField(blank=True, help_text='Name of the device that performed the backup (e.g. iPhone 15)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='backup_provider',
            field=models.CharField(blank=True, choices=[('google_drive', 'Google Drive'), ('icloud', 'iCloud')], help_text='Provider where the wallet backup was last verified', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='backup_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful backup verification (Response 200 OK)', null=True),
        ),
    ]
