# Generated by Django 5.2 on 2025-12-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_backup_device_name_user_backup_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_keyless_migrated',
            field=models.BooleanField(default=False, help_text='True if the user has migrated to V2 architecture (Manifest + UUID)'),
        ),
    ]
