# Generated by Django 5.2 on 2025-12-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_keyless_migrated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_keyless_migrated',
        ),
    ]
