# Generated by Django 5.2 on 2025-12-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_is_keyless_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_os',
            field=models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], help_text="Operating System of the user's primary device", max_length=20, null=True),
        ),
    ]
