# Generated by Django 5.2 on 2025-12-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0015_alter_referralrewardevent_internal_id'),
        ('users', '0013_user_platform_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedtransactiontable',
            name='referral_reward_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_transaction', to='achievements.referralrewardevent'),
        ),
    ]
