# Generated by Django 4.2.20 on 2025-07-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_update_unified_transactions_view_invitation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('send', 'Send/Receive'), ('payment', 'Payment')], max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.CharField(max_length=32)),
                ('token_type', models.CharField(choices=[('cUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], max_length=10)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('error_message', models.TextField(blank=True)),
                ('sender_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], max_length=10)),
                ('sender_display_name', models.CharField(blank=True, max_length=255)),
                ('sender_phone', models.CharField(blank=True, max_length=30)),
                ('sender_address', models.CharField(max_length=66)),
                ('counterparty_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], max_length=10)),
                ('counterparty_display_name', models.CharField(blank=True, max_length=255)),
                ('counterparty_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('counterparty_address', models.CharField(max_length=66)),
                ('description', models.TextField(blank=True)),
                ('invoice_id', models.CharField(blank=True, max_length=32, null=True)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=32, null=True)),
                ('from_address', models.CharField(max_length=66)),
                ('to_address', models.CharField(max_length=66)),
                ('is_invitation', models.BooleanField(default=False)),
                ('invitation_claimed', models.BooleanField(default=False)),
                ('invitation_reverted', models.BooleanField(default=False)),
                ('invitation_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unified_transactions_view',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
