# Generated by Django 4.2.20 on 2025-07-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_fix_conversion_status_mapping'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS unified_transactions_view;
            CREATE VIEW unified_transactions_view AS
            SELECT 
                -- Common fields
                'send' as transaction_type,
                st.id,
                st.created_at,
                st.updated_at,
                st.deleted_at,
                st.amount,
                st.token_type,
                st.status,
                st.transaction_hash,
                st.error_message,
                
                -- Sender info
                st.sender_user_id,
                st.sender_business_id,
                st.sender_type,
                st.sender_display_name,
                st.sender_phone,
                st.sender_address,
                
                -- Recipient info (map to counterparty fields)
                st.recipient_user_id as counterparty_user_id,
                st.recipient_business_id as counterparty_business_id,
                st.recipient_type as counterparty_type,
                st.recipient_display_name as counterparty_display_name,
                st.recipient_phone as counterparty_phone,
                st.recipient_address as counterparty_address,
                
                -- Additional send-specific fields
                'Transferencia' as description,
                NULL as invoice_id,
                NULL as payment_transaction_id,
                
                -- Computed direction fields
                st.sender_address as from_address,
                st.recipient_address as to_address,
                
                -- Invitation tracking fields
                st.is_invitation,
                st.invitation_claimed,
                st.invitation_reverted,
                st.invitation_expires_at
                
            FROM send_sendtransaction st
            WHERE st.deleted_at IS NULL
            
            UNION ALL
            
            SELECT 
                -- Common fields
                'payment' as transaction_type,
                pt.id,
                pt.created_at,
                pt.updated_at,
                pt.deleted_at,
                pt.amount,
                pt.token_type,
                pt.status,
                pt.transaction_hash,
                pt.error_message,
                
                -- Payer info (sender)
                pt.payer_user_id as sender_user_id,
                pt.payer_business_id as sender_business_id,
                pt.payer_type as sender_type,
                pt.payer_display_name as sender_display_name,
                pt.payer_phone as sender_phone,
                pt.payer_address as sender_address,
                
                -- Merchant info (recipient/counterparty)
                pt.merchant_account_user_id as counterparty_user_id,
                pt.merchant_business_id as counterparty_business_id,
                pt.merchant_type as counterparty_type,
                pt.merchant_display_name as counterparty_display_name,
                NULL as counterparty_phone,  -- Merchants don't have phone in payment context
                pt.merchant_address as counterparty_address,
                
                -- Payment-specific fields
                pt.description,
                pt.invoice_id,
                pt.payment_transaction_id,
                
                -- Computed direction fields
                pt.payer_address as from_address,
                pt.merchant_address as to_address,
                
                -- Invitation tracking fields
                false as is_invitation,
                false as invitation_claimed,
                false as invitation_reverted,
                NULL as invitation_expires_at
                
            FROM payments_paymenttransaction pt
            WHERE pt.deleted_at IS NULL
            
            UNION ALL
            
            SELECT 
                -- Common fields
                'conversion' as transaction_type,
                cv.id,
                cv.created_at,
                cv.updated_at,
                cv.deleted_at,
                cv.from_amount::varchar(32) as amount,
                CASE 
                    WHEN cv.conversion_type = 'usdc_to_cusd' THEN 'USDC'
                    ELSE 'cUSD'
                END as token_type,
                CASE 
                    WHEN cv.status = 'COMPLETED' THEN 'CONFIRMED'
                    WHEN cv.status = 'PROCESSING' THEN 'SPONSORING'
                    ELSE cv.status
                END as status,
                cv.from_transaction_hash as transaction_hash,
                cv.error_message,
                
                -- Actor info (sender - the one converting)
                cv.actor_user_id as sender_user_id,
                cv.actor_business_id as sender_business_id,
                cv.actor_type as sender_type,
                cv.actor_display_name as sender_display_name,
                CASE 
                    WHEN cv.actor_type = 'user' THEN au.phone_number
                    ELSE NULL
                END as sender_phone,
                cv.actor_address as sender_address,
                
                -- No counterparty for conversions (self-transaction)
                NULL as counterparty_user_id,
                NULL as counterparty_business_id,
                'user' as counterparty_type,
                'Confío System' as counterparty_display_name,
                NULL as counterparty_phone,
                '0x0' as counterparty_address,
                
                -- Conversion details in description
                CONCAT(
                    'Conversión: ',
                    cv.from_amount,
                    ' ',
                    CASE 
                        WHEN cv.conversion_type = 'usdc_to_cusd' THEN 'USDC → '
                        ELSE 'cUSD → '
                    END,
                    cv.to_amount,
                    ' ',
                    CASE 
                        WHEN cv.conversion_type = 'usdc_to_cusd' THEN 'cUSD'
                        ELSE 'USDC'
                    END
                ) as description,
                NULL as invoice_id,
                NULL as payment_transaction_id,
                
                -- For conversions, from/to addresses are the same (actor's address)
                cv.actor_address as from_address,
                cv.actor_address as to_address,
                
                -- No invitations for conversions
                false as is_invitation,
                false as invitation_claimed,
                false as invitation_reverted,
                NULL as invitation_expires_at
                
            FROM conversions cv
            LEFT JOIN users_user au ON cv.actor_user_id = au.id
            WHERE cv.is_deleted = false;
            """,
            reverse_sql="DROP VIEW IF EXISTS unified_transactions_view;"
        ),
    ]