# Generated by Codex on 2026-06-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanitarian', '0003_seed_venezuela_volunteer_copy'),
        ('users', '0023_user_icp_rating_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedtransactiontable',
            name='humanitarian_donation',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='unified_transaction',
                to='humanitarian.humanitariandonation',
            ),
        ),
        migrations.AddField(
            model_name='unifiedtransactiontable',
            name='humanitarian_release',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='unified_transaction',
                to='humanitarian.humanitarianrelease',
            ),
        ),
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='transaction_type',
            field=models.CharField(
                choices=[
                    ('send', 'Send/Receive'),
                    ('payment', 'Payment'),
                    ('payroll', 'Payroll'),
                    ('conversion', 'Conversion'),
                    ('exchange', 'P2P Exchange'),
                    ('reward', 'Reward'),
                    ('presale', 'Presale Purchase'),
                    ('ramp', 'Ramp'),
                    ('humanitarian', 'Humanitarian Aid'),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
