# Generated by Django 4.2.20 on 2025-07-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_p2p_trades_to_unified_view'),
    ]

    operations = [
    ]
