# Generated by Django 5.2 on 2026-07-04 15:17

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_soft_delete_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funnelevent',
            options={'verbose_name': 'Funnel Event', 'verbose_name_plural': 'Funnel Events (raw, 90d)'},
        ),
        migrations.RenameIndex(
            model_name='funneldailyrollup',
            new_name='users_funne_date_f5bf8e_idx',
            old_name='users_funne_date_ev_idx',
        ),
        migrations.RenameIndex(
            model_name='funneldailyrollup',
            new_name='users_funne_event_n_299cf4_idx',
            old_name='users_funne_ev_co_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='funneldailyrollup',
            new_name='users_funne_event_n_239a2c_idx',
            old_name='users_funne_ev_so__750_idx',
        ),
        migrations.RenameIndex(
            model_name='funnelevent',
            new_name='users_funne_event_n_3f5bfb_idx',
            old_name='users_funne_event_n_c6f_idx',
        ),
        migrations.RenameIndex(
            model_name='funnelevent',
            new_name='users_funne_country_e15213_idx',
            old_name='users_funne_country_eca_idx',
        ),
        migrations.RenameIndex(
            model_name='funnelevent',
            new_name='users_funne_source__e04b0c_idx',
            old_name='users_funne_source__d89_idx',
        ),
        migrations.RenameIndex(
            model_name='funnelevent',
            new_name='users_funne_channel_45cb85_idx',
            old_name='users_funne_channel_6a0_idx',
        ),
        migrations.RenameIndex(
            model_name='funnelevent',
            new_name='users_funne_user_id_4527b3_idx',
            old_name='users_funne_user_ev_idx',
        ),
        migrations.RenameIndex(
            model_name='funnelevent',
            new_name='users_funne_session_ec7bce_idx',
            old_name='users_funne_session_idx',
        ),
        migrations.AlterField(
            model_name='funneldailyrollup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='funnelevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confio_icp_other_text',
            field=models.TextField(blank=True, help_text='Free-text "Otra razón" — 500-char cap, control chars stripped on save', null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='confio_icp_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='ICP segmentation tags chosen by user (multi-select)', size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='confio_rating_prompted_at',
            field=models.DateTimeField(blank=True, help_text='Set when submitConfioRating mutation succeeds. Gates modal re-fire.', null=True),
        ),
    ]
