# Generated by Django 4.2.20 on 2025-07-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_update_unified_view_ordering'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS unified_transactions_view;
            CREATE VIEW unified_transactions_view AS
            SELECT 
                -- Common fields
                'send' as transaction_type,
                st.id,
                st.created_at,
                st.updated_at,
                st.deleted_at,
                st.amount,
                st.token_type,
                st.status,
                st.transaction_hash,
                st.error_message,
                
                -- Sender info
                st.sender_user_id,
                st.sender_business_id,
                st.sender_type,
                st.sender_display_name,
                st.sender_phone,
                st.sender_address,
                
                -- Recipient info (map to counterparty fields)
                st.recipient_user_id as counterparty_user_id,
                st.recipient_business_id as counterparty_business_id,
                st.recipient_type as counterparty_type,
                st.recipient_display_name as counterparty_display_name,
                st.recipient_phone as counterparty_phone,
                st.recipient_address as counterparty_address,
                
                -- Additional send-specific fields
                'Transferencia' as description,
                NULL as invoice_id,
                NULL as payment_transaction_id,
                
                -- From/To addresses for direction calculation
                st.sender_address as from_address,
                st.recipient_address as to_address,
                
                -- Invitation fields
                st.is_invitation,
                st.invitation_claimed,
                st.invitation_reverted,
                st.invitation_expires_at
            FROM send_sendtransaction st
            WHERE st.deleted_at IS NULL
            
            UNION ALL
            
            SELECT 
                -- Common fields
                'payment' as transaction_type,
                pt.id,
                pt.created_at,
                pt.updated_at,
                pt.deleted_at,
                pt.amount,
                pt.token_type,
                CASE 
                    WHEN pt.status = 'PAID' THEN 'CONFIRMED'
                    ELSE pt.status
                END as status,
                pt.transaction_hash,
                pt.error_message,
                
                -- Map payment relationships
                -- Payer is the sender
                pt.payer_user_id as sender_user_id,
                pt.payer_business_id as sender_business_id,
                pt.payer_type as sender_type,
                pt.payer_display_name as sender_display_name,
                pt.payer_phone as sender_phone,
                pt.payer_address as sender_address,
                
                -- Merchant is the counterparty
                pt.merchant_account_user_id as counterparty_user_id,
                pt.merchant_business_id as counterparty_business_id,
                pt.merchant_type as counterparty_type,
                pt.merchant_display_name as counterparty_display_name,
                NULL as counterparty_phone,
                pt.merchant_address as counterparty_address,
                
                -- Additional payment-specific fields
                COALESCE(i.description, 'Pago') as description,
                pt.invoice_id,
                pt.id as payment_transaction_id,
                
                -- From/To addresses for direction calculation
                pt.payer_address as from_address,
                pt.merchant_address as to_address,
                
                -- No invitation for payments
                FALSE as is_invitation,
                FALSE as invitation_claimed,
                FALSE as invitation_reverted,
                NULL as invitation_expires_at
            FROM payments_paymenttransaction pt
            LEFT JOIN payments_invoice i ON pt.invoice_id = i.id
            WHERE pt.deleted_at IS NULL
            
            UNION ALL
            
            SELECT 
                -- Common fields
                'conversion' as transaction_type,
                cv.id,
                cv.created_at,
                cv.updated_at,
                cv.deleted_at,
                cv.from_amount::varchar(32) as amount,
                CASE 
                    WHEN cv.conversion_type = 'usdc_to_cusd' THEN 'USDC'
                    ELSE 'cUSD'
                END as token_type,
                CASE 
                    WHEN cv.status = 'COMPLETED' THEN 'CONFIRMED'
                    WHEN cv.status = 'PROCESSING' THEN 'SPONSORING'
                    ELSE cv.status
                END as status,
                cv.from_transaction_hash as transaction_hash,
                cv.error_message,
                
                -- Actor info (sender - the one converting)
                cv.actor_user_id as sender_user_id,
                cv.actor_business_id as sender_business_id,
                cv.actor_type as sender_type,
                cv.actor_display_name as sender_display_name,
                CASE 
                    WHEN cv.actor_type = 'user' THEN au.phone_number
                    ELSE NULL
                END as sender_phone,
                cv.actor_address as sender_address,
                
                -- No counterparty for conversions (self-transaction)
                NULL as counterparty_user_id,
                NULL as counterparty_business_id,
                'user' as counterparty_type,
                'Confío System' as counterparty_display_name,
                NULL as counterparty_phone,
                '0x0' as counterparty_address,
                
                -- Conversion details in description
                CONCAT(
                    'Conversión: ',
                    cv.from_amount,
                    ' ',
                    CASE 
                        WHEN cv.conversion_type = 'usdc_to_cusd' THEN 'USDC → '
                        ELSE 'cUSD → '
                    END,
                    cv.to_amount,
                    ' ',
                    CASE 
                        WHEN cv.conversion_type = 'usdc_to_cusd' THEN 'cUSD'
                        ELSE 'USDC'
                    END
                ) as description,
                NULL as invoice_id,
                NULL as payment_transaction_id,
                
                -- For conversions, from/to addresses are the same (actor's address)
                cv.actor_address as from_address,
                cv.actor_address as to_address,
                
                -- No invitations for conversions
                false as is_invitation,
                false as invitation_claimed,
                false as invitation_reverted,
                NULL as invitation_expires_at
            FROM conversions cv
            LEFT JOIN users_user au ON cv.actor_user_id = au.id
            WHERE cv.is_deleted = false
            
            UNION ALL
            
            SELECT 
                -- Common fields
                'exchange' as transaction_type,
                pt.id,
                -- Use completed_at when available (when funds are released), otherwise created_at
                COALESCE(pt.completed_at, pt.created_at) as created_at,
                pt.updated_at,
                pt.deleted_at,
                CAST(pt.crypto_amount AS VARCHAR) as amount,
                -- Get token type from the offer
                COALESCE(po.token_type, 'cUSD') as token_type,
                -- Map P2P trade status to unified status
                CASE 
                    WHEN pt.status IN ('COMPLETED', 'CRYPTO_RELEASED') THEN 'CONFIRMED'
                    WHEN pt.status IN ('CANCELLED', 'EXPIRED') THEN 'FAILED'
                    ELSE 'PENDING'
                END as status,
                '' as transaction_hash,
                '' as error_message,
                
                -- For P2P trades, determine sender/receiver based on trade type
                -- If buying crypto: sender is the one sending fiat (buyer), counterparty is seller
                -- If selling crypto: sender is the one sending crypto (seller), counterparty is buyer
                CASE 
                    WHEN po.exchange_type = 'BUY' THEN pt.seller_user_id
                    ELSE pt.buyer_user_id
                END as sender_user_id,
                CASE 
                    WHEN po.exchange_type = 'BUY' THEN pt.seller_business_id
                    ELSE pt.buyer_business_id
                END as sender_business_id,
                CASE 
                    WHEN po.exchange_type = 'BUY' AND pt.seller_business_id IS NOT NULL THEN 'business'
                    WHEN po.exchange_type = 'BUY' THEN 'user'
                    WHEN po.exchange_type = 'SELL' AND pt.buyer_business_id IS NOT NULL THEN 'business'
                    ELSE 'user'
                END as sender_type,
                CASE 
                    WHEN po.exchange_type = 'BUY' THEN 
                        COALESCE(sb.name, CONCAT(su.first_name, ' ', su.last_name), su.username)
                    ELSE 
                        COALESCE(bb.name, CONCAT(bu.first_name, ' ', bu.last_name), bu.username)
                END as sender_display_name,
                CASE 
                    WHEN po.exchange_type = 'BUY' THEN su.phone_number
                    ELSE bu.phone_number
                END as sender_phone,
                '' as sender_address,
                
                -- Counterparty info
                CASE 
                    WHEN po.exchange_type = 'BUY' THEN pt.buyer_user_id
                    ELSE pt.seller_user_id
                END as counterparty_user_id,
                CASE 
                    WHEN po.exchange_type = 'BUY' THEN pt.buyer_business_id
                    ELSE pt.seller_business_id
                END as counterparty_business_id,
                CASE 
                    WHEN po.exchange_type = 'BUY' AND pt.buyer_business_id IS NOT NULL THEN 'business'
                    WHEN po.exchange_type = 'BUY' THEN 'user'
                    WHEN po.exchange_type = 'SELL' AND pt.seller_business_id IS NOT NULL THEN 'business'
                    ELSE 'user'
                END as counterparty_type,
                CASE 
                    WHEN po.exchange_type = 'BUY' THEN 
                        COALESCE(bb.name, CONCAT(bu.first_name, ' ', bu.last_name), bu.username)
                    ELSE 
                        COALESCE(sb.name, CONCAT(su.first_name, ' ', su.last_name), su.username)
                END as counterparty_display_name,
                CASE 
                    WHEN po.exchange_type = 'BUY' THEN bu.phone_number
                    ELSE su.phone_number
                END as counterparty_phone,
                '' as counterparty_address,
                
                -- P2P trade description
                CONCAT(
                    'Intercambio P2P: ',
                    pt.crypto_amount,
                    ' ',
                    COALESCE(po.token_type, 'cUSD'),
                    ' por ',
                    pt.fiat_amount,
                    ' ',
                    pt.currency_code
                ) as description,
                NULL as invoice_id,
                NULL as payment_transaction_id,
                
                -- No real blockchain addresses for P2P trades
                '' as from_address,
                '' as to_address,
                
                -- No invitation for P2P trades
                FALSE as is_invitation,
                FALSE as invitation_claimed,
                FALSE as invitation_reverted,
                NULL as invitation_expires_at
            FROM p2p_exchange_p2ptrade pt
            LEFT JOIN p2p_exchange_p2poffer po ON pt.offer_id = po.id
            LEFT JOIN users_user bu ON pt.buyer_user_id = bu.id
            LEFT JOIN users_user su ON pt.seller_user_id = su.id
            LEFT JOIN users_business bb ON pt.buyer_business_id = bb.id
            LEFT JOIN users_business sb ON pt.seller_business_id = sb.id
            WHERE pt.deleted_at IS NULL
              AND pt.status IN ('COMPLETED', 'CRYPTO_RELEASED')
            """,
            reverse_sql="DROP VIEW IF EXISTS unified_transactions_view;"
        )
    ]