# Generated by Django 5.2 on 2026-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_funnelevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bsc_address',
            field=models.CharField(blank=True, help_text='BSC (savings chain) address for this account — derived client-side from the same seed (confio/evm/v1)', max_length=42, null=True),
        ),
    ]
