# Generated by Django 4.2.20 on 2025-07-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_fix_p2p_trade_dates_in_unified_view'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP VIEW IF EXISTS unified_transactions_view;",
            reverse_sql="-- View will be recreated by reversing other migrations"
        ),
    ]