# Generated by Django 4.2.20 on 2025-07-27 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0015_support_external_deposits'),
        ('conversion', '0005_create_unified_transaction_table'),
        ('p2p_exchange', '0030_add_favoriter_business'),
        ('payments', '0016_create_unified_transaction_table'),
        ('users', '0027_drop_unified_transactions_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedTransactionTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('send', 'Send/Receive'), ('payment', 'Payment'), ('conversion', 'Conversion'), ('exchange', 'P2P Exchange')], db_index=True, max_length=10)),
                ('amount', models.CharField(max_length=32)),
                ('token_type', models.CharField(choices=[('cUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], max_length=10)),
                ('transaction_hash', models.CharField(blank=True, default='', max_length=66)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sender_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business'), ('external', 'External')], max_length=10)),
                ('sender_display_name', models.CharField(blank=True, max_length=255)),
                ('sender_phone', models.CharField(blank=True, max_length=30)),
                ('sender_address', models.CharField(blank=True, default='', max_length=66)),
                ('counterparty_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business'), ('external', 'External')], max_length=10)),
                ('counterparty_display_name', models.CharField(blank=True, max_length=255)),
                ('counterparty_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('counterparty_address', models.CharField(blank=True, default='', max_length=66)),
                ('description', models.TextField(blank=True)),
                ('invoice_id', models.CharField(blank=True, max_length=32, null=True)),
                ('payment_reference_id', models.CharField(blank=True, max_length=32, null=True)),
                ('from_address', models.CharField(blank=True, default='', max_length=66)),
                ('to_address', models.CharField(blank=True, default='', max_length=66)),
                ('is_invitation', models.BooleanField(default=False)),
                ('invitation_claimed', models.BooleanField(default=False)),
                ('invitation_reverted', models.BooleanField(default=False)),
                ('invitation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_transaction', to='conversion.conversion')),
                ('counterparty_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_table_counterparty_transactions', to='users.business')),
                ('counterparty_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_table_counterparty_transactions', to=settings.AUTH_USER_MODEL)),
                ('p2p_trade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_transaction', to='p2p_exchange.p2ptrade')),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_transaction', to='payments.paymenttransaction')),
                ('send_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_transaction', to='send.sendtransaction')),
                ('sender_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_table_sent_transactions', to='users.business')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_table_sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unified_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='unified_tra_created_cbbaba_idx'), models.Index(fields=['transaction_type', '-created_at'], name='unified_tra_transac_47d842_idx'), models.Index(fields=['sender_user', '-created_at'], name='unified_tra_sender__541842_idx'), models.Index(fields=['sender_business', '-created_at'], name='unified_tra_sender__ddd5b2_idx'), models.Index(fields=['counterparty_user', '-created_at'], name='unified_tra_counter_c6c09a_idx'), models.Index(fields=['counterparty_business', '-created_at'], name='unified_tra_counter_465c28_idx'), models.Index(fields=['status', '-created_at'], name='unified_tra_status_4bf89c_idx'), models.Index(fields=['token_type', '-created_at'], name='unified_tra_token_t_1f7468_idx')],
            },
        ),
    ]
