# Generated by Django 5.2 on 2026-07-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_account_bsc_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='token_type',
            field=models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin'), ('ALGO', 'ALGO'), ('CUSD_PLUS', 'Confío Dollar Plus'), ('USDT', 'Tether USD')], max_length=10),
        ),
    ]
