# Generated by Django 5.2 on 2026-07-31 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusd_plus', '0006_alter_sponsoredbatch_kind_cusdplusmovement'),
        ('users', '0028_alter_unifiedtransactiontable_token_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedtransactiontable',
            name='cusd_plus_conversion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_transaction', to='cusd_plus.cusdplusconversion'),
        ),
    ]
