# Generated by Django 4.2.20 on 2025-07-28 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_create_unified_transaction_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('role', models.CharField(choices=[('cashier', 'Cashier'), ('manager', 'Manager'), ('admin', 'Administrator')], default='cashier', help_text='Employee role determining base permissions', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Custom permissions overriding role defaults')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this employee is currently active')),
                ('hired_at', models.DateTimeField(auto_now_add=True, help_text='When the employee was added')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When the employee was deactivated', null=True)),
                ('shift_start_time', models.TimeField(blank=True, help_text='Daily shift start time', null=True)),
                ('shift_end_time', models.TimeField(blank=True, help_text='Daily shift end time', null=True)),
                ('daily_transaction_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum daily transaction amount', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this employee')),
                ('business', models.ForeignKey(help_text='The business this employee works for', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.business')),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User who deactivated this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_deactivated', to=settings.AUTH_USER_MODEL)),
                ('hired_by', models.ForeignKey(blank=True, help_text='User who added this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_hired', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who is an employee', on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hired_at'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='users_busin_busines_62c92b_idx'), models.Index(fields=['user', 'is_active'], name='users_busin_user_id_266894_idx')],
                'unique_together': {('business', 'user')},
            },
        ),
    ]
