# Generated by Django 5.2 on 2026-08-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_unifiedtransactiontable_cusd_plus_conversion'),
        # The rows must be moved onto conversion.Conversion before this
        # column disappears (cusd_plus.0011 does the move + repoint).
        ('cusd_plus', '0011_merge_conversions_into_conversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiedtransactiontable',
            name='cusd_plus_conversion',
        ),
    ]
