# Generated by Django 4.2.20 on 2025-07-28 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models_employee


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_add_business_employee_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('invitation_code', models.CharField(default=users.models_employee.generate_invitation_code, editable=False, max_length=32, unique=True)),
                ('employee_phone', models.CharField(help_text='Phone number of the invited employee', max_length=20)),
                ('employee_phone_country', models.CharField(help_text='ISO country code for the phone number', max_length=2)),
                ('employee_name', models.CharField(blank=True, help_text='Name of the invited employee (optional)', max_length=255)),
                ('role', models.CharField(choices=[('cashier', 'Cashier'), ('manager', 'Manager'), ('admin', 'Administrator')], default='cashier', max_length=20)),
                ('permissions', models.JSONField(blank=True, help_text='Custom permissions that override role defaults', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Optional message to include with the invitation')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_invitations', to='users.business')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invitation_code'], name='users_emplo_invitat_e81015_idx'), models.Index(fields=['business', 'status'], name='users_emplo_busines_c33c12_idx'), models.Index(fields=['employee_phone', 'status'], name='users_emplo_employe_be6d32_idx'), models.Index(fields=['expires_at'], name='users_emplo_expires_da7a25_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('payment_accepted', 'Payment Accepted'), ('invoice_created', 'Invoice Created'), ('invoice_cancelled', 'Invoice Cancelled'), ('account_accessed', 'Account Accessed'), ('balance_viewed', 'Balance Viewed'), ('transaction_viewed', 'Transaction Viewed'), ('settings_changed', 'Settings Changed')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('invoice_id', models.CharField(blank=True, help_text='Related invoice ID if applicable', max_length=32, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Related transaction hash if applicable', max_length=66, null=True)),
                ('amount', models.CharField(blank=True, help_text='Transaction amount if applicable', max_length=32, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_activity_logs', to='users.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['business', 'timestamp'], name='users_emplo_busines_067881_idx'), models.Index(fields=['employee', 'timestamp'], name='users_emplo_employe_bdbb76_idx'), models.Index(fields=['action', 'timestamp'], name='users_emplo_action_38f3f2_idx'), models.Index(fields=['invoice_id'], name='users_emplo_invoice_6ef086_idx'), models.Index(fields=['transaction_id'], name='users_emplo_transac_31b47b_idx')],
            },
        ),
    ]
