# Generated by Django 4.2.20 on 2025-07-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_employeeinvitation_employeeactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinvitation',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Custom permissions that override role defaults'),
        ),
    ]
