# Generated by Django 4.2.20 on 2025-07-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_fix_employee_invitation_permissions_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessemployee',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('cashier', 'Cashier')], default='cashier', help_text='Employee role determining base permissions', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('cashier', 'Cashier')], default='cashier', max_length=20),
        ),
    ]
