# Generated by Django 5.2 on 2026-08-02 13:49

from django.db import migrations, models


def label_existing_cusd_plus(apps, schema_editor):
    """Existing cUSD+ rows already hold dollar values, not shares.

    Every writer that has ever produced one stores a USD figure (the savings
    conversion's quote, the scanner's shares-through-price-per-share, the
    dollars requested by send and payroll), so the historical rows carry the
    same convention the model now stamps going forward. Labelling them keeps
    old and new cards comparable instead of leaving a silent cutover date.
    """
    U = apps.get_model('users', 'UnifiedTransactionTable')
    n = U.objects.filter(token_type='CUSD_PLUS').update(amount_denomination='USD_VALUE')
    print(f"  labelled {n} existing cUSD+ row(s) as USD_VALUE")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_unified_token_type_canonical'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedtransactiontable',
            name='amount_denomination',
            field=models.CharField(choices=[('TOKEN_UNITS', 'Token units (non-accruing: 1 unit = 1 token)'), ('USD_VALUE', 'Dollar value at the time of the transaction'), ('SHARES', 'Accruing-vault share count')], default='TOKEN_UNITS', help_text='Unit of `amount`. Every current cUSD+ writer stores a dollar value, not shares — see save().', max_length=16),
        ),
        migrations.RunPython(label_existing_cusd_plus, migrations.RunPython.noop),
    ]
