# Generated by Django 5.2 on 2026-08-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_business_employee_ownership_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedtransactiontable',
            name='fee_amount',
            field=models.CharField(blank=True, default='', help_text='Fee deducted from `amount` before the recipient is credited. Blank means no fee: both sides see `amount`.', max_length=32),
        ),
    ]
