# Generated by Django 5.2 on 2026-08-02 19:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_backfill_payroll_fee_amount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('bsc_address'), condition=models.Q(('bsc_address__isnull', False), models.Q(('bsc_address', ''), _negated=True), ('deleted_at__isnull', True)), name='uniq_account_bsc_address_ci'),
        ),
    ]
