# Generated by Django 4.2.20 on 2025-07-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_achievementtype_userachievement_tiktokviralshare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementtype',
            name='category',
            field=models.CharField(choices=[('onboarding', 'Bienvenida'), ('trading', 'Intercambios'), ('payments', 'Pagos y Transacciones'), ('social', 'Comunidad'), ('verification', 'Verificación'), ('ambassador', 'Embajador')], help_text='Category this achievement belongs to', max_length=20),
        ),
    ]
