# Generated by Django 4.2.20 on 2025-07-28 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_achievementtype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfioRewardBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, help_text='Total CONFIO earned from all sources', max_digits=20)),
                ('total_locked', models.DecimalField(decimal_places=2, default=0, help_text='Total CONFIO currently locked', max_digits=20)),
                ('total_unlocked', models.DecimalField(decimal_places=2, default=0, help_text='Total CONFIO available (when tokens launch)', max_digits=20)),
                ('achievement_rewards', models.DecimalField(decimal_places=2, default=0, help_text='CONFIO earned from achievements', max_digits=20)),
                ('referral_rewards', models.DecimalField(decimal_places=2, default=0, help_text='CONFIO earned from referrals', max_digits=20)),
                ('viral_rewards', models.DecimalField(decimal_places=2, default=0, help_text='CONFIO earned from viral content', max_digits=20)),
                ('presale_purchase', models.DecimalField(decimal_places=2, default=0, help_text='CONFIO purchased in presale', max_digits=20)),
                ('other_rewards', models.DecimalField(decimal_places=2, default=0, help_text='CONFIO from other sources', max_digits=20)),
                ('lock_until', models.DateTimeField(blank=True, help_text='Date when tokens will be unlocked', null=True)),
                ('last_reward_at', models.DateTimeField(blank=True, help_text='Last time user received a reward', null=True)),
                ('daily_reward_count', models.PositiveIntegerField(default=0, help_text='Number of rewards claimed today')),
                ('daily_reward_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total CONFIO claimed today', max_digits=10)),
                ('migration_address', models.CharField(blank=True, help_text='Sui wallet address for future token distribution', max_length=100, null=True)),
                ('migration_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Migration'), ('migrated', 'Migrated to Blockchain'), ('failed', 'Migration Failed')], default='pending', help_text='Status of blockchain migration', max_length=20)),
                ('user', models.OneToOneField(help_text='User who owns this balance', on_delete=django.db.models.deletion.CASCADE, related_name='confio_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CONFIO Balance',
                'verbose_name_plural': 'CONFIO Balances',
            },
        ),
        migrations.CreateModel(
            name='ConfioTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('transaction_type', models.CharField(choices=[('reward', 'Reward Earned'), ('presale', 'Presale Purchase'), ('unlock', 'Tokens Unlocked'), ('migration', 'Blockchain Migration'), ('adjustment', 'Manual Adjustment')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of CONFIO in this transaction', max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text="User's balance after this transaction", max_digits=20)),
                ('source', models.CharField(help_text='Source of the transaction (achievement slug, referral, etc)', max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the transaction')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                ('achievement', models.ForeignKey(blank=True, help_text='Related achievement if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confio_transactions', to='users.userachievement')),
                ('referral', models.ForeignKey(blank=True, help_text='Related referral if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confio_transactions', to='users.influencerreferral')),
                ('user', models.ForeignKey(help_text='User this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='confio_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_confi_user_id_f365cf_idx'), models.Index(fields=['transaction_type', '-created_at'], name='users_confi_transac_8ddcc0_idx')],
            },
        ),
    ]
