# Generated by Django 5.2 on 2026-08-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0011_payment_unique_by_source'),
        ('users', '0037_uniq_account_bsc_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedtransactiontable',
            name='sponsored_batch',
            field=models.OneToOneField(
                blank=True,
                help_text='Sponsored BSC batch that durably owns this stock-trade row.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='unified_transaction',
                to='blockchain.sponsoredbatch',
            ),
        ),
    ]
