# Generated by Django 5.2 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_uniq_account_bsc_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='solana_address',
            field=models.CharField(
                blank=True,
                help_text='Solana address for this account — derived client-side from the V2 master secret',
                max_length=44,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('solana_address__isnull', False),
                    models.Q(('solana_address', ''), _negated=True),
                    ('deleted_at__isnull', True),
                ),
                fields=('solana_address',),
                name='uniq_account_solana_address',
            ),
        ),
    ]
