# Generated by Django 4.2.20 on 2025-07-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_confiorewardbalance_confiotransaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfioTransaction',
            new_name='ConfioRewardTransaction',
        ),
        migrations.AlterModelOptions(
            name='confiorewardtransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'CONFIO Reward Transaction', 'verbose_name_plural': 'CONFIO Reward Transactions'},
        ),
    ]