# Generated by Django 4.2.20 on 2025-07-28 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_rename_confio_transaction_to_reward_transaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='confiorewardtransaction',
            new_name='users_confi_user_id_e3d32c_idx',
            old_name='users_confi_user_id_f365cf_idx',
        ),
        migrations.RenameIndex(
            model_name='confiorewardtransaction',
            new_name='users_confi_transac_a0edf8_idx',
            old_name='users_confi_transac_8ddcc0_idx',
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='slug',
            field=models.CharField(blank=True, help_text='Unique identifier for this achievement type (auto-generated from name if blank)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='confiorewardtransaction',
            name='achievement',
            field=models.ForeignKey(blank=True, help_text='Related achievement if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confio_reward_transactions', to='users.userachievement'),
        ),
        migrations.AlterField(
            model_name='confiorewardtransaction',
            name='referral',
            field=models.ForeignKey(blank=True, help_text='Related referral if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confio_reward_transactions', to='users.influencerreferral'),
        ),
        migrations.AlterField(
            model_name='confiorewardtransaction',
            name='user',
            field=models.ForeignKey(help_text='User this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='confio_reward_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
