# Generated by Django 4.2.20 on 2025-07-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_make_achievement_slug_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementtype',
            name='share_image',
            field=models.ImageField(blank=True, help_text='Generated share image for social media (1080x1080)', null=True, upload_to='achievement_shares/'),
        ),
    ]
