# Generated by Django 4.2.20 on 2025-07-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_add_achievement_share_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementtype',
            name='share_image',
        ),
    ]
