# Generated by Django 4.2.20 on 2025-07-28 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_remove_share_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerAmbassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('tier', models.CharField(choices=[('bronze', 'Bronce'), ('silver', 'Plata'), ('gold', 'Oro'), ('diamond', 'Diamante')], default='bronze', help_text='Current ambassador tier', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('revoked', 'Revocado')], default='active', help_text='Current ambassador status', max_length=20)),
                ('total_referrals', models.IntegerField(default=0, help_text='Total number of successful referrals')),
                ('active_referrals', models.IntegerField(default=0, help_text='Number of referrals active in last 30 days')),
                ('total_viral_views', models.BigIntegerField(default=0, help_text='Total views across all viral content')),
                ('monthly_viral_views', models.BigIntegerField(default=0, help_text='Views in current month')),
                ('referral_transaction_volume', models.DecimalField(decimal_places=2, default=0, help_text='Total transaction volume from referrals', max_digits=12)),
                ('confio_earned', models.DecimalField(decimal_places=2, default=0, help_text='Total CONFIO earned as ambassador', max_digits=10)),
                ('tier_achieved_at', models.DateTimeField(auto_now_add=True, help_text='When current tier was achieved')),
                ('next_tier_progress', models.IntegerField(default=0, help_text='Progress percentage to next tier (0-100)')),
                ('benefits', models.JSONField(default=dict, help_text='Current benefits based on tier')),
                ('custom_referral_code', models.CharField(blank=True, help_text='Custom referral code for ambassador', max_length=20, null=True, unique=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('performance_score', models.IntegerField(default=100, help_text='Performance score (0-100) for tier evaluation')),
                ('dedicated_support', models.BooleanField(default=False, help_text='Has access to dedicated support')),
                ('ambassador_notes', models.TextField(blank=True, help_text='Internal notes about this ambassador')),
                ('user', models.OneToOneField(help_text='User who achieved ambassador status', on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Influencer Ambassador',
                'verbose_name_plural': 'Influencer Ambassadors',
                'ordering': ['-tier', '-total_viral_views'],
            },
        ),
        migrations.CreateModel(
            name='AmbassadorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('activity_type', models.CharField(choices=[('referral', 'New Referral'), ('viral_milestone', 'Viral Milestone'), ('tier_upgrade', 'Tier Upgrade'), ('monthly_bonus', 'Monthly Bonus'), ('special_achievement', 'Special Achievement')], help_text='Type of activity', max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('confio_rewarded', models.DecimalField(decimal_places=2, default=0, help_text='CONFIO awarded for this activity', max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity data')),
                ('ambassador', models.ForeignKey(help_text='Ambassador this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.influencerambassador')),
            ],
            options={
                'verbose_name': 'Ambassador Activity',
                'verbose_name_plural': 'Ambassador Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
