# Generated by Django 4.2.20 on 2025-07-28 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_influencerambassador_ambassadoractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('action', models.CharField(help_text='Type of action that was flagged', max_length=50)),
                ('flags', models.JSONField(default=list, help_text='List of flags triggered')),
                ('metadata', models.JSONField(default=dict, help_text='Additional context about the activity')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which activity originated', null=True)),
                ('device_fingerprint', models.CharField(blank=True, help_text='Hashed device fingerprint', max_length=64, null=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Whether this activity has been reviewed')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the activity was reviewed', null=True)),
                ('action_taken', models.CharField(choices=[('none', 'No Action'), ('warning', 'Warning Issued'), ('suspended', 'Account Suspended'), ('banned', 'Account Banned')], default='none', help_text='Action taken after review', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about the review')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suspicious_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who performed the suspicious activity', on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspicious Activity',
                'verbose_name_plural': 'Suspicious Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_suspi_user_id_f363a6_idx'), models.Index(fields=['reviewed', '-created_at'], name='users_suspi_reviewe_3869f3_idx'), models.Index(fields=['device_fingerprint'], name='users_suspi_device__19122c_idx')],
            },
        ),
    ]
