# Generated by Django 5.2 on 2026-09-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_local_transfer_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnelevent',
            name='ip_country',
            field=models.CharField(blank=True, db_index=True, help_text='ISO 3166-1 alpha-2 estimated from the request IP, as opposed to `country` (declared or phone). Empty if unknown. Never the IP itself.', max_length=2),
        ),
        migrations.AddIndex(
            model_name='funnelevent',
            index=models.Index(fields=['ip_country', 'event_name', 'created_at'], name='users_funne_ip_coun_d9c9e8_idx'),
        ),
    ]
