# Generated by Django 4.2.20 on 2025-07-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_suspiciousactivity'),
    ]

    operations = [
        # Rename tiktok_username to referrer_identifier
        migrations.RenameField(
            model_name='influencerreferral',
            old_name='tiktok_username',
            new_name='referrer_identifier',
        ),
        # Add referral_type field
        migrations.AddField(
            model_name='influencerreferral',
            name='referral_type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('influencer', 'Influencer'),
                    ('friend', 'Friend'),
                ],
                default='influencer',
                help_text='Type of referral'
            ),
        ),
    ]
