# Generated by Django 4.2.20 on 2025-07-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_rename_referral_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PioneroBetaTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('last_user_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pionero Beta Tracker',
                'verbose_name_plural': 'Pionero Beta Tracker',
            },
        ),
        migrations.RemoveIndex(
            model_name='influencerreferral',
            name='users_influ_tiktok__d5d1eb_idx',
        ),
        migrations.AlterField(
            model_name='influencerreferral',
            name='referrer_identifier',
            field=models.CharField(db_index=True, help_text='Username, phone number, or influencer handle of the referrer', max_length=100),
        ),
        migrations.AddIndex(
            model_name='influencerreferral',
            index=models.Index(fields=['referrer_identifier'], name='users_influ_referre_75f6b4_idx'),
        ),
    ]
