# Generated by Django 5.2 on 2026-10-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_user_wallet_recovery_drive_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_test_account',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
