# Generated by Django 4.2.17 on 2025-07-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_add_pionero_tracker'),
        ('achievements', '0001_initial'),
    ]

    operations = [
        # This migration is intentionally empty.
        # The achievement models have been moved to the achievements app.
        # The actual model deletions are handled by Django's migration state
        # tracking, which recognizes that these models now exist in the
        # achievements app instead of the users app.
    ]