# Generated by Django 4.2.17 on 2025-07-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_add_pionero_tracker'),
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='achievementtype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='achievementtype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement_type',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='influencerreferral',
            name='influencer_user',
        ),
        migrations.RemoveField(
            model_name='influencerreferral',
            name='referred_user',
        ),
        migrations.RemoveField(
            model_name='tiktokviralshare',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='tiktokviralshare',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tiktokviralshare',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='confiorewardbalance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='confiorewardtransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='influencerambassador',
            name='assigned_manager',
        ),
        migrations.RemoveField(
            model_name='influencerambassador',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ambassadoractivity',
            name='ambassador',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='investigated_by',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='AchievementType',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
        migrations.DeleteModel(
            name='InfluencerReferral',
        ),
        migrations.DeleteModel(
            name='TikTokViralShare',
        ),
        migrations.DeleteModel(
            name='ConfioRewardBalance',
        ),
        migrations.DeleteModel(
            name='ConfioRewardTransaction',
        ),
        migrations.DeleteModel(
            name='InfluencerAmbassador',
        ),
        migrations.DeleteModel(
            name='AmbassadorActivity',
        ),
        migrations.DeleteModel(
            name='SuspiciousActivity',
        ),
        migrations.DeleteModel(
            name='PioneroBetaTracker',
        ),
    ]