# Generated by Django 5.2 on 2026-10-04 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_user_is_platform_test_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyPromptState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty_key', models.CharField(max_length=160)),
                ('skip_count', models.PositiveSmallIntegerField(default=0)),
                ('dismiss_count', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_prompt_states', to='users.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'counterparty_key'), name='uniq_counterparty_prompt_state')],
            },
        ),
        migrations.CreateModel(
            name='CounterpartyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty_key', models.CharField(help_text='business:<id> | user:<id> | bank:<code>:<acct> | dest:<id> | addr:<address>', max_length=160)),
                ('category', models.CharField(choices=[('food', 'Comida'), ('transport', 'Transporte'), ('home', 'Casa'), ('family', 'Familia'), ('work', 'Trabajo'), ('other', 'Otro')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_rules', to='users.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'counterparty_key'), name='uniq_counterparty_rule')],
            },
        ),
        migrations.CreateModel(
            name='MovementOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Comida'), ('transport', 'Transporte'), ('home', 'Casa'), ('family', 'Familia'), ('work', 'Trabajo'), ('other', 'Otro')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_overrides', to='users.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_overrides', to='users.unifiedtransactiontable')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'movement'), name='uniq_movement_override')],
            },
        ),
    ]
