# Generated by Django 4.2.20 on 2025-07-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_remove_ambassadoractivity_ambassador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('AML_REVIEW', 'Under AML Review')], max_length=10),
        ),
    ]
