# Generated by Django 5.2 on 2026-10-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_cashflow_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpartyrule',
            name='category',
            field=models.CharField(choices=[('food', 'Comida'), ('transport', 'Transporte'), ('home', 'Casa'), ('bills', 'Servicios'), ('family', 'Familia'), ('shopping', 'Compras'), ('health', 'Salud'), ('education', 'Educación'), ('leisure', 'Salidas'), ('debt', 'Deudas'), ('work', 'Trabajo'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movementoverride',
            name='category',
            field=models.CharField(choices=[('food', 'Comida'), ('transport', 'Transporte'), ('home', 'Casa'), ('bills', 'Servicios'), ('family', 'Familia'), ('shopping', 'Compras'), ('health', 'Salud'), ('education', 'Educación'), ('leisure', 'Salidas'), ('debt', 'Deudas'), ('work', 'Trabajo'), ('other', 'Otro')], max_length=20),
        ),
    ]
