# Generated by Django 5.2 on 2025-08-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_add_aml_review_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='sui_address',
            new_name='aptos_address',
        ),
        migrations.AlterField(
            model_name='account',
            name='aptos_address',
            field=models.CharField(blank=True, help_text='Last‑computed Aptos address for this account', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='counterparty_address',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='from_address',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='sender_address',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='to_address',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='transaction_hash',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
