# Generated by Django 5.2 on 2026-10-04 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_cashflow_more_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusdPlusPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('pps_wad', models.DecimalField(decimal_places=0, help_text='pPlus() at block_number, 1e18 = US$1', max_digits=40)),
                ('block_number', models.BigIntegerField()),
                ('complete', models.BooleanField(default=False, help_text='True once every holder batch was attempted (R26)')),
                ('failed_account_ids', models.JSONField(blank=True, default=list, help_text='Accounts whose balance read failed after retries; their month is unknown (R28)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CusdPlusHoldingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shares_raw', models.DecimalField(decimal_places=0, help_text='balanceOf, 18 decimals', max_digits=40)),
                ('block_number', models.BigIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cusd_plus_snapshots', to='users.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'date'), name='uniq_cusd_plus_holding_day')],
            },
        ),
    ]
