# Generated by Django 5.2 on 2025-08-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_add_wallet_pepper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletpepper',
            options={},
        ),
        migrations.RemoveField(
            model_name='walletpepper',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='walletpepper',
            name='user',
        ),
        migrations.AddField(
            model_name='walletpepper',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletpepper',
            name='scope',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='walletpepper',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='aptos_address',
            field=models.CharField(blank=True, help_text='Last‑computed Aptos address for this account (temporarily storing Algorand)', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='walletpepper',
            name='firebase_uid',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='walletpepper',
            name='pepper',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='walletpepper',
            index=models.Index(fields=['firebase_uid', 'version'], name='user_wallet_firebas_be6af7_idx'),
        ),
        migrations.AlterModelTable(
            name='walletpepper',
            table='user_wallet_pepper',
        ),
    ]
