# Generated by Django 5.2 on 2026-10-07 10:59

import re

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


PROBE_RAIL_RE = re.compile(r'^(send|receive)_([a-z]{2})_([a-z0-9]{2,24})$')

# payment_accounts.local_money.METHODS as of this migration: the ids a
# nationality-blocked opt-in can name, with (direction, ISO-2). Frozen here so
# the migration never depends on live app code.
BLOCKED_METHODS = {
    'br_pix': ('send', 'BR'), 'br_qr': ('send', 'BR'),
    'co_breb': ('send', 'CO'), 'co_qr': ('send', 'CO'),
    'mx_clabe': ('send', 'MX'), 'ar_cvu': ('send', 'AR'), 'ar_qr': ('send', 'AR'),
    'br_pix_receive': ('receive', 'BR'), 'co_breb_receive': ('receive', 'CO'),
    'mx_clabe_receive': ('receive', 'MX'), 'ar_cvu_receive': ('receive', 'AR'),
}


def _probe_rail(rail_id):
    match = PROBE_RAIL_RE.match(rail_id)
    return (match.group(1), match.group(2).upper()) if match else None


def backfill_from_confirmed_opt_ins(apps, schema_editor):
    """Everyone who already said "Sí, avísame" joins the waitlist.

    Until now that answer lived only as a FunnelEvent, which the nightly
    rollup deletes after 90 days — so this copies whatever is still there,
    for both the "Próximamente" probes and the nationality-blocked rails.
    The earliest confirmation keeps its date.
    """
    FunnelEvent = apps.get_model('users', 'FunnelEvent')
    Entry = apps.get_model('users', 'LocalRailWaitlistEntry')
    sources = {
        'local_rail_interest': ('coming_soon', _probe_rail),
        'local_rail_blocked_interest': ('nationality_blocked', BLOCKED_METHODS.get),
    }
    earliest = {}
    rows = FunnelEvent.objects.filter(
        event_name__in=list(sources), user__isnull=False,
        properties__stage='confirmed',
    ).values_list('event_name', 'user_id', 'properties', 'created_at').order_by('created_at')
    for event_name, user_id, props, created_at in rows.iterator():
        props = props if isinstance(props, dict) else {}
        rail_id = str(props.get('rail') or '')
        kind, resolve = sources[event_name]
        rail = resolve(rail_id)
        if not rail:
            continue
        earliest.setdefault((user_id, rail_id), (kind, rail[0], rail[1], created_at))
    for (user_id, rail_id), (kind, direction, country, created_at) in earliest.items():
        entry, created = Entry.objects.get_or_create(
            user_id=user_id, rail_id=rail_id,
            defaults={'direction': direction, 'country': country, 'kind': kind},
        )
        if created:
            Entry.objects.filter(pk=entry.pk).update(created_at=created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_cusd_plus_savings_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRailWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rail_id', models.CharField(db_index=True, max_length=40)),
                ('direction', models.CharField(max_length=8)),
                ('kind', models.CharField(choices=[('coming_soon', 'Coming soon (probe rail)'), ('nationality_blocked', 'Blocked for nationality')], default='coming_soon', max_length=24)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_rail_waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local rail waitlist entry',
                'verbose_name_plural': 'Local rail waitlist entries',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'rail_id'), name='uniq_local_rail_waitlist_user_rail')],
            },
        ),
        migrations.RunPython(backfill_from_confirmed_opt_ins, migrations.RunPython.noop),
    ]
