# Generated by Django 5.2 on 2025-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_rename_sui_to_aptos_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='algorand_address',
            field=models.CharField(blank=True, help_text='Algorand address for this account', max_length=58, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='algorand_verified',
            field=models.BooleanField(default=False, help_text='Whether the Algorand address ownership has been verified'),
        ),
        migrations.AddField(
            model_name='account',
            name='algorand_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the Algorand address was verified', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='web3auth_id',
            field=models.CharField(blank=True, help_text='Web3Auth user ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='web3auth_provider',
            field=models.CharField(blank=True, help_text='Web3Auth provider (google, apple, etc.)', max_length=20, null=True),
        ),
    ]
