# Generated by Django 5.2 on 2026-10-07 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_local_rail_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('ia_plus', 'Confío IA+'), ('smart_account', 'Cuenta inteligente')], max_length=24)),
                ('door', models.CharField(max_length=24)),
                ('trigger', models.CharField(blank=True, default='', max_length=24)),
                ('account_type', models.CharField(blank=True, default='', max_length=16)),
                ('funded', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('would_pay', models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='', max_length=3)),
                ('volume_range', models.CharField(blank=True, choices=[('lt_100', '< US$100'), ('100_500', 'US$100–500'), ('500_2000', 'US$500–2.000'), ('gt_2000', '> US$2.000')], default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paid offer waitlist entry',
                'verbose_name_plural': 'Paid offer waitlist entries',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='uniq_product_waitlist_user_product')],
            },
        ),
    ]
