# Generated by Django 5.2 on 2025-08-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_walletpepper_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletpepper',
            name='scope',
        ),
    ]
