# Generated by Django 5.2 on 2025-08-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_remove_scope_from_walletpepper'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpepper',
            name='grace_period_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletpepper',
            name='previous_pepper',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='walletpepper',
            name='previous_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletpepper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
