# Generated by Django 5.2 on 2025-08-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_add_grace_period_to_walletpepper'),
    ]

    operations = [
        # Step 1: Rename the field from firebase_uid to account_key
        migrations.RenameField(
            model_name='walletpepper',
            old_name='firebase_uid',
            new_name='account_key',
        ),
        
        # Step 2: Update the field definition to reflect its new purpose
        migrations.AlterField(
            model_name='walletpepper',
            name='account_key',
            field=models.CharField(
                max_length=255,
                unique=True,
                db_index=True,
                help_text='Unique key per account: user_{id}_{type}_{index} or user_{id}_business_{businessId}_{index}'
            ),
        ),
        
        # Step 3: Update the model's verbose name and options
        migrations.AlterModelOptions(
            name='walletpepper',
            options={
                'verbose_name': 'Account Wallet Pepper',
                'verbose_name_plural': 'Account Wallet Peppers',
                'ordering': ['-created_at'],
            },
        ),
    ]
