# Generated by Django 5.2 on 2025-08-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_add_wallet_derivation_pepper'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user_phone_key_active',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_phone_key',
        ),
        migrations.RemoveIndex(
            model_name='walletpepper',
            name='user_wallet_firebas_be6af7_idx',
        ),
        migrations.AddField(
            model_name='account',
            name='algorand_address',
            field=models.CharField(blank=True, help_text='Algorand address for this account', max_length=58, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='token_type',
            field=models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='walletderivationpepper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='walletpepper',
            name='grace_period_until',
            field=models.DateTimeField(blank=True, help_text='When the grace period for using previous pepper ends', null=True),
        ),
        migrations.AlterField(
            model_name='walletpepper',
            name='pepper',
            field=models.CharField(help_text='Random pepper for additional entropy', max_length=64),
        ),
        migrations.AlterField(
            model_name='walletpepper',
            name='previous_pepper',
            field=models.CharField(blank=True, help_text='Previous pepper kept during grace period', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='walletpepper',
            name='previous_version',
            field=models.IntegerField(blank=True, help_text='Previous version number', null=True),
        ),
        migrations.AlterField(
            model_name='walletpepper',
            name='rotated_at',
            field=models.DateTimeField(blank=True, help_text='When the pepper was last rotated', null=True),
        ),
        migrations.AlterField(
            model_name='walletpepper',
            name='version',
            field=models.IntegerField(default=1, help_text='Pepper version for rotation support'),
        ),
    ]
