# Generated by Django 5.2 on 2025-08-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_rename_aptos_to_algorand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('AML_REVIEW', 'Under AML Review')], max_length=20),
        ),
    ]
