# Generated by Django 5.2 on 2025-08-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_unified_status_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedtransactiontable',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_SIG', 'Pending Signature'), ('PENDING_BLOCKCHAIN', 'Pending Blockchain'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('AML_REVIEW', 'Under AML Review')], max_length=20),
        ),
    ]
