# Generated by Django 5.2 on 2026-07-04 15:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0026_alter_funnelevent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CusdPlusConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], max_length=10)),
                ('actor_display_name', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('to_savings', 'cUSD -> cUSD+ (Ahorrar)'), ('from_savings', 'cUSD+ -> cUSD (Retirar)')], max_length=15)),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=19)),
                ('quoted_cost_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Total cost pct the user accepted (client-quoted, decision b)', max_digits=8)),
                ('quoted_receive_usd', models.DecimalField(decimal_places=6, max_digits=19)),
                ('user_algo_address', models.CharField(blank=True, max_length=58)),
                ('user_bsc_address', models.CharField(blank=True, max_length=42)),
                ('src_tx_id', models.CharField(blank=True, help_text='Source-chain tx id (leg AB group txid on ALG / redeem tx on BSC); also the Allbridge tracking key', max_length=88)),
                ('dest_tx_hash', models.CharField(blank=True, help_text='Final-leg tx (vault mint on BSC / auto-swap on ALG)', max_length=88)),
                ('status', models.CharField(choices=[('CREATED', 'Created (quote accepted, nothing signed)'), ('SRC_COMMITTED', 'Source leg committed - bridge in flight'), ('STUCK', 'Bridge exceeded timeout - ops attention'), ('DEST_ARRIVED', 'Funds at user destination address'), ('COMPLETED', 'Final leg committed'), ('ABANDONED', 'Never signed - expired')], default='CREATED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('src_committed_at', models.DateTimeField(blank=True, null=True)),
                ('dest_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('actor_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cusd_plus_conversions', to='users.business')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cusd_plus_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cusd_plus_conversions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_user', 'status'], name='cpc_user_status_idx'), models.Index(fields=['status', 'updated_at'], name='cpc_status_updated_idx')],
            },
        ),
    ]
