# Generated by Django 5.2 on 2026-07-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusd_plus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusdplusconversion',
            name='bridge_arrival_tx',
            field=models.CharField(blank=True, help_text='On-chain arrival tx at the user destination (chain-observed, not vendor-reported)', max_length=88),
        ),
        migrations.AddField(
            model_name='cusdplusconversion',
            name='dest_scan_from_block',
            field=models.BigIntegerField(blank=True, help_text='Destination-chain scan cursor set when monitoring starts', null=True),
        ),
    ]
