# Generated by Django 5.2 on 2026-07-22 03:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusd_plus', '0003_cusdplusconversion_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BnbAutoConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_wei', models.CharField(max_length=32)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bnb_auto_converts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cusd_plus_bnb_auto_converts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='cpbac_user_created_idx'), models.Index(fields=['tx_hash'], name='cpbac_tx_hash_idx')],
            },
        ),
    ]
