# Generated by Django 5.2 on 2026-07-30 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusd_plus', '0004_bnbautoconvert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bsc_address', models.CharField(max_length=42)),
                ('kind', models.CharField(max_length=16)),
                ('num_calls', models.PositiveSmallIntegerField()),
                ('calls_json', models.TextField()),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('gas_limit', models.PositiveIntegerField()),
                ('max_fee_wei', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('sent', 'Broadcast, receipt pending'), ('confirmed', 'Mined and executed'), ('reverted', 'Mined but reverted'), ('noop_failed', 'Mined, but delegation did not apply (no-op)')], default='sent', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cusd_plus_sponsored_batches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='cpsb_user_created_idx'), models.Index(fields=['tx_hash'], name='cpsb_tx_hash_idx'), models.Index(fields=['status'], name='cpsb_status_idx')],
            },
        ),
    ]
