# Generated by Django 5.2 on 2026-07-31 01:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusd_plus', '0005_sponsoredbatch'),
        ('users', '0028_alter_unifiedtransactiontable_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoredbatch',
            name='kind',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='CusdPlusMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('deposit', 'Deposit into savings'), ('withdraw', 'Withdrawal from savings'), ('send', 'Sent to someone'), ('receive', 'Received'), ('payment', 'Paid a business'), ('payroll', 'Payroll'), ('buy', 'Stock buy'), ('sell', 'Stock sell'), ('yield', 'Yield summary')], max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cusd_plus_movements', to='users.account')),
            ],
            options={
                'db_table': 'cusd_plus_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='cpmov_acct_created_idx')],
            },
        ),
    ]
