# Generated by Django 5.2 on 2026-07-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusd_plus', '0006_alter_sponsoredbatch_kind_cusdplusmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusdplusconversion',
            name='direction',
            field=models.CharField(choices=[('to_savings', 'USDT -> cUSD+ (Ahorrar)'), ('from_savings', 'cUSD+ -> USDT (Retirar)')], max_length=15),
        ),
    ]
