# Generated by Django 5.2 on 2026-07-31 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusd_plus', '0007_alter_cusdplusconversion_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredbatch',
            name='block_hash',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name='sponsoredbatch',
            name='block_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsoredbatch',
            name='delegate_nonce',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsoredbatch',
            name='source_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsoredbatch',
            name='status',
            field=models.CharField(choices=[('signed', 'Signed, broadcast unconfirmed'), ('sent', 'Broadcast, receipt pending'), ('confirmed', 'Mined, executed and final'), ('reverted', 'Mined but reverted'), ('noop_failed', 'Mined, but delegation did not apply (no-op)'), ('reorged', 'Was mined then orphaned by a reorg')], default='sent', max_length=16),
        ),
        migrations.AddIndex(
            model_name='sponsoredbatch',
            index=models.Index(fields=['kind', 'source_id'], name='cpsb_kind_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='sponsoredbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('tx_hash__gt', '')), fields=('tx_hash',), name='cpsb_unique_tx_hash'),
        ),
    ]
