# Generated by Django 5.2 on 2026-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusd_plus', '0008_sponsoredbatch_block_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoredbatch',
            name='status',
            field=models.CharField(choices=[('signed', 'Signed, broadcast unconfirmed'), ('sent', 'Broadcast, receipt pending'), ('confirmed', 'Mined, executed and final'), ('reverted', 'Mined but reverted'), ('noop_failed', 'Mined, but delegation did not apply (no-op)'), ('reorged', 'Was mined then orphaned by a reorg'), ('dropped', 'Signed but never reached the chain')], default='sent', max_length=16),
        ),
    ]
