# Generated by Django 5.2 on 2026-08-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusd_plus', '0009_alter_sponsoredbatch_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CusdPlusMovement',
        ),
    ]
