# Generated by Django 5.2 on 2026-08-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusd_plus', '0011_merge_conversions_into_conversion'),
        # The unified FK referencing this model must be gone first.
        ('users', '0030_remove_unifiedtransactiontable_cusd_plus_conversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CusdPlusConversion',
        ),
    ]
