# Generated by Django 5.2 on 2026-09-04 05:46

import billing.ids
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0009_invoice_lifetime_ceiling'),
        ('users', '0042_add_bnb_unified_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('inv'), editable=False, max_length=40, unique=True)),
                ('number', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('payment_pending', 'Payment pending'), ('paid', 'Paid'), ('past_due', 'Past due'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], default='draft', max_length=24)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('subtotal_minor', models.PositiveBigIntegerField()),
                ('amount_paid_minor', models.PositiveBigIntegerField(default=0)),
                ('amount_remaining_minor', models.PositiveBigIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('line_items_snapshot', models.JSONField(default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('api', 'API'), ('dashboard', 'Dashboard'), ('schedule', 'Schedule'), ('import', 'Import')], max_length=16)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='BillingPaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('pi'), editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires payment method'), ('requires_confirmation', 'Requires confirmation'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='requires_payment_method', max_length=32)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('expires_at', models.DateTimeField()),
                ('last_payment_error', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('client_secret_hash', models.CharField(blank=True, max_length=128)),
                ('billing_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='billing.billinginvoice')),
                ('legacy_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_payment_intent', to='payments.invoice')),
                ('payer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payment_intents', to='users.account')),
                ('payer_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payment_intents_as_payer', to='users.business')),
                ('payer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('pay'), editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='processing', max_length=16)),
                ('commercial_amount_minor', models.PositiveBigIntegerField()),
                ('commercial_currency', models.CharField(default='PEN', max_length=3)),
                ('settlement_asset', models.CharField(max_length=16)),
                ('settlement_decimals', models.PositiveSmallIntegerField()),
                ('gross_units', models.DecimalField(decimal_places=0, max_digits=78)),
                ('fee_units', models.DecimalField(decimal_places=0, max_digits=78)),
                ('receiver_net_units', models.DecimalField(decimal_places=0, max_digits=78)),
                ('chain', models.CharField(default='BSC', max_length=16)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_snapshot', models.JSONField(default=dict)),
                ('billing_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.billinginvoice')),
                ('legacy_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_payment', to='payments.paymenttransaction')),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.billingpaymentintent')),
            ],
        ),
        migrations.CreateModel(
            name='ObligationSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('subj'), editable=False, max_length=40, unique=True)),
                ('external_id', models.CharField(max_length=255)),
                ('subject_type', models.CharField(choices=[('person', 'Person'), ('business', 'Business'), ('membership', 'Membership'), ('other', 'Other')], default='person', max_length=20)),
                ('display_label', models.CharField(blank=True, max_length=160)),
                ('masked_reference', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('blocked', 'Blocked')], default='active', max_length=16)),
                ('locale', models.CharField(default='es-PE', max_length=16)),
                ('timezone', models.CharField(default='America/Lima', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_subjects', to='users.business')),
                ('confio_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('obl'), editable=False, max_length=40, unique=True)),
                ('external_reference', models.CharField(max_length=255)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('original_amount_minor', models.PositiveBigIntegerField()),
                ('amount_paid_minor', models.PositiveBigIntegerField(default=0)),
                ('amount_remaining_minor', models.PositiveBigIntegerField()),
                ('line_items_snapshot', models.JSONField(default=list)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('issued_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('held', 'Held'), ('disputed', 'Disputed'), ('payment_pending', 'Payment pending'), ('paid', 'Paid'), ('past_due', 'Past due'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], default='draft', max_length=24)),
                ('source_version', models.CharField(blank=True, max_length=80)),
                ('allocation_policy', models.CharField(default='oldest_first', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_obligations', to='users.business')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='billing.obligationsubject')),
            ],
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='billing.obligationsubject'),
        ),
        migrations.CreateModel(
            name='PaymentAllocationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_delta_minor', models.BigIntegerField()),
                ('allocation_order', models.PositiveIntegerField()),
                ('allocation_revision', models.PositiveIntegerField(default=1)),
                ('quote_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_entries', to='billing.billingobligation')),
            ],
            options={
                'ordering': ('allocation_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InstitutionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('app'), editable=False, max_length=40, unique=True)),
                ('opaque_subject_reference', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('payment_confirmed', 'Payment confirmed'), ('application_pending', 'Application pending'), ('acknowledged', 'Acknowledged'), ('rejected', 'Rejected'), ('mismatch', 'Mismatch'), ('manual_review', 'Manual review')], default='payment_confirmed', max_length=24)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('acknowledgement_reference', models.CharField(blank=True, max_length=255)),
                ('returned_status', models.CharField(blank=True, max_length=80)),
                ('returned_version', models.CharField(blank=True, max_length=80)),
                ('payment_confirmed_at', models.DateTimeField()),
                ('institution_applied_at', models.DateTimeField(blank=True, null=True)),
                ('billing_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_applications', to='billing.billingpayment')),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='institution_application', to='billing.paymentallocationentry')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('eff'), editable=False, max_length=40, unique=True)),
                ('semantic_key', models.CharField(max_length=255)),
                ('effect_type', models.CharField(choices=[('payment', 'Payment'), ('reversal', 'Reversal'), ('reallocation', 'Reallocation'), ('refund', 'Refund')], max_length=16)),
                ('commercial_currency', models.CharField(max_length=3)),
                ('commercial_delta_minor', models.BigIntegerField()),
                ('provenance', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='effects', to='billing.billingpayment')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_payment_effects', to='users.business')),
                ('parent_effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensating_effects', to='billing.paymenteffect')),
            ],
        ),
        migrations.AddField(
            model_name='paymentallocationentry',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.paymenteffect'),
        ),
        migrations.CreateModel(
            name='SettlementLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('set'), editable=False, max_length=40, unique=True)),
                ('chain_id', models.PositiveBigIntegerField()),
                ('contract_version', models.CharField(max_length=32)),
                ('receiver_address', models.CharField(max_length=66)),
                ('input_token_address', models.CharField(max_length=66)),
                ('input_token_symbol', models.CharField(max_length=16)),
                ('input_token_decimals', models.PositiveSmallIntegerField()),
                ('gross_units', models.DecimalField(decimal_places=0, max_digits=78)),
                ('fee_token_address', models.CharField(max_length=66)),
                ('fee_units', models.DecimalField(decimal_places=0, max_digits=78)),
                ('output_token_address', models.CharField(max_length=66)),
                ('receiver_net_units', models.DecimalField(decimal_places=0, max_digits=78)),
                ('transaction_hash', models.CharField(max_length=66)),
                ('block_number', models.PositiveBigIntegerField()),
                ('block_hash', models.CharField(max_length=66)),
                ('transaction_index', models.PositiveIntegerField()),
                ('log_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_legs', to='billing.billingpayment')),
            ],
        ),
        migrations.CreateModel(
            name='BillingInvoiceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_amount_minor', models.PositiveBigIntegerField()),
                ('allocation_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_links', to='billing.billinginvoice')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_links', to='billing.billingobligation')),
            ],
            options={
                'ordering': ('allocation_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('invoice', 'obligation'), name='billing_invoice_obligation_uniq'), models.UniqueConstraint(fields=('invoice', 'allocation_order'), name='billing_invoice_allocation_order_uniq'), models.CheckConstraint(condition=models.Q(('selected_amount_minor__gt', 0)), name='billing_invoice_selected_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='billingpaymentintent',
            index=models.Index(fields=['billing_invoice', 'status', 'id'], name='bill_pi_invoice_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingpaymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('requires_payment_method', 'requires_confirmation', 'processing'))), fields=('billing_invoice',), name='billing_one_active_intent_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='billingpaymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('billing_invoice', 'idempotency_key'), name='billing_intent_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billingpaymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='billing_intent_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='billingpayment',
            index=models.Index(fields=['billing_invoice', 'status', 'id'], name='bill_pay_invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='billingpayment',
            index=models.Index(fields=['transaction_hash'], name='bill_pay_tx_hash_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingpayment',
            constraint=models.CheckConstraint(condition=models.Q(('commercial_amount_minor__gt', 0)), name='billing_payment_commercial_positive'),
        ),
        migrations.AddConstraint(
            model_name='billingpayment',
            constraint=models.CheckConstraint(condition=models.Q(('gross_units__gt', 0)), name='billing_payment_gross_positive'),
        ),
        migrations.AddConstraint(
            model_name='billingpayment',
            constraint=models.CheckConstraint(condition=models.Q(('fee_units__gte', 0), ('receiver_net_units__gte', 0)), name='billing_payment_parts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='billingpayment',
            constraint=models.CheckConstraint(condition=models.Q(('gross_units', django.db.models.expressions.CombinedExpression(models.F('fee_units'), '+', models.F('receiver_net_units')))), name='billing_payment_settlement_balances'),
        ),
        migrations.AddIndex(
            model_name='obligationsubject',
            index=models.Index(fields=['business', 'status', 'id'], name='bill_subj_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='obligationsubject',
            constraint=models.UniqueConstraint(fields=('business', 'external_id'), name='billing_subject_business_external_uniq'),
        ),
        migrations.AddIndex(
            model_name='billingobligation',
            index=models.Index(fields=['business', 'status', 'due_at', 'id'], name='bill_obl_tenant_due_idx'),
        ),
        migrations.AddIndex(
            model_name='billingobligation',
            index=models.Index(fields=['subject', 'period_start', 'id'], name='bill_obl_subject_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingobligation',
            constraint=models.UniqueConstraint(fields=('business', 'external_reference'), name='billing_obligation_business_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billingobligation',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount_minor__gt', 0)), name='billing_obligation_original_positive'),
        ),
        migrations.AddConstraint(
            model_name='billingobligation',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount_minor', django.db.models.expressions.CombinedExpression(models.F('amount_paid_minor'), '+', models.F('amount_remaining_minor')))), name='billing_obligation_projection_balances'),
        ),
        migrations.AddConstraint(
            model_name='billingobligation',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='billing_obligation_period_order'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['business', 'status', 'due_at', 'id'], name='bill_inv_tenant_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='billinginvoice',
            constraint=models.UniqueConstraint(fields=('business', 'number'), name='billing_invoice_business_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billinginvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_minor__gt', 0)), name='billing_invoice_subtotal_positive'),
        ),
        migrations.AddConstraint(
            model_name='billinginvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_minor', django.db.models.expressions.CombinedExpression(models.F('amount_paid_minor'), '+', models.F('amount_remaining_minor')))), name='billing_invoice_projection_balances'),
        ),
        migrations.AddConstraint(
            model_name='billinginvoice',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='billing_invoice_period_order'),
        ),
        migrations.AddIndex(
            model_name='institutionapplication',
            index=models.Index(fields=['status', 'updated_at', 'id'], name='bill_app_status_age_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenteffect',
            index=models.Index(fields=['business', 'created_at', 'id'], name='bill_effect_tenant_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenteffect',
            constraint=models.UniqueConstraint(fields=('business', 'semantic_key'), name='billing_effect_semantic_uniq'),
        ),
        migrations.AddConstraint(
            model_name='paymenteffect',
            constraint=models.CheckConstraint(condition=models.Q(('commercial_delta_minor', 0), _negated=True), name='billing_effect_delta_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocationentry',
            constraint=models.UniqueConstraint(fields=('effect', 'allocation_order'), name='billing_effect_allocation_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocationentry',
            constraint=models.UniqueConstraint(fields=('effect', 'obligation', 'allocation_revision'), name='billing_effect_obligation_revision_uniq'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocationentry',
            constraint=models.CheckConstraint(condition=models.Q(('commercial_delta_minor', 0), _negated=True), name='billing_allocation_delta_nonzero'),
        ),
        migrations.AddIndex(
            model_name='settlementleg',
            index=models.Index(fields=['billing_payment', 'id'], name='bill_set_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementleg',
            constraint=models.UniqueConstraint(fields=('chain_id', 'transaction_hash', 'log_index'), name='billing_settlement_chain_event_uniq'),
        ),
        migrations.AddConstraint(
            model_name='settlementleg',
            constraint=models.CheckConstraint(condition=models.Q(('gross_units', django.db.models.expressions.CombinedExpression(models.F('fee_units'), '+', models.F('receiver_net_units')))), name='billing_settlement_leg_balances'),
        ),
        migrations.AddConstraint(
            model_name='settlementleg',
            constraint=models.CheckConstraint(condition=models.Q(('fee_units__gte', 0), ('gross_units__gt', 0), ('receiver_net_units__gte', 0)), name='billing_settlement_units_valid'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION billing_prevent_journal_mutation()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    RAISE EXCEPTION 'billing journal rows are append-only'
                        USING ERRCODE = '55000';
                END;
                $$;

                CREATE TRIGGER billing_paymenteffect_append_only
                BEFORE UPDATE OR DELETE ON billing_paymenteffect
                FOR EACH ROW EXECUTE FUNCTION billing_prevent_journal_mutation();

                CREATE TRIGGER billing_allocation_append_only
                BEFORE UPDATE OR DELETE ON billing_paymentallocationentry
                FOR EACH ROW EXECUTE FUNCTION billing_prevent_journal_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS billing_allocation_append_only
                    ON billing_paymentallocationentry;
                DROP TRIGGER IF EXISTS billing_paymenteffect_append_only
                    ON billing_paymenteffect;
                DROP FUNCTION IF EXISTS billing_prevent_journal_mutation();
            """,
        ),
    ]
