# Generated by Django 5.2 on 2026-09-04 05:50

import django.db.models.expressions
import django.db.models.functions.math
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('payments', '0009_invoice_lifetime_ceiling'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='billingpayment',
            constraint=models.CheckConstraint(condition=models.Q(('fee_units', django.db.models.functions.math.Ceil(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross_units'), '*', models.Value(90)), '/', models.Value(10000))))), name='billing_payment_fee_exact'),
        ),
        migrations.AddConstraint(
            model_name='settlementleg',
            constraint=models.CheckConstraint(condition=models.Q(('fee_units', django.db.models.functions.math.Ceil(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross_units'), '*', models.Value(90)), '/', models.Value(10000))))), name='billing_settlement_fee_exact'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER billing_settlement_leg_append_only
                BEFORE UPDATE OR DELETE ON billing_settlementleg
                FOR EACH ROW EXECUTE FUNCTION billing_prevent_journal_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS billing_settlement_leg_append_only
                    ON billing_settlementleg;
            """,
        ),
    ]
