# Generated by Django 5.2 on 2026-09-04 05:55

import billing.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingpayment_billing_payment_fee_exact_and_more'),
        ('users', '0042_add_bnb_unified_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('evt'), editable=False, max_length=40, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('aggregate_type', models.CharField(max_length=40)),
                ('aggregate_id', models.CharField(max_length=40)),
                ('aggregate_version', models.PositiveBigIntegerField()),
                ('transition_key', models.CharField(max_length=255)),
                ('correlation_id', models.CharField(blank=True, max_length=80)),
                ('causation_id', models.CharField(blank=True, max_length=80)),
                ('api_version', models.CharField(default='2026-09-01', max_length=16)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_events', to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='BillingOutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('out'), editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('leased', 'Leased'), ('dispatched', 'Dispatched'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('available_at', models.DateTimeField()),
                ('lease_token', models.CharField(blank=True, max_length=64)),
                ('leased_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_message', to='billing.billingevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='billingevent',
            index=models.Index(fields=['business', 'created_at', 'id'], name='bill_evt_tenant_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingevent',
            constraint=models.UniqueConstraint(fields=('business', 'transition_key'), name='billing_event_transition_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billingevent',
            constraint=models.UniqueConstraint(fields=('business', 'aggregate_type', 'aggregate_id', 'aggregate_version', 'event_type'), name='billing_event_aggregate_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='billingoutboxmessage',
            index=models.Index(fields=['status', 'available_at', 'id'], name='bill_outbox_claim_idx'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER billing_event_append_only
                BEFORE UPDATE OR DELETE ON billing_billingevent
                FOR EACH ROW EXECUTE FUNCTION billing_prevent_journal_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS billing_event_append_only
                    ON billing_billingevent;
            """,
        ),
    ]
