# Generated by Django 5.2 on 2026-09-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingevent_billingoutboxmessage_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='settlementleg',
            name='billing_settlement_units_valid',
        ),
        migrations.AddField(
            model_name='settlementleg',
            name='contract_address',
            field=models.CharField(default='', max_length=66),
        ),
        migrations.AddField(
            model_name='settlementleg',
            name='invoice_id_bytes32',
            field=models.CharField(default='', max_length=66),
        ),
        migrations.AddField(
            model_name='settlementleg',
            name='output_token_decimals',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='settlementleg',
            name='output_token_symbol',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='settlementleg',
            name='output_units',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AddField(
            model_name='settlementleg',
            name='payer_address',
            field=models.CharField(default='', max_length=66),
        ),
        migrations.AddField(
            model_name='settlementleg',
            name='routed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='settlementleg',
            constraint=models.CheckConstraint(condition=models.Q(('fee_units__gte', 0), ('gross_units__gt', 0), ('output_units__gt', 0), ('receiver_net_units__gte', 0)), name='billing_settlement_units_valid'),
        ),
    ]
