# Generated by Django 5.2 on 2026-09-04 11:12

import billing.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_settlementleg_billing_settlement_units_valid_and_more'),
        ('users', '0042_add_bnb_unified_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligationsubject',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BusinessApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('key'), editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=8)),
                ('prefix', models.CharField(max_length=32, unique=True)),
                ('secret_hmac', models.CharField(max_length=64)),
                ('scopes', models.JSONField(default=list)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_api_keys', to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], max_length=8)),
                ('key', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=8)),
                ('route', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=16)),
                ('lease_expires_at', models.DateTimeField()),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_records', to='billing.businessapikey')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_idempotency_records', to='users.business')),
            ],
        ),
        migrations.AddIndex(
            model_name='businessapikey',
            index=models.Index(fields=['business', 'mode', 'revoked_at', 'id'], name='bill_key_tenant_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['status', 'lease_expires_at', 'id'], name='bill_idem_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['expires_at', 'id'], name='bill_idem_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('api_key', 'mode', 'method', 'route', 'key'), name='billing_idempotency_namespace_uniq'),
        ),
    ]
