# Generated by Django 5.2 on 2026-09-04 11:21

import billing.ids
import django.db.models.deletion
import django.utils.timezone
import users.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_obligationsubject_version_businessapikey_and_more'),
        ('users', '0042_add_bnb_unified_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionapplication',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='institutionapplication',
            name='lease_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='institutionapplication',
            name='leased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionapplication',
            name='payload_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='InstitutionConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('icn'), editable=False, max_length=40, unique=True)),
                ('provider', models.SlugField(max_length=64)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], max_length=8)),
                ('verification_url', models.URLField(blank=True, max_length=500)),
                ('application_url', models.URLField(blank=True, max_length=500)),
                ('bearer_token', users.fields.EncryptedCharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('sandbox', 'Sandbox'), ('active', 'Active'), ('disabled', 'Disabled')], default='sandbox', max_length=16)),
                ('live_approved', models.BooleanField(default=False)),
                ('settlement_authority', models.CharField(blank=True, max_length=80)),
                ('refund_authority', models.CharField(blank=True, max_length=80)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_institution_connections', to='users.business')),
            ],
        ),
        migrations.AddField(
            model_name='institutionapplication',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='billing.institutionconnection'),
        ),
        migrations.CreateModel(
            name='InstitutionDataGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('igr'), editable=False, max_length=40, unique=True)),
                ('field_names', models.JSONField(default=list)),
                ('purpose_snapshot', models.JSONField(default=dict)),
                ('consent_version', models.CharField(max_length=40)),
                ('granted_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_grants', to='billing.institutionconnection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_data_grants', to='billing.obligationsubject')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionDataRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=40)),
                ('purpose', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_requirements', to='billing.institutionconnection')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectIdentityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=40)),
                ('encrypted_value', users.fields.EncryptedCharField(max_length=1024)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='user', max_length=80)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_values', to='billing.obligationsubject')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('wep'), editable=False, max_length=40, unique=True)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], max_length=8)),
                ('url', models.URLField(max_length=500)),
                ('secret', users.fields.EncryptedCharField(max_length=512)),
                ('event_types', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_webhook_endpoints', to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('wdl'), editable=False, max_length=40, unique=True)),
                ('replay_number', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('leased', 'Leased'), ('delivered', 'Delivered'), ('retrying', 'Retrying'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('signing_secret', users.fields.EncryptedCharField(max_length=512)),
                ('event_body', models.JSONField()),
                ('available_at', models.DateTimeField()),
                ('leased_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_deliveries', to='billing.billingevent')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='billing.webhookendpoint')),
            ],
        ),
        migrations.AddConstraint(
            model_name='institutionconnection',
            constraint=models.UniqueConstraint(fields=('business', 'provider', 'mode'), name='billing_institution_connection_uniq'),
        ),
        migrations.AddIndex(
            model_name='institutiondatagrant',
            index=models.Index(fields=['connection', 'subject', 'revoked_at', 'id'], name='bill_igr_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='institutiondatarequirement',
            constraint=models.UniqueConstraint(fields=('connection', 'field_name'), name='billing_institution_requirement_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subjectidentityvalue',
            constraint=models.UniqueConstraint(fields=('subject', 'field_name'), name='billing_subject_identity_field_uniq'),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['business', 'mode', 'status', 'id'], name='bill_wep_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'available_at', 'id'], name='bill_wdl_claim_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'endpoint', 'replay_number'), name='billing_webhook_delivery_replay_uniq'),
        ),
    ]
