# Generated by Django 5.2 on 2026-09-04 11:27

import billing.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_institutionapplication_available_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionIdentitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('ise'), editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('requested_fields', models.JSONField(default=list)),
                ('obligation_references', models.JSONField(default=list)),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('token_used_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_sessions', to='billing.institutionconnection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_sessions', to='billing.obligationsubject')),
            ],
            options={
                'indexes': [models.Index(fields=['connection', 'status', 'expires_at', 'id'], name='bill_ise_status_exp_idx')],
            },
        ),
    ]
