# Generated by Django 5.2 on 2026-09-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_institutionidentitysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingevent',
            name='mode',
            field=models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='live', max_length=8),
        ),
    ]
