# Generated by Django 5.2 on 2026-09-04 11:33

import billing.ids
import billing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billingevent_mode'),
        ('users', '0042_add_bnb_unified_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingobligation',
            name='period_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='BillingImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('imp'), editable=False, max_length=40, unique=True)),
                ('schema_version', models.CharField(max_length=32)),
                ('source_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('validating', 'Validating'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('promoting', 'Promoting'), ('completed', 'Completed')], default='staged', max_length=16)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('promoted_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_import_batches', to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='BillingImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('promoted', 'Promoted')], default='staged', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='billing.billingimportbatch')),
                ('promoted_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='billing.billingobligation')),
                ('promoted_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='billing.obligationsubject')),
            ],
        ),
        migrations.CreateModel(
            name='BillingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset_days', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('emitted', 'Emitted'), ('suppressed', 'Suppressed')], default='pending', max_length=16)),
                ('scheduled_for', models.DateTimeField()),
                ('emitted_at', models.DateTimeField(blank=True, null=True)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='billing.billingobligation')),
            ],
        ),
        migrations.CreateModel(
            name='BillingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('sch'), editable=False, max_length=40, unique=True)),
                ('external_reference', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='active', max_length=16)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('presentation_mode', models.CharField(choices=[('payer_amount', 'Payer amount'), ('receiver_net_target', 'Receiver net target')], default='payer_amount', max_length=24)),
                ('interval_months', models.PositiveSmallIntegerField(default=1)),
                ('anchor_day', models.PositiveSmallIntegerField(default=1)),
                ('days_until_due', models.PositiveSmallIntegerField(default=10)),
                ('next_period_start', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_periods', models.PositiveIntegerField(blank=True, null=True)),
                ('generated_periods', models.PositiveIntegerField(default=0)),
                ('timezone', models.CharField(default='America/Lima', max_length=64)),
                ('reminder_offsets_days', models.JSONField(default=billing.models.default_reminder_offsets)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_schedules', to='users.business')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_schedules', to='billing.obligationsubject')),
            ],
        ),
        migrations.AddField(
            model_name='billingobligation',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='billing.billingschedule'),
        ),
        migrations.AddConstraint(
            model_name='billingobligation',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('schedule', 'period_key'), name='billing_obligation_schedule_period_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billingimportbatch',
            constraint=models.UniqueConstraint(fields=('business', 'source_sha256'), name='billing_import_source_uniq'),
        ),
        migrations.AddIndex(
            model_name='billingimportrow',
            index=models.Index(fields=['batch', 'status', 'row_number'], name='bill_imp_row_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='billing_import_row_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='billingreminder',
            index=models.Index(fields=['status', 'scheduled_for', 'id'], name='bill_reminder_claim_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingreminder',
            constraint=models.UniqueConstraint(fields=('obligation', 'offset_days'), name='billing_reminder_obligation_offset_uniq'),
        ),
        migrations.AddIndex(
            model_name='billingschedule',
            index=models.Index(fields=['status', 'next_period_start', 'id'], name='bill_sch_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingschedule',
            constraint=models.UniqueConstraint(fields=('business', 'external_reference'), name='billing_schedule_business_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billingschedule',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='billing_schedule_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='billingschedule',
            constraint=models.CheckConstraint(condition=models.Q(('anchor_day__gte', 1), ('anchor_day__lte', 28)), name='billing_schedule_anchor_valid'),
        ),
        migrations.AddConstraint(
            model_name='billingschedule',
            constraint=models.CheckConstraint(condition=models.Q(('interval_months__gte', 1)), name='billing_schedule_interval_positive'),
        ),
    ]
