# Generated by Django 5.2 on 2026-09-04 11:42

import billing.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_billingobligation_period_key_billingimportbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='public_id',
            field=models.CharField(default=billing.ids.PrefixedPublicId('wd'), editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='public_id',
            field=models.CharField(default=billing.ids.PrefixedPublicId('we'), editable=False, max_length=40, unique=True),
        ),
    ]
