# Generated by Django 5.2 on 2026-09-04 14:38

import billing.ids
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.math
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_webhookdelivery_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('qt'), editable=False, max_length=40, unique=True)),
                ('commercial_amount_minor', models.PositiveBigIntegerField()),
                ('commercial_currency', models.CharField(default='PEN', max_length=3)),
                ('presentation_mode', models.CharField(choices=[('payer_amount', 'Payer amount'), ('receiver_net_target', 'Receiver net target')], max_length=24)),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('rate_source', models.CharField(max_length=50)),
                ('rate_fetched_at', models.DateTimeField()),
                ('settlement_asset', models.CharField(default='CUSD_PLUS', max_length=16)),
                ('settlement_decimals', models.PositiveSmallIntegerField(default=18)),
                ('gross_units', models.DecimalField(decimal_places=0, max_digits=78)),
                ('fee_units', models.DecimalField(decimal_places=0, max_digits=78)),
                ('receiver_net_units', models.DecimalField(decimal_places=0, max_digits=78)),
                ('display_amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('expires_at', models.DateTimeField()),
                ('payment_intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_quote', to='billing.billingpaymentintent')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('commercial_amount_minor__gt', 0)), name='billing_quote_commercial_positive'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='billing_quote_rate_positive'), models.CheckConstraint(condition=models.Q(('gross_units__gt', 0)), name='billing_quote_gross_positive'), models.CheckConstraint(condition=models.Q(('gross_units', django.db.models.expressions.CombinedExpression(models.F('fee_units'), '+', models.F('receiver_net_units')))), name='billing_quote_settlement_balances'), models.CheckConstraint(condition=models.Q(('fee_units', django.db.models.functions.math.Ceil(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross_units'), '*', models.Value(90)), '/', models.Value(10000))))), name='billing_quote_fee_exact')],
            },
        ),
    ]
