# Generated by Django 5.2 on 2026-09-04 15:00

import billing.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_settlementquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CipSandboxMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('cipsm'), editable=False, max_length=40, unique=True)),
                ('member_number', models.CharField(max_length=80)),
                ('habilidad', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=16)),
                ('paid_through', models.DateField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cip_sandbox_members', to='billing.institutionconnection')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cip_sandbox_member', to='billing.obligationsubject')),
            ],
        ),
        migrations.CreateModel(
            name='CipSandboxApplicationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=billing.ids.PrefixedPublicId('cipsr'), editable=False, max_length=40, unique=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_sha256', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('mismatch', 'Mismatch'), ('rejected', 'Rejected')], max_length=24)),
                ('response_snapshot', models.JSONField(default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cip_sandbox_receipts', to='billing.institutionconnection')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_receipts', to='billing.cipsandboxmember')),
            ],
        ),
        migrations.AddIndex(
            model_name='cipsandboxmember',
            index=models.Index(fields=['connection', 'habilidad', 'id'], name='bill_cipsm_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='cipsandboxmember',
            constraint=models.UniqueConstraint(fields=('connection', 'member_number'), name='billing_cip_sandbox_member_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cipsandboxapplicationreceipt',
            constraint=models.UniqueConstraint(fields=('connection', 'idempotency_key'), name='billing_cip_sandbox_receipt_idem_uniq'),
        ),
    ]
