# Generated by Django 5.2 on 2026-09-05 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_cipsandboxmember_cipsandboxapplicationreceipt_and_more'),
        ('users', '0042_add_bnb_unified_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billingimportbatch',
            name='billing_import_source_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='billingobligation',
            name='billing_obligation_business_external_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='billingschedule',
            name='billing_schedule_business_external_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='obligationsubject',
            name='billing_subject_business_external_uniq',
        ),
        migrations.AddField(
            model_name='billingimportbatch',
            name='mode',
            field=models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='live', max_length=8),
        ),
        migrations.AddField(
            model_name='billingobligation',
            name='mode',
            field=models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='live', max_length=8),
        ),
        migrations.AddField(
            model_name='billingschedule',
            name='mode',
            field=models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='live', max_length=8),
        ),
        migrations.AddField(
            model_name='obligationsubject',
            name='mode',
            field=models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='live', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='billingimportbatch',
            constraint=models.UniqueConstraint(fields=('business', 'mode', 'source_sha256'), name='billing_import_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billingobligation',
            constraint=models.UniqueConstraint(fields=('business', 'mode', 'external_reference'), name='billing_obligation_business_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billingschedule',
            constraint=models.UniqueConstraint(fields=('business', 'mode', 'external_reference'), name='billing_schedule_business_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='obligationsubject',
            constraint=models.UniqueConstraint(fields=('business', 'mode', 'external_id'), name='billing_subject_business_external_uniq'),
        ),
    ]
