# Generated by Django 5.2 on 2026-09-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_remove_billingimportbatch_billing_import_source_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionconnection',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
