name = "confio-graphql"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Routes for GraphQL endpoint
routes = [
  { pattern = "confio.lat/graphql*", zone_id = "1fae8d4a5dbd820442e673422099f4ec" },
  { pattern = "www.confio.lat/graphql*", zone_id = "1fae8d4a5dbd820442e673422099f4ec" }
]

[env.production]
vars = { ENVIRONMENT = "production" }