# Generated by Django 4.2.20 on 2025-07-27 03:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_unifiedtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conversion_type', models.CharField(choices=[('usdc_to_cusd', 'USDC to cUSD'), ('cusd_to_usdc', 'cUSD to USDC')], max_length=20)),
                ('from_amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('to_amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('from_transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('to_transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='users.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='conversions_user_id_619257_idx'), models.Index(fields=['account', 'status'], name='conversions_account_8153f8_idx'), models.Index(fields=['conversion_id'], name='conversions_convers_21da52_idx'), models.Index(fields=['created_at'], name='conversions_created_26e2d3_idx')],
            },
        ),
    ]
