# Generated by Django 5.2 on 2025-09-02 02:45

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], help_text='Type of actor (user or business)', max_length=10)),
                ('actor_display_name', models.CharField(blank=True, help_text='Display name of the actor at conversion time', max_length=255)),
                ('actor_address', models.CharField(blank=True, help_text='Blockchain address of the actor', max_length=66)),
                ('conversion_type', models.CharField(choices=[('usdc_to_cusd', 'USDC to cUSD'), ('cusd_to_usdc', 'cUSD to USDC')], max_length=20)),
                ('from_amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('to_amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('from_transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('to_transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_SIG', 'Pending Signature'), ('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conversions',
                'ordering': ['-created_at'],
            },
        ),
    ]
