# Generated by Django 5.2 on 2025-09-02 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversion', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='actor_business',
            field=models.ForeignKey(blank=True, help_text='Business that initiated the conversion (if business account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_conversions', to='users.business'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='actor_user',
            field=models.ForeignKey(blank=True, help_text='User who initiated the conversion (if personal account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_conversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['actor_user', 'status'], name='conv_actor_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['actor_business', 'status'], name='conv_actor_bus_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['actor_type', 'status'], name='conv_actor_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['conversion_id'], name='conversions_convers_21da52_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['created_at'], name='conversions_created_26e2d3_idx'),
        ),
    ]
