# Generated by Django 5.2 on 2025-12-17 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_initial'),
        ('users', '0013_user_platform_os'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversion',
            name='conversions_convers_21da52_idx',
        ),
        migrations.RenameField(
            model_name='conversion',
            old_name='conversion_id',
            new_name='internal_id',
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['internal_id'], name='conversions_interna_bffeb3_idx'),
        ),
    ]
