# Generated by Django 4.2.20 on 2025-07-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0004_remove_legacy_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversion',
            name='conversions_user_id_619257_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversion',
            name='conversions_account_8153f8_idx',
        ),
    ]
