# Generated by Django 5.2 on 2025-08-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0005_create_unified_transaction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_SIG', 'Pending Signature'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
