# Generated by Django 5.2 on 2026-07-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0005_revert_algo_conversion_types_to_usdc_to_cusd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='conversion_type',
            field=models.CharField(choices=[('usdc_to_cusd', 'USDC to cUSD'), ('cusd_to_usdc', 'cUSD to USDC'), ('usdc_to_algo', 'USDC to ALGO')], max_length=20),
        ),
    ]
