# Generated by Django 5.2 on 2026-08-01 17:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0006_alter_conversion_conversion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='bridge_arrival_tx',
            field=models.CharField(blank=True, help_text='On-chain arrival at the user destination (chain-observed, not vendor-reported)', max_length=88),
        ),
        migrations.AddField(
            model_name='conversion',
            name='dest_arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversion',
            name='dest_scan_from_block',
            field=models.BigIntegerField(blank=True, help_text='Destination-chain scan cursor set when monitoring starts', null=True),
        ),
        migrations.AddField(
            model_name='conversion',
            name='quoted_cost_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Total cost pct the user accepted at quote time', max_digits=8),
        ),
        migrations.AddField(
            model_name='conversion',
            name='source',
            field=models.CharField(choices=[('convert', 'In-app conversion (user-quoted)'), ('external_deposit', 'External USDT-BSC deposit'), ('ramp', 'Ramp (Koywe) delivery')], default='convert', help_text='How the row was born (savings rows; Algorand swaps are always in-app)', max_length=20),
        ),
        migrations.AddField(
            model_name='conversion',
            name='src_committed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversion',
            name='user_bsc_address',
            field=models.CharField(blank=True, help_text="The user's own BSC address (non-custodial; informational). The Algorand side lives in actor_address.", max_length=42),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='conversion_type',
            field=models.CharField(choices=[('usdc_to_cusd', 'USDC to cUSD'), ('cusd_to_usdc', 'cUSD to USDC'), ('usdc_to_algo', 'USDC to ALGO'), ('to_savings', 'USDT -> cUSD+ (Ahorrar)'), ('from_savings', 'cUSD+ -> USDT (Retirar)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='from_transaction_hash',
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_SIG', 'Pending Signature'), ('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CREATED', 'Created (quote accepted, nothing signed)'), ('SRC_COMMITTED', 'Source leg committed - bridge in flight'), ('STUCK', 'Bridge exceeded timeout - ops attention'), ('DEST_ARRIVED', 'Funds at user destination address'), ('ABANDONED', 'Never signed - expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='to_transaction_hash',
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
    ]
