# Generated by Codex on 2025-08-24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0006_alter_conversion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('PENDING_SIG', 'Pending Signature'),
                    ('SUBMITTED', 'Submitted'),
                    ('PROCESSING', 'Processing'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]

