# Generated by Django 5.2 on 2026-08-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0007_conversion_bridge_arrival_tx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_SIG', 'Pending Signature'), ('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CREATED', 'Created (quote accepted, nothing signed)'), ('SRC_COMMITTED', 'Source leg committed - bridge in flight'), ('STUCK', 'Bridge exceeded timeout - ops attention'), ('DEST_ARRIVED', 'Funds at user destination address'), ('ABANDONED', 'Never signed - expired'), ('DELIVERED_USDT', 'Delivered as USDT - holder cannot mint')], default='PENDING', max_length=20),
        ),
    ]
