# Generated by Django 5.2 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0009_alter_conversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='gross_amount_exact',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Authoritative gross amount from the prepared call/contract event.', max_digits=78, null=True),
        ),
        migrations.AddField(
            model_name='conversion',
            name='fee_amount_exact',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Authoritative Confio conversion fee at token precision.', max_digits=78, null=True),
        ),
        migrations.AddField(
            model_name='conversion',
            name='net_amount_exact',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Authoritative net amount after the conversion fee.', max_digits=78, null=True),
        ),
        migrations.AddField(
            model_name='conversion',
            name='conversion_fee_bps',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversion',
            name='from_asset_id',
            field=models.CharField(blank=True, choices=[('CUSD_ALGO', 'cUSD (Algorand)'), ('USDC_ALGO', 'USDC (Algorand)'), ('USDT_BSC', 'USDT (BSC)'), ('CUSD_BSC', 'cUSD (BSC)'), ('CUSD_PLUS_BSC', 'cUSD+ (BSC)')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='conversion',
            name='to_asset_id',
            field=models.CharField(blank=True, choices=[('CUSD_ALGO', 'cUSD (Algorand)'), ('USDC_ALGO', 'USDC (Algorand)'), ('USDT_BSC', 'USDT (BSC)'), ('CUSD_BSC', 'cUSD (BSC)'), ('CUSD_PLUS_BSC', 'cUSD+ (BSC)')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='conversion',
            name='perimeter_direction',
            field=models.CharField(blank=True, choices=[('entry', 'USDT -> Confio dollars'), ('exit', 'Confio dollars -> USDT'), ('internal', 'cUSD <-> cUSD+')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='conversion',
            name='prepared_intent_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conversion',
            name='contract_event_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
