# Generated by Django 5.2 on 2025-09-02 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confiorewardbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confio_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confiorewardtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confio_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='influencerambassador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadoractivity',
            name='ambassador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='achievements.influencerambassador'),
        ),
        migrations.AddField(
            model_name='influencerreferral',
            name='influencer_user',
            field=models.ForeignKey(blank=True, help_text='Actual user who made the referral (if registered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_as_influencer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='influencerreferral',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_as_referred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiktokviralshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiktokviralshare',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tiktok_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='achievements.achievementtype'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiktokviralshare',
            name='achievement',
            field=models.ForeignKey(blank=True, help_text='Achievement being shared (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_shares', to='achievements.userachievement'),
        ),
        migrations.AlterUniqueTogether(
            name='influencerreferral',
            unique_together={('referred_user', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement_type', 'deleted_at')},
        ),
    ]
