# Generated by Django 4.2.20 on 2025-07-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuspiciousActivity',
        ),
    ]
