# Generated by Django 4.2.20 on 2025-07-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_remove_suspicious_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='claim_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address when achievement was earned', null=True),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='device_fingerprint_hash',
            field=models.CharField(blank=True, help_text='Hash of device fingerprint when achievement was earned', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='security_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional security metadata for fraud detection'),
        ),
    ]
