# Generated by Django 4.2.20 on 2025-07-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_add_fraud_prevention_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='confiorewardbalance',
            name='daily_reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total CONFIO claimed today', max_digits=10),
        ),
        migrations.AddField(
            model_name='confiorewardbalance',
            name='daily_reward_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of rewards claimed today'),
        ),
        migrations.AddField(
            model_name='confiorewardbalance',
            name='last_reward_at',
            field=models.DateTimeField(blank=True, help_text='Last time user received a reward', null=True),
        ),
    ]
