# Generated by Django 5.2 on 2025-11-06 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_rename_referrals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementtype',
            options={'ordering': ['category', 'display_order', 'name'], 'verbose_name': 'Reward Program (Deprecated)', 'verbose_name_plural': 'Reward Programs (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='ambassadoractivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Referral Ambassador Activity (Deprecated)', 'verbose_name_plural': 'Referral Ambassador Activities (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='confiorewardbalance',
            options={'verbose_name': 'Reward Wallet (Deprecated)', 'verbose_name_plural': 'Reward Wallets (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='confiorewardtransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reward Ledger Entry (Deprecated)', 'verbose_name_plural': 'Reward Ledger Entries (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='influencerambassador',
            options={'ordering': ['-confio_earned', '-total_referrals'], 'verbose_name': 'Referral Ambassador (Deprecated)', 'verbose_name_plural': 'Referral Ambassadors (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='tiktokviralshare',
            options={'ordering': ['-created_at'], 'verbose_name': 'Social Referral Share (Deprecated)', 'verbose_name_plural': 'Social Referral Shares (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-earned_at', '-created_at'], 'verbose_name': 'User Reward (Deprecated)', 'verbose_name_plural': 'User Rewards (Deprecated)'},
        ),
        migrations.CreateModel(
            name='ReferralWithdrawalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of referral-earned CONFIO withdrawn', max_digits=10)),
                ('reference_type', models.CharField(default='send_transaction', help_text='Source of the withdrawal record, e.g., send_transaction', max_length=50)),
                ('reference_id', models.CharField(blank=True, help_text='Identifier for the source record (transaction hash, send ID, etc.)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for manual review')),
                ('requires_review', models.BooleanField(default=False, help_text='Whether this withdrawal requires manual compliance review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_withdrawal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Withdrawal Log',
                'verbose_name_plural': 'Referral Withdrawal Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='achievement_user_id_5a8d41_idx'), models.Index(fields=['reference_type', 'reference_id'], name='achievement_referen_c20110_idx')],
            },
        ),
    ]
