# Generated by Django 5.2 on 2025-11-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_achievementtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreferral',
            name='reward_box_name',
            field=models.CharField(blank=True, help_text='Nombre de box utilizado en la bóveda de recompensas', max_length=128),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='reward_error',
            field=models.TextField(blank=True, help_text='Último error registrado al intentar marcar elegibilidad'),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='reward_event',
            field=models.CharField(blank=True, help_text='Evento que activó la recompensa (send, payment, p2p_trade, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='reward_last_attempt_at',
            field=models.DateTimeField(blank=True, help_text='Último intento de sincronizar con la bóveda de recompensas', null=True),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='reward_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales (ej. parámetros Algorand)'),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='reward_referee_confio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CONFIO asignado al referido (en unidades token)', max_digits=12),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='reward_referrer_confio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CONFIO asignado al referidor (en unidades token)', max_digits=12),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='reward_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('eligible', 'Elegible'), ('failed', 'Fallido')], default='pending', help_text='Estado de elegibilidad en la bóveda on-chain', max_length=20),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='reward_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se registró exitosamente la elegibilidad on-chain', null=True),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='reward_tx_id',
            field=models.CharField(blank=True, help_text='ID de transacción Algorand que marcó la elegibilidad', max_length=128),
        ),
    ]
