# Generated by Django 5.2 on 2025-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_referral_pending_placeholders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralrewardevent',
            name='reward_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('eligible', 'Elegible'), ('failed', 'Fallido'), ('skipped', 'Omitido'), ('claimed', 'Reclamado')], default='pending', max_length=20),
        ),
    ]
