# Generated by Django 5.2 on 2025-11-24 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0011_update_userreferral_reward_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='referralrewardevent',
            name='unique_first_reward_event_per_trigger',
        ),
        migrations.AddConstraint(
            model_name='referralrewardevent',
            constraint=models.UniqueConstraint(fields=('user', 'trigger', 'referral'), name='unique_reward_event_per_trigger_and_referral'),
        ),
    ]
