# Generated by Django 5.2 on 2025-12-17 14:54

import achievements.models
from django.db import migrations, models
import uuid

def populate_uuids(apps, schema_editor):
    ConfioRewardTransaction = apps.get_model('achievements', 'ConfioRewardTransaction')
    for row in ConfioRewardTransaction.objects.all():
        row.internal_id = uuid.uuid4().hex
        row.save(update_fields=['internal_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0012_fix_referral_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='confiorewardtransaction',
            name='internal_id',
            field=models.CharField(default=None, editable=False, max_length=32, null=True),
        ),
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='confiorewardtransaction',
            name='internal_id',
            field=models.CharField(default=achievements.models.generate_reward_transaction_id, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
