# Generated by Django 5.2 on 2025-12-17 15:08

import achievements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0013_confiorewardtransaction_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrewardevent',
            name='internal_id',
            field=models.CharField(default=achievements.models.generate_referral_event_id, editable=False, max_length=32, null=True),
        ),
    ]
