# Generated by Django 5.2 on 2026-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0015_alter_referralrewardevent_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreferral',
            name='cohort',
            field=models.CharField(blank=True, db_index=True, help_text="Canonical referral cohort for F5 queries. Values map to the three-cohort taxonomy: 'creator_julianmoonluna' (T1), 'user_driven' (T3), 'send_invite' (T4), 'organic' (T5), or '' if unclassified. Populated from attribution_data on save.", max_length=32),
        ),
    ]
