# Generated by Django 5.2 on 2026-08-02 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0017_backfill_userreferral_cohort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='confiorewardtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('reference_type', 'referral_claim')), fields=('reference_type', 'reference_id'), name='uniq_referral_claim_reference'),
        ),
    ]
