# Generated by Django 5.2 on 2026-08-02 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0018_uniq_referral_claim_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referralwithdrawallog',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('reference_type', 'reference_id'), name='uniq_referral_withdrawal_reference'),
        ),
        migrations.AddConstraint(
            model_name='userreferral',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('referred_user',), name='uniq_live_referral_per_referee'),
        ),
    ]
