# Generated by Django 4.2.20 on 2025-07-30 01:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresalePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_token', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_purchase', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_purchase', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_per_user', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total purchase per user for this phase', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='upcoming', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['phase_number'],
            },
        ),
        migrations.CreateModel(
            name='PresaleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_raised', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_participants', models.IntegerField(default=0)),
                ('total_tokens_sold', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('average_purchase', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='presale.presalephase')),
            ],
            options={
                'verbose_name_plural': 'Presale stats',
            },
        ),
        migrations.CreateModel(
            name='UserPresaleLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_purchased', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('last_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presale.presalephase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='PresalePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusd_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('confio_amount', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('price_per_token', models.DecimalField(decimal_places=4, help_text='Price at time of purchase', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=256, null=True)),
                ('from_address', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='presale.presalephase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presale_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'phase'], name='presale_pre_user_id_23f826_idx'), models.Index(fields=['status'], name='presale_pre_status_6d9129_idx'), models.Index(fields=['-created_at'], name='presale_pre_created_2cd88b_idx')],
            },
        ),
    ]
