# Generated by Django 4.2.20 on 2025-07-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presalephase',
            name='location_emoji',
            field=models.CharField(default='🌎', help_text='Emoji and location text', max_length=50),
        ),
        migrations.AddField(
            model_name='presalephase',
            name='target_audience',
            field=models.CharField(default='Comunidad', help_text='Target audience for this phase', max_length=100),
        ),
        migrations.AddField(
            model_name='presalephase',
            name='vision_points',
            field=models.JSONField(default=list, help_text='List of vision points for this phase'),
        ),
    ]
