# Generated by Django 5.2 on 2025-09-02 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presalepurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presale_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presalestats',
            name='phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='presale.presalephase'),
        ),
        migrations.AddField(
            model_name='userpresalelimit',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presale.presalephase'),
        ),
        migrations.AddField(
            model_name='userpresalelimit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='presalepurchase',
            index=models.Index(fields=['user', 'phase'], name='presale_pre_user_id_23f826_idx'),
        ),
        migrations.AddIndex(
            model_name='presalepurchase',
            index=models.Index(fields=['status'], name='presale_pre_status_6d9129_idx'),
        ),
        migrations.AddIndex(
            model_name='presalepurchase',
            index=models.Index(fields=['-created_at'], name='presale_pre_created_2cd88b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpresalelimit',
            unique_together={('user', 'phase')},
        ),
    ]
