# Generated by Django 4.2.20 on 2025-07-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0002_presalephase_location_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presalephase',
            name='status',
            field=models.CharField(choices=[('coming_soon', 'Coming Soon'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='upcoming', max_length=20),
        ),
    ]
