# Generated by Django 5.2 on 2025-11-18 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresaleWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(default=False, help_text='Whether user has been notified about presale availability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presale_waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presale Waitlist Entry',
                'verbose_name_plural': 'Presale Waitlist Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='presale_pre_user_id_66a506_idx'), models.Index(fields=['notified'], name='presale_pre_notifie_5050e5_idx'), models.Index(fields=['-created_at'], name='presale_pre_created_d702d0_idx')],
            },
        ),
    ]
