# Generated by Django 4.2.20 on 2025-07-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0003_add_coming_soon_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresaleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_presale_active', models.BooleanField(default=False, help_text='Master switch to enable/disable all presale features in the app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Presale Settings',
                'verbose_name_plural': 'Presale Settings',
            },
        ),
    ]
