# Generated by Django 5.2 on 2025-12-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0003_presalewaitlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presalestats',
            options={'verbose_name': 'Presale stats (deprecated)', 'verbose_name_plural': 'Presale stats (deprecated)'},
        ),
    ]
