# Generated by Django 5.2 on 2025-12-17 14:54

import presale.models
from django.db import migrations, models
import uuid

def populate_uuids(apps, schema_editor):
    PresalePurchase = apps.get_model('presale', 'PresalePurchase')
    for row in PresalePurchase.objects.all():
        row.internal_id = uuid.uuid4().hex
        row.save(update_fields=['internal_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0004_alter_presalestats_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='presalepurchase',
            name='internal_id',
            field=models.CharField(default=None, editable=False, max_length=32, null=True),
        ),
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='presalepurchase',
            name='internal_id',
            field=models.CharField(default=presale.models.generate_presale_purchase_id, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
