# Generated by Django 5.2 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0005_presalepurchase_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='presalepurchase',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user accepted the presale terms', null=True),
        ),
        migrations.AddField(
            model_name='presalepurchase',
            name='accepted_terms_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP recorded when the user accepted the presale terms', null=True),
        ),
        migrations.AddField(
            model_name='presalepurchase',
            name='accepted_terms_user_agent',
            field=models.TextField(blank=True, help_text='User agent recorded when the user accepted the presale terms'),
        ),
        migrations.AddField(
            model_name='presalepurchase',
            name='accepted_terms_version',
            field=models.CharField(blank=True, help_text='Terms version accepted by the user at purchase time', max_length=32),
        ),
    ]
