# Generated by Django 5.2 on 2026-07-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0007_presalesettings_telegram_group_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='presalepurchase',
            name='attested_not_us_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the 'No vivo en Estados Unidos' self-attestation", null=True),
        ),
        migrations.AddField(
            model_name='presalepurchase',
            name='attested_not_us_resident',
            field=models.BooleanField(default=False, help_text="User checked 'No vivo en Estados Unidos' at purchase time"),
        ),
        migrations.AddField(
            model_name='presalepurchase',
            name='ip_country',
            field=models.CharField(blank=True, help_text='ISO country resolved from the client IP at purchase time', max_length=2),
        ),
    ]
