# Generated by Django 5.2 on 2026-07-30 21:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0008_presalepurchase_attested_not_us_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresaleMigrationCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsc_address', models.CharField(help_text='BSC address the credit is assigned to (snapshot of Account.bsc_address at row creation)', max_length=42)),
                ('confio_amount', models.DecimalField(decimal_places=6, help_text="Total CONFIO from the user's completed Algorand purchases", max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued in Safe batch'), ('credited', 'Credited on-chain'), ('failed', 'Failed verification')], default='pending', max_length=20)),
                ('batch_id', models.CharField(blank=True, help_text='Identifier of the Safe batch this row was queued into', max_length=64)),
                ('safe_tx_hash', models.CharField(blank=True, help_text='Transaction hash of the creditMigrated call that included this row', max_length=66)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='presale_migration_credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presale Migration Credit',
                'verbose_name_plural': 'Presale Migration Credits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='presale_pre_status_f23ab4_idx'), models.Index(fields=['batch_id'], name='presale_pre_batch_i_b975bc_idx')],
            },
        ),
    ]
