# Generated by Django 5.2 on 2026-07-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0009_presalemigrationcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='presalepurchase',
            name='funding_source',
            field=models.CharField(choices=[('algorand_cusd', 'Legacy cUSD (Algorand)'), ('direct_cusd', 'Confío Dollar (USDT-BSC)'), ('cusd_plus_redeem', 'Redeemed from cUSD+')], default='algorand_cusd', help_text='Which balance funded this purchase', max_length=20),
        ),
    ]
