# Generated by Django 4.2.20 on 2025-07-02 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('sender_address', models.CharField(max_length=64)),
                ('recipient_address', models.CharField(max_length=64)),
                ('amount', models.CharField(max_length=32)),
                ('token_type', models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10)),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('transaction_hash', models.CharField(blank=True, help_text='Sui transaction digest (32 bytes, 64 hex characters)', max_length=64, unique=True)),
                ('error_message', models.TextField(blank=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_hash'], name='send_transa_transac_66b202_idx'), models.Index(fields=['sender_user', 'status'], name='send_transa_sender__8f7670_idx'), models.Index(fields=['recipient_user', 'status'], name='send_transa_recipie_a7159a_idx'), models.Index(fields=['sender_address'], name='send_transa_sender__a424fe_idx'), models.Index(fields=['recipient_address'], name='send_transa_recipie_573104_idx'), models.Index(fields=['created_at'], name='send_transa_created_94232c_idx')],
            },
        ),
    ]
