# Generated by Django 5.2 on 2025-09-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('invitation_id', models.CharField(max_length=64, unique=True)),
                ('phone_key', models.CharField(db_index=True, max_length=32)),
                ('phone_country', models.CharField(blank=True, max_length=2)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('token_type', models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10)),
                ('message', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('reclaimed', 'Reclaimed')], default='pending', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_txid', models.CharField(blank=True, max_length=66)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Phone invite',
                'verbose_name_plural': 'Phone invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SendTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('sender_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business'), ('external', 'External')], default='user', help_text='Type of sender (user or business)', max_length=10)),
                ('recipient_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business'), ('external', 'External')], default='user', help_text='Type of recipient (user or business)', max_length=10)),
                ('sender_display_name', models.CharField(blank=True, help_text='Display name for the sender', max_length=255)),
                ('recipient_display_name', models.CharField(blank=True, help_text='Display name for the recipient', max_length=255)),
                ('sender_phone', models.CharField(blank=True, help_text='Sender phone number at transaction time', max_length=30)),
                ('recipient_phone', models.CharField(blank=True, help_text='Recipient phone number at transaction time', max_length=30)),
                ('sender_address', models.CharField(max_length=66)),
                ('recipient_address', models.CharField(max_length=66)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('token_type', models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10)),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('AML_REVIEW', 'Under AML Review')], default='PENDING', max_length=10)),
                ('transaction_hash', models.CharField(blank=True, help_text='Sui transaction digest (0x + 32 bytes, 66 hex characters total)', max_length=66, null=True, unique=True)),
                ('error_message', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Optional key to prevent duplicate transactions', max_length=64, null=True)),
                ('is_invitation', models.BooleanField(default=False, help_text='True if this transaction includes an invitation to join Confío')),
                ('invitation_claimed', models.BooleanField(default=False, help_text='True if the invitation was claimed by the recipient')),
                ('invitation_reverted', models.BooleanField(default=False, help_text='True if the invitation expired and funds were returned to sender')),
                ('invitation_expires_at', models.DateTimeField(blank=True, help_text='When the invitation expires (7 days after creation)', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
