# Generated by Django 4.2.20 on 2025-07-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_add_soft_delete_to_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient_address',
            field=models.CharField(max_length=66),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_address',
            field=models.CharField(max_length=66),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(blank=True, help_text='Sui transaction digest (0x + 32 bytes, 66 hex characters total)', max_length=66, unique=True),
        ),
    ]
