# Generated by Django 5.2 on 2025-09-02 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('send', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneinvite',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_invites_claimed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phoneinvite',
            name='inviter_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='recipient_business',
            field=models.ForeignKey(blank=True, help_text='Business that received the transaction (if received by business)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='users.business'),
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='sender_business',
            field=models.ForeignKey(blank=True, help_text='Business that sent the transaction (if sent by business)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='users.business'),
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='sender_user',
            field=models.ForeignKey(blank=True, help_text='User who sent the transaction (null for external deposits)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phoneinvite',
            name='send_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_invite', to='send.sendtransaction'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['transaction_hash'], name='send_sendtr_transac_ec6151_idx'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['sender_user', 'status'], name='send_sendtr_sender__a83073_idx'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['recipient_user', 'status'], name='send_sendtr_recipie_a91a25_idx'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['sender_business', 'status'], name='send_sendtr_sender__631d62_idx'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['recipient_business', 'status'], name='send_sendtr_recipie_185477_idx'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['sender_address'], name='send_sendtr_sender__040c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['recipient_address'], name='send_sendtr_recipie_a3f268_idx'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['created_at'], name='send_sendtr_created_2422da_idx'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['idempotency_key'], name='send_sendtr_idempot_171c7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='sendtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('idempotency_key__isnull', False)), fields=('sender_user', 'idempotency_key'), name='unique_send_idempotency'),
        ),
        migrations.AddIndex(
            model_name='phoneinvite',
            index=models.Index(fields=['phone_key', 'status'], name='send_phonei_phone_k_52505d_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneinvite',
            index=models.Index(fields=['invitation_id'], name='send_phonei_invitat_d8135e_idx'),
        ),
    ]
