# Generated by Django 4.2.20 on 2025-07-02 18:36

from django.db import migrations

def update_cusd_to_lowercase(apps, schema_editor):
    """Update existing CUSD records to cUSD"""
    Transaction = apps.get_model('send', 'Transaction')
    
    # Update all CUSD transactions to cUSD
    Transaction.objects.filter(token_type='CUSD').update(token_type='cUSD')

def reverse_update_cusd_to_lowercase(apps, schema_editor):
    """Reverse: update cUSD records back to CUSD"""
    Transaction = apps.get_model('send', 'Transaction')
    
    # Update all cUSD transactions back to CUSD
    Transaction.objects.filter(token_type='cUSD').update(token_type='CUSD')

class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_fix_sui_address_length'),
    ]

    operations = [
        migrations.RunPython(update_cusd_to_lowercase, reverse_update_cusd_to_lowercase),
    ]
