# Generated by Django 5.2 on 2025-12-17 12:45

import send.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0003_sendtransaction_internal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtransaction',
            name='internal_id',
            field=models.CharField(default=send.models.generate_send_transaction_id, editable=False, max_length=32, unique=True),
        ),
    ]
