# Generated by Django 4.2.20 on 2025-07-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0003_update_cusd_to_lowercase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token_type',
            field=models.CharField(choices=[('cUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin')], max_length=10),
        ),
    ]
