# Generated by Django 4.2.20 on 2025-07-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0005_rename_transaction_to_sendtransaction'),
        ('users', '0005_account_business_delete_userprofile_account_business_and_more'),
    ]

    operations = [
        # Add new direct User/Business relationship fields
        migrations.AddField(
            model_name='sendtransaction',
            name='sender_business',
            field=models.ForeignKey(
                blank=True,
                help_text='Business that sent the transaction (if sent by business)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sent_transactions',
                to='users.business'
            ),
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='recipient_business',
            field=models.ForeignKey(
                blank=True,
                help_text='Business that received the transaction (if received by business)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='received_transactions',
                to='users.business'
            ),
        ),
        
        # Add computed fields for GraphQL
        migrations.AddField(
            model_name='sendtransaction',
            name='sender_type',
            field=models.CharField(
                choices=[('user', 'Personal'), ('business', 'Business')],
                default='user',
                max_length=10,
                help_text='Type of sender (user or business)'
            ),
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='recipient_type',
            field=models.CharField(
                choices=[('user', 'Personal'), ('business', 'Business')],
                default='user',
                max_length=10,
                help_text='Type of recipient (user or business)'
            ),
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='sender_display_name',
            field=models.CharField(
                blank=True,
                max_length=255,
                help_text='Display name for the sender'
            ),
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='recipient_display_name',
            field=models.CharField(
                blank=True,
                max_length=255,
                help_text='Display name for the recipient'
            ),
        ),
        
        # Add indexes for the new fields
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['sender_business'], name='send_sendtransaction_sender_business_idx'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['recipient_business'], name='send_sendtransaction_recipient_business_idx'),
        ),
    ]
