# Generated by Django 5.2 on 2026-07-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0006_alter_phoneinvite_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtransaction',
            name='transaction_hash',
            field=models.CharField(blank=True, help_text='Algorand transaction ID (52 chars; field kept at 66 for legacy rows)', max_length=66, null=True, unique=True),
        ),
    ]
