# Generated by Django 4.2.20 on 2025-07-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0006_add_business_support'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sendtransaction',
            name='send_sendtransaction_sender_business_idx',
        ),
        migrations.RemoveIndex(
            model_name='sendtransaction',
            name='send_sendtransaction_recipient_business_idx',
        ),
        migrations.RenameIndex(
            model_name='sendtransaction',
            new_name='send_sendtr_transac_ec6151_idx',
            old_name='send_transa_transac_66b202_idx',
        ),
        migrations.RenameIndex(
            model_name='sendtransaction',
            new_name='send_sendtr_sender__a83073_idx',
            old_name='send_transa_sender__8f7670_idx',
        ),
        migrations.RenameIndex(
            model_name='sendtransaction',
            new_name='send_sendtr_recipie_a91a25_idx',
            old_name='send_transa_recipie_a7159a_idx',
        ),
        migrations.RenameIndex(
            model_name='sendtransaction',
            new_name='send_sendtr_sender__040c7a_idx',
            old_name='send_transa_sender__a424fe_idx',
        ),
        migrations.RenameIndex(
            model_name='sendtransaction',
            new_name='send_sendtr_recipie_a3f268_idx',
            old_name='send_transa_recipie_573104_idx',
        ),
        migrations.RenameIndex(
            model_name='sendtransaction',
            new_name='send_sendtr_created_2422da_idx',
            old_name='send_transa_created_94232c_idx',
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Optional key to prevent duplicate transactions', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['sender_business', 'status'], name='send_sendtr_sender__631d62_idx'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['recipient_business', 'status'], name='send_sendtr_recipie_185477_idx'),
        ),
        migrations.AddIndex(
            model_name='sendtransaction',
            index=models.Index(fields=['idempotency_key'], name='send_sendtr_idempot_171c7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='sendtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('idempotency_key__isnull', False)), fields=('sender_user', 'idempotency_key'), name='unique_send_idempotency'),
        ),
    ]
