# Generated by Django 4.2.20 on 2025-07-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0007_remove_sendtransaction_send_sendtransaction_sender_business_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendtransaction',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='Recipient phone number at transaction time', max_length=30),
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='sender_phone',
            field=models.CharField(blank=True, help_text='Sender phone number at transaction time', max_length=30),
        ),
    ]
