# Generated by Django 5.2 on 2026-07-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0007_alter_sendtransaction_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendtransaction',
            name='bsc_calls_json',
            field=models.TextField(blank=True, default='', help_text='Sponsored 7702 call batch for BSC sends (server-built at prepare)'),
        ),
        migrations.AlterField(
            model_name='phoneinvite',
            name='token_type',
            field=models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin'), ('ALGO', 'ALGO'), ('CUSD_PLUS', 'Confío Dollar Plus'), ('USDT', 'Tether USD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sendtransaction',
            name='token_type',
            field=models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin'), ('ALGO', 'ALGO'), ('CUSD_PLUS', 'Confío Dollar Plus'), ('USDT', 'Tether USD')], max_length=10),
        ),
    ]
