# Generated by Django 5.2 on 2026-07-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0008_sendtransaction_bsc_calls_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('reclaiming', 'Reclaim in flight'), ('reclaimed', 'Reclaimed')], default='pending', max_length=16),
        ),
    ]
