# Generated by Django 5.2 on 2026-08-01 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0009_alter_phoneinvite_status'),
        ('users', '0029_unifiedtransactiontable_cusd_plus_conversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sendtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('idempotency_key__isnull', False), ('sender_user__isnull', True)), fields=('idempotency_key',), name='unique_external_inbound_idempotency'),
        ),
    ]
