# Generated by Django 5.2 on 2026-08-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0010_sendtransaction_unique_external_inbound_idempotency'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneinvite',
            name='inviter_address',
            field=models.CharField(blank=True, default='', max_length=42),
        ),
    ]
