# Generated by Django 4.2.20 on 2025-07-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0010_cleanup_legacy_display_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendtransaction',
            name='is_invitation',
            field=models.BooleanField(default=False, help_text='True if this transaction includes an invitation to join Confío'),
        ),
    ]
