# Generated by Django 4.2.20 on 2025-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0011_add_invitation_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendtransaction',
            name='invitation_claimed',
            field=models.BooleanField(default=False, help_text='True if the invitation was claimed by the recipient'),
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='invitation_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the invitation expires (7 days after creation)', null=True),
        ),
        migrations.AddField(
            model_name='sendtransaction',
            name='invitation_reverted',
            field=models.BooleanField(default=False, help_text='True if the invitation expired and funds were returned to sender'),
        ),
    ]
