# Generated by Django 5.2 on 2026-08-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0011_phoneinvite_inviter_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneinvite',
            name='status',
            field=models.CharField(choices=[('draft', 'Prepared, nothing broadcast'), ('creating', 'Create batch in flight'), ('pending', 'Escrowed, awaiting claim'), ('claiming', 'Claim in flight'), ('claimed', 'Claimed'), ('reclaiming', 'Reclaim in flight'), ('reclaimed', 'Reclaimed'), ('failed', 'Create never landed')], default='pending', max_length=16),
        ),
    ]
