# Generated by Django 5.2 on 2026-08-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0013_backfill_phoneinvite_inviter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneinvite',
            name='rail',
            field=models.CharField(choices=[('algorand', 'Algorand'), ('bsc', 'BNB Smart Chain')], db_index=True, default='algorand', max_length=8),
        ),
    ]
