# Generated by Django 4.2.20 on 2025-07-27 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send', '0014_set_invitation_expiry_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtransaction',
            name='recipient_type',
            field=models.CharField(choices=[('user', 'Personal'), ('business', 'Business'), ('external', 'External')], default='user', help_text='Type of recipient (user or business)', max_length=10),
        ),
        migrations.AlterField(
            model_name='sendtransaction',
            name='sender_type',
            field=models.CharField(choices=[('user', 'Personal'), ('business', 'Business'), ('external', 'External')], default='user', help_text='Type of sender (user or business)', max_length=10),
        ),
        migrations.AlterField(
            model_name='sendtransaction',
            name='sender_user',
            field=models.ForeignKey(blank=True, help_text='User who sent the transaction (null for external deposits)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
