# Generated by Django 4.2.20 on 2025-07-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0015_support_external_deposits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SPONSORING', 'Sponsoring'), ('SIGNED', 'Signed'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('AML_REVIEW', 'Under AML Review')], default='PENDING', max_length=10),
        ),
    ]
