# Generated by Django 4.2.20 on 2025-07-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0016_alter_sendtransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
    ]
