# Generated by Django 4.2.20 on 2025-07-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0018_convert_amount_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtransaction',
            name='transaction_hash',
            field=models.CharField(blank=True, help_text='Sui transaction digest (0x + 32 bytes, 66 hex characters total)', max_length=66, null=True, unique=True),
        ),
    ]
