# Generated by Django 4.2.20 on 2025-07-20 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p2p_exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2POffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('exchange_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('token_type', models.CharField(choices=[('cUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms', models.TextField(blank=True)),
                ('response_time_minutes', models.IntegerField(default=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('auto_complete_enabled', models.BooleanField(default=False)),
                ('auto_complete_time_minutes', models.IntegerField(default=30)),
                ('payment_methods', models.ManyToManyField(related_name='offers', to='p2p_exchange.p2ppaymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='p2ptrade',
            name='exchange',
        ),
        migrations.DeleteModel(
            name='P2PExchange',
        ),
        migrations.AddField(
            model_name='p2ptrade',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='p2p_exchange.p2poffer'),
        ),
        migrations.AddIndex(
            model_name='p2poffer',
            index=models.Index(fields=['exchange_type', 'token_type', 'status'], name='p2p_exchang_exchang_9a02fd_idx'),
        ),
        migrations.AddIndex(
            model_name='p2poffer',
            index=models.Index(fields=['rate'], name='p2p_exchang_rate_e0d538_idx'),
        ),
        migrations.AddIndex(
            model_name='p2poffer',
            index=models.Index(fields=['created_at'], name='p2p_exchang_created_9b1b99_idx'),
        ),
    ]
