# Generated by Django 4.2.20 on 2025-07-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0002_rename_p2pexchange_to_p2poffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ppaymentmethod',
            name='country_code',
            field=models.CharField(blank=True, help_text="ISO country code (e.g., 'VE', 'US'). Leave empty for global methods.", max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='p2ppaymentmethod',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='p2ppaymentmethod',
            unique_together={('name', 'country_code')},
        ),
    ]
