# Generated by Django 5.2 on 2025-12-17 14:54

import p2p_exchange.models
from django.db import migrations, models
import uuid

def populate_uuids(apps, schema_editor):
    P2PTrade = apps.get_model('p2p_exchange', 'P2PTrade')
    for row in P2PTrade.objects.all():
        row.internal_id = uuid.uuid4().hex
        row.save(update_fields=['internal_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ptrade',
            name='internal_id',
            field=models.CharField(default=None, editable=False, max_length=32, null=True),
        ),
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='p2ptrade',
            name='internal_id',
            field=models.CharField(default=p2p_exchange.models.generate_p2p_trade_id, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
