# Generated by Django 4.2.20 on 2025-07-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0003_p2ppaymentmethod_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2poffer',
            name='country_code',
            field=models.CharField(default='VE', help_text="ISO country code (e.g., 'VE', 'US', 'AS')", max_length=2),
            preserve_default=False,
        ),
    ]
