# Generated by Django 4.2.20 on 2025-07-21 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_soft_delete_fields'),
        ('p2p_exchange', '0004_p2poffer_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2poffer',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account used for this offer (personal or business)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_offers', to='users.account'),
        ),
        migrations.AddField(
            model_name='p2ptrade',
            name='buyer_account',
            field=models.ForeignKey(blank=True, help_text="Buyer's account used for this trade", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_purchases', to='users.account'),
        ),
        migrations.AddField(
            model_name='p2ptrade',
            name='seller_account',
            field=models.ForeignKey(blank=True, help_text="Seller's account used for this trade", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_sales', to='users.account'),
        ),
    ]
