# Generated by Django 4.2.20 on 2025-07-21 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p2p_exchange', '0005_p2poffer_account_p2ptrade_buyer_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ptrade',
            name='buyer_business',
            field=models.ForeignKey(blank=True, help_text='Business that is buying (for business trades)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_purchases', to='users.business'),
        ),
        migrations.AddField(
            model_name='p2ptrade',
            name='buyer_user',
            field=models.ForeignKey(blank=True, help_text='User who is buying (for personal trades)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_purchases_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='p2ptrade',
            name='seller_business',
            field=models.ForeignKey(blank=True, help_text='Business that is selling (for business trades)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_sales', to='users.business'),
        ),
        migrations.AddField(
            model_name='p2ptrade',
            name='seller_user',
            field=models.ForeignKey(blank=True, help_text='User who is selling (for personal trades)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_sales_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='p2ptrade',
            name='buyer',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use buyer_user or buyer_business instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_purchases_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='p2ptrade',
            name='buyer_account',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use buyer_user or buyer_business instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_purchases_old', to='users.account'),
        ),
        migrations.AlterField(
            model_name='p2ptrade',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use seller_user or seller_business instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_sales_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='p2ptrade',
            name='seller_account',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use seller_user or seller_business instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_sales_old', to='users.account'),
        ),
        migrations.AddIndex(
            model_name='p2ptrade',
            index=models.Index(fields=['buyer_user', 'status'], name='p2p_exchang_buyer_u_f5cc77_idx'),
        ),
        migrations.AddIndex(
            model_name='p2ptrade',
            index=models.Index(fields=['buyer_business', 'status'], name='p2p_exchang_buyer_b_68aece_idx'),
        ),
        migrations.AddIndex(
            model_name='p2ptrade',
            index=models.Index(fields=['seller_user', 'status'], name='p2p_exchang_seller__5b1dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='p2ptrade',
            index=models.Index(fields=['seller_business', 'status'], name='p2p_exchang_seller__ed2339_idx'),
        ),
    ]
