# Generated by Django 4.2.20 on 2025-07-21 02:15

from django.db import migrations


def populate_direct_relationships(apps, schema_editor):
    """
    Populate the new direct user/business foreign key fields based on existing account data.
    """
    P2PTrade = apps.get_model('p2p_exchange', 'P2PTrade')
    Account = apps.get_model('users', 'Account')
    
    print("Populating direct user/business relationships for P2P trades...")
    
    for trade in P2PTrade.objects.all():
        print(f"Processing trade {trade.id}...")
        
        # Process buyer
        if trade.buyer_account:
            account = trade.buyer_account
            if account.account_type == 'business' and account.business:
                trade.buyer_business = account.business
                print(f"  Buyer: Set business {account.business.name}")
            else:
                trade.buyer_user = trade.buyer  # Use the user from old field
                print(f"  Buyer: Set user {trade.buyer.username}")
        elif trade.buyer:
            # Fallback: if no account but has buyer, assume personal
            trade.buyer_user = trade.buyer
            print(f"  Buyer: Fallback to user {trade.buyer.username}")
            
        # Process seller
        if trade.seller_account:
            account = trade.seller_account
            if account.account_type == 'business' and account.business:
                trade.seller_business = account.business
                print(f"  Seller: Set business {account.business.name}")
            else:
                trade.seller_user = trade.seller  # Use the user from old field
                print(f"  Seller: Set user {trade.seller.username}")
        elif trade.seller:
            # Fallback: if no account but has seller, assume personal
            trade.seller_user = trade.seller
            print(f"  Seller: Fallback to user {trade.seller.username}")
            
        trade.save()
        print(f"  Trade {trade.id} updated successfully")
    
    print("✅ Direct relationship population completed!")


def reverse_populate_direct_relationships(apps, schema_editor):
    """
    Reverse migration: Clear the new direct relationship fields.
    """
    P2PTrade = apps.get_model('p2p_exchange', 'P2PTrade')
    
    print("Clearing direct user/business relationships...")
    for trade in P2PTrade.objects.all():
        trade.buyer_user = None
        trade.buyer_business = None
        trade.seller_user = None
        trade.seller_business = None
        trade.save()
    print("✅ Direct relationships cleared!")


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0006_add_direct_user_business_relationships'),
    ]

    operations = [
        migrations.RunPython(
            populate_direct_relationships,
            reverse_populate_direct_relationships
        ),
    ]
