# Generated by Django 4.2.20 on 2025-07-21 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p2p_exchange', '0007_populate_direct_user_business_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2poffer',
            name='offer_business',
            field=models.ForeignKey(blank=True, help_text='Business creating this offer (for business offers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_offers', to='users.business'),
        ),
        migrations.AddField(
            model_name='p2poffer',
            name='offer_user',
            field=models.ForeignKey(blank=True, help_text='User creating this offer (for personal offers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_offers_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='p2poffer',
            name='account',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use offer_user or offer_business instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_offers_old', to='users.account'),
        ),
        migrations.AlterField(
            model_name='p2poffer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use offer_user or offer_business instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_offers_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='p2poffer',
            index=models.Index(fields=['offer_user', 'status'], name='p2p_exchang_offer_u_19b75d_idx'),
        ),
        migrations.AddIndex(
            model_name='p2poffer',
            index=models.Index(fields=['offer_business', 'status'], name='p2p_exchang_offer_b_1eca15_idx'),
        ),
    ]
