# Generated by Django 4.2.20 on 2025-07-21 02:34

from django.db import migrations


def populate_offer_direct_relationships(apps, schema_editor):
    """
    Populate the new direct user/business foreign key fields for offers based on existing account data.
    """
    P2POffer = apps.get_model('p2p_exchange', 'P2POffer')
    Account = apps.get_model('users', 'Account')
    
    print("Populating direct user/business relationships for P2P offers...")
    
    for offer in P2POffer.objects.all():
        print(f"Processing offer {offer.id}...")
        
        if offer.account:
            # Offer has account - determine if business or personal
            account = offer.account
            if account.account_type == 'business' and account.business:
                offer.offer_business = account.business
                print(f"  Set offer_business to: {account.business.name}")
            else:
                offer.offer_user = offer.user  # Use the user from old field
                print(f"  Set offer_user to: {offer.user.username}")
        elif offer.user:
            # Fallback: if no account but has user, assume personal
            offer.offer_user = offer.user
            print(f"  Fallback: Set offer_user to: {offer.user.username}")
            
        offer.save()
        print(f"  Offer {offer.id} updated successfully")
    
    print("✅ Offer direct relationship population completed!")


def reverse_populate_offer_direct_relationships(apps, schema_editor):
    """
    Reverse migration: Clear the new direct relationship fields for offers.
    """
    P2POffer = apps.get_model('p2p_exchange', 'P2POffer')
    
    print("Clearing offer direct user/business relationships...")
    for offer in P2POffer.objects.all():
        offer.offer_user = None
        offer.offer_business = None
        offer.save()
    print("✅ Offer direct relationships cleared!")


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0008_add_direct_user_business_to_offers'),
    ]

    operations = [
        migrations.RunPython(
            populate_offer_direct_relationships,
            reverse_populate_offer_direct_relationships
        ),
    ]
