# Generated by Django 4.2.20 on 2025-07-21 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_add_soft_delete_fields'),
        ('p2p_exchange', '0009_populate_offer_direct_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pmessage',
            name='sender_business',
            field=models.ForeignKey(blank=True, help_text='Business sending this message (for business messages)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_messages_sent', to='users.business'),
        ),
        migrations.AddField(
            model_name='p2pmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, help_text='User sending this message (for personal messages)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_messages_sent_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='p2puserstats',
            name='stats_business',
            field=models.OneToOneField(blank=True, help_text='Business these stats belong to (for business account stats)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_stats', to='users.business'),
        ),
        migrations.AddField(
            model_name='p2puserstats',
            name='stats_user',
            field=models.OneToOneField(blank=True, help_text='User these stats belong to (for personal account stats)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='p2pmessage',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use sender_user or sender_business instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_messages_sent_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='p2puserstats',
            name='user',
            field=models.OneToOneField(blank=True, help_text='DEPRECATED: Use stats_user or stats_business instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_stats_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='p2pmessage',
            index=models.Index(fields=['sender_user', 'is_read'], name='p2p_exchang_sender__707b76_idx'),
        ),
        migrations.AddIndex(
            model_name='p2pmessage',
            index=models.Index(fields=['sender_business', 'is_read'], name='p2p_exchang_sender__bda543_idx'),
        ),
    ]
