# Generated by Django 4.2.20 on 2025-07-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_country_bank_bankinfo'),
        ('p2p_exchange', '0011_populate_message_stats_direct_relationships'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='p2ppaymentmethod',
            options={'ordering': ['display_order', 'display_name']},
        ),
        migrations.AddField(
            model_name='p2ppaymentmethod',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Reference to Bank model if this is a bank-based payment method', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.bank'),
        ),
        migrations.AddField(
            model_name='p2ppaymentmethod',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the payment method'),
        ),
        migrations.AddField(
            model_name='p2ppaymentmethod',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for displaying in UI (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='p2ppaymentmethod',
            name='provider_type',
            field=models.CharField(choices=[('bank', 'Traditional Bank'), ('fintech', 'Fintech/Digital Wallet'), ('crypto', 'Crypto Service'), ('cash', 'Cash/Physical'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='p2ppaymentmethod',
            name='requires_account_number',
            field=models.BooleanField(default=True, help_text='Whether this method requires an account number'),
        ),
        migrations.AddField(
            model_name='p2ppaymentmethod',
            name='requires_email',
            field=models.BooleanField(default=False, help_text='Whether this method requires an email (e.g., PayPal)'),
        ),
        migrations.AddField(
            model_name='p2ppaymentmethod',
            name='requires_phone',
            field=models.BooleanField(default=False, help_text='Whether this method requires a phone number (e.g., Pago Móvil)'),
        ),
        migrations.AlterField(
            model_name='p2ppaymentmethod',
            name='display_name',
            field=models.CharField(help_text="User-friendly name (e.g., 'Banco de Venezuela', 'Nequi')", max_length=100),
        ),
        migrations.AlterField(
            model_name='p2ppaymentmethod',
            name='icon',
            field=models.CharField(blank=True, help_text='Frontend icon reference', max_length=50),
        ),
        migrations.AlterField(
            model_name='p2ppaymentmethod',
            name='name',
            field=models.CharField(help_text="Unique identifier (e.g., 'banco_venezuela', 'nequi')", max_length=50),
        ),
    ]
