# Generated by Django 4.2.20 on 2025-07-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_populate_payment_method_for_existing_bankinfo'),
        ('p2p_exchange', '0012_add_payment_method_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ppaymentmethod',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country for non-bank payment methods (e.g., fintech, mobile payments)', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country'),
        ),
        migrations.AlterField(
            model_name='p2ppaymentmethod',
            name='provider_type',
            field=models.CharField(choices=[('bank', 'Traditional Bank'), ('fintech', 'Fintech/Digital Wallet'), ('cash', 'Cash/Physical'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
