# Generated by Django 4.2.20 on 2025-07-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0015_fix_payment_method_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ptrade',
            name='country_code',
            field=models.CharField(default='VE', help_text='ISO country code from the offer', max_length=2),
        ),
        migrations.AddField(
            model_name='p2ptrade',
            name='currency_code',
            field=models.CharField(default='VES', help_text="Currency code (e.g., 'VES', 'COP', 'ARS')", max_length=3),
        ),
    ]
