# Generated by Django 4.2.20 on 2025-07-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0016_add_country_currency_to_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2poffer',
            name='currency_code',
            field=models.CharField(default='', help_text="Currency code (e.g., 'VES', 'COP', 'ARS')", max_length=3),
        ),
    ]
