# Generated by Django 4.2.20 on 2025-07-24 01:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_populate_payment_method_for_existing_bankinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p2p_exchange', '0018_populate_offer_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PTradeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('speed_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reliability_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('ratee_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_ratings_received', to='users.business')),
                ('ratee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_ratings_given', to='users.business')),
                ('rater_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='p2p_exchange.p2ptrade')),
            ],
            options={
                'ordering': ['-rated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='p2ptraderating',
            constraint=models.UniqueConstraint(fields=('trade',), name='unique_rating_per_trade'),
        ),
    ]
