# Generated by Django 4.2.20 on 2025-07-24 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0019_add_trade_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2puserstats',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average rating from completed trades (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
