# Generated by Django 4.2.20 on 2025-07-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0020_add_avg_rating_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='p2ptraderating',
            name='unique_rating_per_trade',
        ),
        migrations.AlterField(
            model_name='p2ptraderating',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='p2p_exchange.p2ptrade'),
        ),
        migrations.AddConstraint(
            model_name='p2ptraderating',
            constraint=models.UniqueConstraint(fields=('trade', 'rater_user', 'rater_business'), name='unique_rating_per_rater_per_trade'),
        ),
    ]
