# Generated by Django 4.2.20 on 2025-07-24 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0022_add_trade_confirmations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2ptradeconfirmation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='p2ptradeconfirmation',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='p2p_exchange.p2ptrade'),
        ),
    ]
