# Generated by Django 4.2.20 on 2025-07-25 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0025_p2pdispute_remove_p2puserstats_unique_stats_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p2ptrade',
            name='dispute_reason',
        ),
        migrations.RemoveField(
            model_name='p2ptrade',
            name='disputed_at',
        ),
        migrations.RemoveField(
            model_name='p2ptrade',
            name='resolved_at',
        ),
    ]
