# Generated by Django 4.2.20 on 2025-07-25 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_populate_payment_method_for_existing_bankinfo'),
        ('p2p_exchange', '0026_remove_redundant_dispute_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PDisputeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('transaction_type', models.CharField(choices=[('REFUND', 'Refund to Buyer'), ('RELEASE', 'Release to Seller'), ('PARTIAL_REFUND', 'Partial Refund'), ('SPLIT', 'Split Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('token_type', models.CharField(max_length=10)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='p2p_exchange.p2pdispute')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_transactions_processed', to=settings.AUTH_USER_MODEL)),
                ('recipient_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_transactions_received', to='users.business')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_transactions_received', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_transactions', to='p2p_exchange.p2ptrade')),
            ],
            options={
                'db_table': 'p2p_dispute_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dispute', 'status'], name='p2p_dispute_dispute_921c7e_idx'), models.Index(fields=['transaction_hash'], name='p2p_dispute_transac_0b974a_idx'), models.Index(fields=['processed_at'], name='p2p_dispute_process_59e6de_idx')],
            },
        ),
    ]
