# Generated by Django 4.2.20 on 2025-07-25 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0027_add_dispute_transaction_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pescrow',
            name='dispute_resolution',
            field=models.ForeignKey(blank=True, help_text='Link to dispute that resolved this escrow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_resolutions', to='p2p_exchange.p2pdispute'),
        ),
        migrations.AddField(
            model_name='p2pescrow',
            name='release_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount released (may be less than escrow_amount for partial refunds)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='p2pescrow',
            name='release_type',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal Release to Seller'), ('REFUND', 'Refund to Buyer'), ('PARTIAL_REFUND', 'Partial Refund'), ('DISPUTE_RELEASE', 'Dispute Release to Seller')], help_text='How the funds were released from escrow', max_length=20),
        ),
        migrations.AddField(
            model_name='p2pescrow',
            name='resolved_by_dispute',
            field=models.BooleanField(default=False, help_text='True if this escrow was resolved through dispute resolution'),
        ),
        migrations.AlterField(
            model_name='p2pescrow',
            name='is_escrowed',
            field=models.BooleanField(default=False, help_text='Funds are currently held in escrow'),
        ),
        migrations.AlterField(
            model_name='p2pescrow',
            name='is_released',
            field=models.BooleanField(default=False, help_text='Funds have been released from escrow'),
        ),
        migrations.AlterModelTable(
            name='p2pescrow',
            table='p2p_escrows',
        ),
    ]
