# Generated by Django 4.2.20 on 2025-07-25 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_populate_payment_method_for_existing_bankinfo'),
        ('p2p_exchange', '0028_enhance_escrow_for_disputes'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PFavoriteTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('note', models.TextField(blank=True, help_text='Personal note about this trader')),
                ('favorite_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='users.business')),
                ('favorite_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_traders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'p2p_favorite_traders',
                'indexes': [models.Index(fields=['user', 'created_at'], name='p2p_favorit_user_id_c1805d_idx')],
                'unique_together': {('user', 'favorite_business'), ('user', 'favorite_user')},
            },
        ),
    ]
