# Generated by Django 4.2.20 on 2025-07-25 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_populate_payment_method_for_existing_bankinfo'),
        ('p2p_exchange', '0029_add_favorite_traders'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='p2pfavoritetrader',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='p2pfavoritetrader',
            name='favoriter_business',
            field=models.ForeignKey(blank=True, help_text='If favoriting from a business account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_favorite_traders', to='users.business'),
        ),
        migrations.AlterUniqueTogether(
            name='p2pfavoritetrader',
            unique_together={('user', 'favoriter_business', 'favorite_business'), ('user', 'favoriter_business', 'favorite_user')},
        ),
        migrations.AddIndex(
            model_name='p2pfavoritetrader',
            index=models.Index(fields=['favoriter_business', 'created_at'], name='p2p_favorit_favorit_4958eb_idx'),
        ),
    ]
