# Generated by Django 4.2.20 on 2025-07-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_exchange', '0030_add_favoriter_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2ptrade',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_SENT', 'Payment Sent'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('CRYPTO_RELEASED', 'Crypto Released'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('AML_REVIEW', 'Under AML Review')], default='PENDING', max_length=20),
        ),
    ]
