# Generated by Django manually to fix migration dependency issue

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Empty initial migration to fix dependency chain
    ]