# Generated by Django 4.2.20 on 2025-04-19 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prover.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sub', models.CharField(blank=True, max_length=255, null=True)),
                ('apple_sub', models.CharField(blank=True, max_length=255, null=True)),
                ('sui_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zk_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZkLoginProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_id', models.CharField(default=prover.models.generate_proof_id, editable=False, max_length=32, unique=True)),
                ('max_epoch', models.PositiveIntegerField()),
                ('randomness', models.BinaryField()),
                ('extended_ephemeral_public_key', models.BinaryField()),
                ('user_signature', models.BinaryField()),
                ('proof_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zk_proofs', to='prover.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
