# Generated by Django 4.2.14 on 2023-10-05 20:55
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Original models removed
    ]