# Generated by Django 4.2.20 on 2025-05-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_country_user_phone_number'),
        ('prover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zkloginproof',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zk_proofs', to='users.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
