# Generated by Django 4.2.20 on 2025-05-18 13:36
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0001_initial'),
    ]

    operations = [
        # Original operations removed
    ]