# Generated by Django 4.2.20 on 2025-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_salt',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
