# Generated by Django 4.2.20 on 2025-05-18 13:36
# Modified to be empty - model no longer exists

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0001_initial'),
    ]

    operations = [
        # Model removed - empty migration for compatibility
    ]