# Generated by Django 4.2.20 on 2025-05-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0002_userprofile_user_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='apple_sub',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='google_sub',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_salt',
        ),
    ]
