# Generated by Django 4.2.20 on 2025-04-18 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import prover.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prover', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zkloginproof',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profil_firebas_c3f353_idx',
        ),
        migrations.RemoveIndex(
            model_name='zkloginproof',
            name='prover_zklo_user_id_f79aac_idx',
        ),
        migrations.RemoveIndex(
            model_name='zkloginproof',
            name='prover_zklo_is_veri_ac2e16_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='firebase_uid',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zk_salt_b64',
        ),
        migrations.RemoveField(
            model_name='zkloginproof',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='zkloginproof',
            name='proof_data',
        ),
        migrations.RemoveField(
            model_name='zkloginproof',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sui_address',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zkloginproof',
            name='extended_ephemeral_public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zkloginproof',
            name='proof',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zkloginproof',
            name='proof_id',
            field=models.CharField(default=prover.models.generate_proof_id, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='zkloginproof',
            name='user_salt',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zkloginproof',
            name='user_signature',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='zkloginproof',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='zkloginproof',
            name='jwt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zkloginproof',
            name='max_epoch',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zkloginproof',
            name='randomness',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zkloginproof',
            name='salt',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zkloginproof',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zk_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='zkloginproof',
            table='zk_login_proofs',
        ),
    ]
