# Generated by Django 4.2.20 on 2025-07-01 23:34
# Modified to be empty - model no longer exists

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0002_alter_zkloginproof_profile_delete_userprofile'),
    ]

    operations = [
        # Model removed - empty migration for compatibility
    ]