# Generated by Django 4.2.20 on 2025-04-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0003_alter_zkloginproof_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_salt',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
