# Generated by Django 4.2.20 on 2025-07-01 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account_business_delete_userprofile_account_business_and_more'),
        ('prover', '0003_remove_zkloginproof_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkloginproof',
            name='account',
            field=models.ForeignKey(default=None, help_text='Account for this specific zkLogin proof', on_delete=django.db.models.deletion.CASCADE, related_name='zk_proofs', to='users.account'),
            preserve_default=False,
        ),
    ]
