# Generated by Django 4.2.20 on 2025-07-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0004_zkloginproof_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkloginproof',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True),
        ),
        migrations.AddField(
            model_name='zkloginproof',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
