# Generated by Django 4.2.20 on 2025-04-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0004_userprofile_user_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_sub',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
