# Generated by Django 5.2 on 2025-08-03 00:31
# Migration to remove ZkLoginProof model - zkLogin proofs should be client-side only

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0005_add_soft_delete_to_zklogin_proof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZkLoginProof',
        ),
    ]
