# Generated by Django 4.2.20 on 2025-04-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0005_userprofile_google_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sui_address',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
