# Generated by Django 4.2.20 on 2025-04-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0006_alter_userprofile_sui_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apple_sub',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
