import React, { useMemo, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  TouchableOpacity,
  ScrollView,
} from 'react-native';
import Icon from 'react-native-vector-icons/Feather';
import Svg, { Defs, Stop, LinearGradient as SvgLinearGradient, Rect, Circle } from 'react-native-svg';
import { Header } from '../navigation/Header';
import { useNavigation } from '@react-navigation/native';
import { NavigationProp } from '@react-navigation/native';
import { useMutation } from '@apollo/client';
import { UPDATE_USERNAME } from '../apollo/queries';
import { MainStackParamList } from '../types/navigation';
import { useAuth } from '../contexts/AuthContext';
import { colors } from '../config/theme';
import { InlineBanner } from '../components/common/InlineBanner';

const normalizeChunk = (value: string) => {
  if (!value) return 'confio';
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '')
    .slice(0, 12) || 'confio';
};

export const UpdateUsernameScreen: React.FC = () => {
  const navigation = useNavigation<NavigationProp<MainStackParamList>>();
  const { userProfile, refreshProfile } = useAuth();
  const currentUsername = userProfile?.username || '';
  const [username, setUsername] = useState(currentUsername);
  const [usernameError, setUsernameError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [banner, setBanner] = useState<{ message: string; variant: 'error' | 'success' | 'info' } | null>(null);
  const dismissBanner = React.useCallback(() => setBanner(null), []);
  const [updateUsername] = useMutation(UPDATE_USERNAME);

  const validateUsername = (value: string) => {
    const trimmed = value.trim();
    if (trimmed.length < 3) {
      return 'El usuario debe tener al menos 3 caracteres';
    }
    if (trimmed.length > 30) {
      return 'El usuario no puede tener más de 30 caracteres';
    }
    if (!/^[a-zA-Z0-9_]+$/.test(trimmed)) {
      return 'Solo se permiten letras, números y guiones bajos (_)';
    }
    return null;
  };

  const sanitizedFirst = useMemo(() => normalizeChunk(userProfile?.firstName || ''), [userProfile?.firstName]);
  const sanitizedLast = useMemo(() => normalizeChunk(userProfile?.lastName || ''), [userProfile?.lastName]);
  const phoneSuffix = useMemo(() => {
    const digits = (userProfile?.phoneNumber || '').replace(/\D/g, '');
    return digits.slice(-4);
  }, [userProfile?.phoneNumber]);

  const suggestions = useMemo(() => {
    const baseCandidates = new Set<string>();

    if (currentUsername && !currentUsername.startsWith('user_') && !/^[a-z0-9]{10,}$/.test(currentUsername)) {
      baseCandidates.add(normalizeChunk(currentUsername));
    }

    if (sanitizedFirst) {
      baseCandidates.add(sanitizedFirst);
      if (sanitizedLast) {
        baseCandidates.add(`${sanitizedFirst}${sanitizedLast.charAt(0)}`);
        baseCandidates.add(`${sanitizedFirst}_${sanitizedLast}`);
      }
      baseCandidates.add(`${sanitizedFirst}confio`);
      baseCandidates.add(`${sanitizedFirst}ve`);
      if (phoneSuffix.length >= 2) {
        baseCandidates.add(`${sanitizedFirst}${phoneSuffix}`);
      }
    }

    if (sanitizedLast) {
      baseCandidates.add(`${sanitizedLast}${sanitizedFirst.charAt(0)}`);
    }

    const fallback = normalizeChunk('confio');
    baseCandidates.add(fallback);
    baseCandidates.add(`${fallback}${new Date().getFullYear()}`);

    const unique = Array.from(baseCandidates)
      .map((candidate) => candidate.slice(0, 24))
      .filter((candidate) => candidate.length >= 3)
      .filter((candidate) => candidate !== currentUsername);

    return unique.slice(0, 6);
  }, [currentUsername, sanitizedFirst, sanitizedLast]);

  const handleSuggestionPress = (suggestion: string) => {
    setUsername(suggestion);
    setUsernameError(null);
  };

  const handleSave = async () => {
    const trimmed = username.trim();
    const validation = validateUsername(trimmed);
    if (validation) {
      setUsernameError(validation);
      return;
    }
    if (trimmed === currentUsername) {
      setBanner({ variant: 'info', message: 'Tu usuario ya está configurado con ese nombre.' });
      return;
    }

    setIsSaving(true);
    setUsernameError(null);
    try {
      const { data } = await updateUsername({
        variables: { username: trimmed },
      });
      if (data?.updateUsername?.success) {
        // No interrupting dialog: the updated @usuario on the previous
        // screen is the confirmation.
        await refreshProfile('personal');
        navigation.goBack();
      } else {
        const message = data?.updateUsername?.error || 'No se pudo actualizar el usuario. Intenta con otro nombre.';
        setUsernameError(message);
      }
    } catch (error) {
      setUsernameError('No se pudo actualizar el usuario. Inténtalo nuevamente.');
    } finally {
      setIsSaving(false);
    }
  };

  const isAutoGenerated = useMemo(
    () => Boolean(currentUsername && (currentUsername.startsWith('user_') || /^[a-z0-9]{10,}$/.test(currentUsername))),
    [currentUsername],
  );

  // Live preview: what friends will see, updating as the user types.
  const previewUsername = username.trim() || currentUsername || 'tuusuario';
  const previewChanged = username.trim() !== currentUsername && username.trim().length > 0;

  return (
    <View style={styles.safeArea}>
      <Header
        navigation={navigation as any}
        title="Editar usuario"
        backgroundColor={colors.secondary}
        isLight
        showBackButton
        rightAccessory={(
          <TouchableOpacity
            style={[styles.saveButton, isSaving && styles.saveButtonDisabled]}
            onPress={handleSave}
            disabled={isSaving}
            hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
            accessibilityRole="button"
            accessibilityLabel="Guardar usuario"
            accessibilityState={{ disabled: isSaving, busy: isSaving }}
          >
            <Text style={styles.saveButtonText}>{isSaving ? 'Guardando…' : 'Guardar'}</Text>
          </TouchableOpacity>
        )}
      />

      <ScrollView style={styles.container} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
        {/* Live preview on the violet suite field: the @usuario being crafted
            IS the hero, updating with every keystroke. Gradient + coin ring,
            padding on fieldInner (Yoga absolute-child rule). */}
        <View style={styles.brandField}>
          <Svg style={StyleSheet.absoluteFill}>
            <Defs>
              <SvgLinearGradient id="usernameField" x1="0" y1="0" x2="0" y2="1">
                <Stop offset="0" stopColor={colors.secondary} />
                <Stop offset="1" stopColor={colors.secondaryDark} />
              </SvgLinearGradient>
            </Defs>
            <Rect width="100%" height="100%" fill="url(#usernameField)" />
            <Circle cx="106%" cy="12%" r="90" stroke={colors.white} strokeWidth="22" strokeOpacity="0.10" fill="none" />
          </Svg>
          <View style={styles.fieldInner}>
            <Text style={styles.fieldEyebrow}>ASÍ TE VERÁN TUS AMIGOS</Text>
            <Text style={styles.fieldUsername} numberOfLines={1} adjustsFontSizeToFit>
              @{previewUsername}
            </Text>
            <View style={styles.fieldStatusRow}>
              {previewChanged ? (
                <>
                  <Icon name="edit-2" size={12} color={colors.violetLight} />
                  <Text style={styles.fieldStatusText}>Sin guardar — toca Guardar para confirmar</Text>
                </>
              ) : (
                <Text style={styles.fieldStatusText}>
                  Aparece en tu perfil y en tus invitaciones
                </Text>
              )}
            </View>
          </View>
        </View>

        <View style={styles.body}>
          {banner && (
            <InlineBanner
              message={banner.message}
              variant={banner.variant}
              onDismiss={dismissBanner}
              style={{ marginBottom: 0 }}
            />
          )}

          {isAutoGenerated && (
            <View style={styles.autoNotice}>
              <Icon name="alert-circle" size={15} color={colors.warning.icon} />
              <Text style={styles.autoNoticeText}>
                Tu usuario actual fue creado automáticamente. Elige uno más
                fácil de recordar y dictar.
              </Text>
            </View>
          )}

          <View style={styles.inputCard}>
            <Text style={styles.inputLabel}>Nuevo usuario</Text>
            <View style={[styles.inputRow, usernameError && styles.inputRowError]}>
              <Text style={styles.inputPrefix}>@</Text>
              <TextInput
                style={styles.input}
                value={username}
                onChangeText={(text) => {
                  setUsername(text);
                  setUsernameError(text.trim() ? validateUsername(text) : null);
                }}
                autoCapitalize="none"
                autoCorrect={false}
                placeholder="maria_confio"
                placeholderTextColor={colors.muted}
                maxLength={30}
              />
            </View>
            <View style={styles.inputFooter}>
              <Text style={styles.inputHint}>Letras, números y guiones bajos.</Text>
              <Text style={[styles.charCount, username.length > 25 && styles.charCountWarn]}>
                {username.length}/30
              </Text>
            </View>
            {usernameError && <Text style={styles.errorText}>{usernameError}</Text>}

            {suggestions.length > 0 && (
              <View style={styles.suggestionsBlock}>
                <Text style={styles.suggestionsTitle}>Sugerencias rápidas</Text>
                <View style={styles.suggestionsRow}>
                  {suggestions.slice(0, 6).map((suggestion) => (
                    <TouchableOpacity
                      key={suggestion}
                      style={styles.suggestionChip}
                      onPress={() => handleSuggestionPress(suggestion)}
                      accessibilityRole="button"
                      accessibilityLabel={`Usar ${suggestion}`}
                    >
                      <Text style={styles.suggestionText}>@{suggestion}</Text>
                    </TouchableOpacity>
                  ))}
                </View>
              </View>
            )}

            <View style={styles.tipsRow}>
              <Icon name="info" size={13} color={colors.text.secondary} />
              <Text style={styles.tipItem}>
                Usa tu nombre, apodo o negocio — corto y fácil de dictar. Tus
                amigos lo escriben en "¿Quién te invitó?" al registrarse.
              </Text>
            </View>
          </View>
        </View>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  saveButton: {
    backgroundColor: colors.white,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  saveButtonDisabled: {
    opacity: 0.5,
  },
  saveButtonText: {
    color: colors.secondary,
    fontWeight: '700',
  },
  container: {
    flex: 1,
  },
  content: {
    paddingBottom: 32,
  },
  brandField: {
    backgroundColor: colors.secondary,
    overflow: 'hidden',
  },
  fieldInner: {
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 24,
    alignItems: 'center',
  },
  fieldEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2,
    color: colors.violetLight,
    marginBottom: 10,
  },
  fieldUsername: {
    fontSize: 32,
    fontWeight: '800',
    color: colors.white,
    textAlign: 'center',
  },
  fieldStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  fieldStatusText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.violetLight,
    textAlign: 'center',
  },
  body: {
    padding: 20,
    gap: 14,
  },
  autoNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: colors.warning.background,
    borderWidth: 1,
    borderColor: colors.warning.border,
    borderRadius: 12,
    padding: 12,
  },
  autoNoticeText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: colors.warning.text,
  },
  inputCard: {
    backgroundColor: colors.background,
    borderRadius: 16,
    padding: 20,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.dark,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.borderMedium,
    borderRadius: 12,
    backgroundColor: colors.neutral,
    paddingHorizontal: 14,
  },
  inputRowError: {
    borderColor: colors.danger,
  },
  inputPrefix: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.secondary,
    marginRight: 4,
  },
  input: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.dark,
  },
  inputFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inputHint: {
    fontSize: 12,
    color: colors.text.secondary,
  },
  charCount: {
    fontSize: 12,
    color: colors.muted,
  },
  charCountWarn: {
    color: colors.error.icon,
  },
  errorText: {
    fontSize: 13,
    color: colors.danger,
  },
  suggestionsBlock: {
    gap: 10,
    marginTop: 4,
  },
  suggestionsTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text.secondary,
  },
  suggestionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  suggestionChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: colors.violetLight,
  },
  suggestionText: {
    color: colors.secondary,
    fontWeight: '600',
  },
  tipsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  tipItem: {
    flex: 1,
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 17,
  },
});

export default UpdateUsernameScreen;
