# Generated by Django 4.2.20 on 2025-08-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0049_add_aml_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(choices=[('CUSD', 'cUSD'), ('CONFIO', 'CONFIO'), ('SUI', 'SUI'), ('USDC', 'USDC')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawBlockchainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('sender', models.CharField(db_index=True, max_length=66)),
                ('module', models.CharField(db_index=True, max_length=66)),
                ('function', models.CharField(max_length=100)),
                ('raw_data', models.JSONField()),
                ('block_time', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-block_time'],
            },
        ),
        migrations.CreateModel(
            name='TransactionProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.rawblockchainevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='rawblockchainevent',
            index=models.Index(fields=['sender', 'block_time'], name='blockchain__sender_3baec2_idx'),
        ),
        migrations.AddIndex(
            model_name='rawblockchainevent',
            index=models.Index(fields=['module', 'function'], name='blockchain__module_920375_idx'),
        ),
        migrations.AddIndex(
            model_name='rawblockchainevent',
            index=models.Index(fields=['processed', 'created_at'], name='blockchain__process_4ca922_idx'),
        ),
        migrations.AddField(
            model_name='balance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='users.account'),
        ),
        migrations.AddIndex(
            model_name='transactionprocessinglog',
            index=models.Index(fields=['status', 'created_at'], name='blockchain__status_599918_idx'),
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['account', 'token'], name='blockchain__account_a741b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('account', 'token')},
        ),
    ]
