# Generated by Django 5.2 on 2025-09-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(choices=[('CUSD', 'cUSD'), ('CONFIO', 'CONFIO'), ('CONFIO_PRESALE', 'CONFIO_PRESALE'), ('USDC', 'USDC')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('pending_amount', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('is_stale', models.BooleanField(default=False, help_text='True if balance needs refresh')),
                ('last_blockchain_check', models.DateTimeField(blank=True, null=True)),
                ('sync_attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IndexerAssetCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.BigIntegerField(db_index=True, unique=True)),
                ('last_scanned_round', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('currency', models.CharField(choices=[('CUSD', 'cUSD'), ('CONFIO', 'CONFIO'), ('USDC', 'USDC'), ('ALGO', 'ALGO')], max_length=10)),
                ('fee_amount', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('net_amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('blockchain_network', models.CharField(default='algorand', max_length=20)),
                ('sender_address', models.CharField(max_length=100)),
                ('recipient_address', models.CharField(max_length=100)),
                ('transaction_hash', models.CharField(blank=True, db_index=True, max_length=100)),
                ('confirmed_at_block', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('blockchain_data', models.JSONField(blank=True, help_text='Store sponsor transactions and other blockchain data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=100, unique=True)),
                ('block_number', models.BigIntegerField()),
                ('receipt_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedIndexerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(db_index=True, max_length=100)),
                ('asset_id', models.BigIntegerField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=100)),
                ('receiver', models.CharField(blank=True, max_length=100)),
                ('confirmed_round', models.BigIntegerField(default=0)),
                ('intra', models.IntegerField(default=0, help_text='Intra-round offset if available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
