# Generated by Django 4.2.20 on 2025-08-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='last_updated',
            new_name='last_synced',
        ),
        migrations.AddField(
            model_name='balance',
            name='is_stale',
            field=models.BooleanField(default=False, help_text='True if balance needs refresh'),
        ),
        migrations.AddField(
            model_name='balance',
            name='last_blockchain_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='pending_amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=36),
        ),
        migrations.AddField(
            model_name='balance',
            name='sync_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['is_stale', 'last_synced'], name='blockchain__is_stal_6007c0_idx'),
        ),
    ]
