# Generated by Django 5.2 on 2025-09-02 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='users.account'),
        ),
        migrations.AddIndex(
            model_name='indexerassetcursor',
            index=models.Index(fields=['last_scanned_round'], name='blockchain__last_sc_72b0cc_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Business owner (for tracking)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient_business',
            field=models.ForeignKey(blank=True, help_text='Business that received the payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='users.business'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_business',
            field=models.ForeignKey(blank=True, help_text='Business account that sent the payment (if from business)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_sent', to='users.business'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='blockchain.payment'),
        ),
        migrations.AddIndex(
            model_name='processedindexertransaction',
            index=models.Index(fields=['asset_id', 'confirmed_round'], name='blockchain__asset_i_9be4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='processedindexertransaction',
            index=models.Index(fields=['receiver'], name='blockchain__receive_906863_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processedindexertransaction',
            unique_together={('txid', 'intra')},
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['account', 'token'], name='blockchain__account_a741b0_idx'),
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['is_stale', 'last_synced'], name='blockchain__is_stal_6007c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('account', 'token')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sender', 'status', '-created_at'], name='blockchain__sender__24182d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['recipient', 'status', '-created_at'], name='blockchain__recipie_a46f42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='blockchain__payment_f39c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_e86869_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_fa6718_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['block_number'], name='blockchain__block_n_fcf64b_idx'),
        ),
    ]
