# Generated by Django 5.2 on 2025-12-17 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_initial'),
        ('users', '0013_user_platform_os'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='blockchain__payment_f39c1f_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='internal_id',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['internal_id'], name='blockchain__interna_521561_idx'),
        ),
    ]
