# Generated by Django 4.2.20 on 2025-08-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_rename_last_updated_balance_last_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawblockchainevent',
            name='checkpoint',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawblockchainevent',
            name='epoch',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='SuiEpoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch_number', models.BigIntegerField(db_index=True, unique=True)),
                ('start_timestamp_ms', models.BigIntegerField()),
                ('end_timestamp_ms', models.BigIntegerField(blank=True, null=True)),
                ('first_checkpoint', models.BigIntegerField()),
                ('last_checkpoint', models.BigIntegerField(blank=True, null=True)),
                ('total_transactions', models.BigIntegerField(default=0)),
                ('total_gas_cost', models.BigIntegerField(default=0)),
                ('stake_subsidy_amount', models.BigIntegerField(default=0)),
                ('total_stake_rewards', models.BigIntegerField(default=0)),
                ('storage_fund_balance', models.BigIntegerField(default=0)),
                ('epoch_commitments', models.JSONField(blank=True, default=list)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-epoch_number'],
                'indexes': [models.Index(fields=['is_current'], name='blockchain__is_curr_4966f4_idx'), models.Index(fields=['start_timestamp_ms', 'end_timestamp_ms'], name='blockchain__start_t_ae346e_idx')],
            },
        ),
    ]
