# Generated by Django 5.2 on 2025-08-13 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_add_epoch_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('currency', models.CharField(choices=[('CUSD', 'cUSD'), ('CONFIO', 'CONFIO'), ('USDC', 'USDC'), ('ALGO', 'ALGO')], max_length=10)),
                ('fee_amount', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('net_amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('blockchain_network', models.CharField(default='algorand', max_length=20)),
                ('sender_address', models.CharField(max_length=100)),
                ('recipient_address', models.CharField(max_length=100)),
                ('transaction_hash', models.CharField(blank=True, db_index=True, max_length=100)),
                ('confirmed_at_block', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=100, unique=True)),
                ('block_number', models.BigIntegerField()),
                ('receipt_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='blockchain.payment')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sender', 'status', '-created_at'], name='blockchain__sender__24182d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['recipient', 'status', '-created_at'], name='blockchain__recipie_a46f42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='blockchain__payment_f39c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_e86869_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_fa6718_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['block_number'], name='blockchain__block_n_fcf64b_idx'),
        ),
    ]
