# Generated by Django 5.2 on 2026-02-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_remove_payment_blockchain__payment_f39c1f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='token',
            field=models.CharField(choices=[('ALGO', 'ALGO'), ('CUSD', 'cUSD'), ('CONFIO', 'CONFIO'), ('CONFIO_PRESALE', 'CONFIO_PRESALE'), ('USDC', 'USDC')], max_length=20),
        ),
    ]
