# Generated by Django 5.2 on 2025-08-13 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_add_payment_models'),
        ('users', '0058_alter_unified_status_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recipient_business',
            field=models.ForeignKey(blank=True, help_text='Business that received the payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='users.business'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_business',
            field=models.ForeignKey(blank=True, help_text='Business account that sent the payment (if from business)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_sent', to='users.business'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Business owner (for tracking)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
