# Generated by Django 5.2 on 2026-03-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_add_algo_to_balance_token_choices'),
        ('conversion', '0001_initial'),
        ('usdc_transactions', '0001_initial'),
        ('users', '0019_unifiedtransactiontable_ramp_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAutoSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], default='user', max_length=10)),
                ('actor_address', models.CharField(blank=True, default='', max_length=100)),
                ('asset_type', models.CharField(choices=[('USDC', 'USDC'), ('ALGO', 'ALGO')], max_length=10)),
                ('amount_micro', models.BigIntegerField(default=0)),
                ('amount_decimal', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('source_address', models.CharField(blank=True, default='', max_length=100)),
                ('source_tx_hash', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_auto_swaps', to='users.account')),
                ('actor_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_auto_swaps', to='users.business')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_auto_swaps', to=settings.AUTH_USER_MODEL)),
                ('conversion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_auto_swap', to='conversion.conversion')),
                ('usdc_deposit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_auto_swap', to='usdc_transactions.usdcdeposit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pendingautoswap',
            index=models.Index(fields=['account', 'status', '-created_at'], name='blockchain_p_account_112f10_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingautoswap',
            index=models.Index(fields=['actor_user', 'status', '-created_at'], name='blockchain_p_actor_u_9b9f19_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingautoswap',
            index=models.Index(fields=['actor_business', 'status', '-created_at'], name='blockchain_p_actor_b_628722_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingautoswap',
            index=models.Index(fields=['asset_type', 'status', '-created_at'], name='blockchain_p_asset_t_6e2f84_idx'),
        ),
    ]
