# Generated by Django 5.2 on 2026-03-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_pendingautoswap'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingautoswap',
            new_name='blockchain__account_c15d86_idx',
            old_name='blockchain_p_account_112f10_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingautoswap',
            new_name='blockchain__actor_u_b0c7c3_idx',
            old_name='blockchain_p_actor_u_9b9f19_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingautoswap',
            new_name='blockchain__actor_b_e2c7fa_idx',
            old_name='blockchain_p_actor_b_628722_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingautoswap',
            new_name='blockchain__asset_t_927130_idx',
            old_name='blockchain_p_asset_t_6e2f84_idx',
        ),
    ]
