# Generated by Django 5.2 on 2025-08-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_add_business_fields_to_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='blockchain_data',
            field=models.JSONField(blank=True, help_text='Store sponsor transactions and other blockchain data', null=True),
        ),
    ]
