# Generated by Django 5.2 on 2026-08-01 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_rename_blockchain_p_account_112f10_idx_blockchain__account_c15d86_idx_and_more'),
        # The table must have left cusd_plus's state before this adopts it.
        ('cusd_plus', '0013_remove_sponsoredbatch_user_delete_bnbautoconvert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingautoswap',
            name='asset_type',
            field=models.CharField(choices=[('USDC', 'USDC'), ('ALGO', 'ALGO'), ('BNB', 'BNB')], max_length=10),
        ),
        # Adopt the table cusd_plus handed over: STATE only, so the 8 rows
        # are never dropped and recreated.
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.CreateModel(
                name='SponsoredBatch',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('user_bsc_address', models.CharField(max_length=42)),
                    ('kind', models.CharField(max_length=32)),
                    ('source_id', models.BigIntegerField(blank=True, null=True)),
                    ('num_calls', models.PositiveSmallIntegerField()),
                    ('calls_json', models.TextField()),
                    ('tx_hash', models.CharField(blank=True, max_length=66)),
                    ('delegate_nonce', models.BigIntegerField(blank=True, null=True)),
                    ('block_number', models.BigIntegerField(blank=True, null=True)),
                    ('block_hash', models.CharField(blank=True, max_length=66)),
                    ('gas_limit', models.PositiveIntegerField()),
                    ('max_fee_wei', models.CharField(max_length=32)),
                    ('status', models.CharField(choices=[('signed', 'Signed, broadcast unconfirmed'), ('sent', 'Broadcast, receipt pending'), ('confirmed', 'Mined, executed and final'), ('reverted', 'Mined but reverted'), ('noop_failed', 'Mined, but delegation did not apply (no-op)'), ('reorged', 'Was mined then orphaned by a reorg'), ('dropped', 'Signed but never reached the chain')], default='sent', max_length=16)),
                    ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                    ('updated_at', models.DateTimeField(auto_now=True)),
                    ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_batches', to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'db_table': 'cusd_plus_sponsored_batches',
                    'ordering': ['-created_at'],
                    'indexes': [models.Index(fields=['user', 'created_at'], name='cpsb_user_created_idx'), models.Index(fields=['tx_hash'], name='cpsb_tx_hash_idx'), models.Index(fields=['status'], name='cpsb_status_idx'), models.Index(fields=['kind', 'source_id'], name='cpsb_kind_source_idx')],
                    'constraints': [models.UniqueConstraint(condition=models.Q(('tx_hash__gt', '')), fields=('tx_hash',), name='cpsb_unique_tx_hash')],
                },
            ),
            ],
            database_operations=[],
        ),
        # Now a real rename: the ledger serves send/pay/payroll/presale/
        # invites, so the cusd_plus_ prefix was a mislabel.
        migrations.AlterModelTable(
            name='sponsoredbatch',
            table='sponsored_batches',
        ),
    ]
