# Generated by Django 5.2 on 2025-08-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_add_blockchain_data_to_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexerAddressCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=58, unique=True)),
                ('last_scanned_round', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_scanned_round'], name='blockchain__last_sc_3acbe7_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndexerAssetCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.BigIntegerField(db_index=True, unique=True)),
                ('last_scanned_round', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_scanned_round'], name='blockchain__last_sc_72b0cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedIndexerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(db_index=True, max_length=100)),
                ('asset_id', models.BigIntegerField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=100)),
                ('receiver', models.CharField(blank=True, max_length=100)),
                ('confirmed_round', models.BigIntegerField(default=0)),
                ('intra', models.IntegerField(default=0, help_text='Intra-round offset if available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['asset_id', 'confirmed_round'], name='blockchain__asset_i_9be4d8_idx'), models.Index(fields=['receiver'], name='blockchain__receive_906863_idx')],
                'unique_together': {('txid', 'intra')},
            },
        ),
    ]
