# Generated by Django 5.2 on 2025-08-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_indexeraddresscursor_indexerassetcursor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexerAddressCursor',
        ),
    ]
