# Generated by Django 5.2 on 2026-08-02 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_alter_pendingautoswap_asset_type_sponsoredbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sponsoredbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'presale_buy'), ('status__in', ('signed', 'sent', 'confirmed'))), fields=('kind', 'source_id'), name='cpsb_unique_active_presale_buy'),
        ),
    ]
