# Generated by Django 5.2 on 2025-08-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_delete_indexeraddresscursor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuiEpoch',
        ),
        migrations.AlterField(
            model_name='balance',
            name='token',
            field=models.CharField(choices=[('CUSD', 'cUSD'), ('CONFIO', 'CONFIO'), ('USDC', 'USDC')], max_length=20),
        ),
    ]
