# Generated by Django 5.2 on 2026-08-02 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_sponsoredbatch_cpsb_unique_active_presale_buy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sponsoredbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'payroll_payout'), ('status__in', ('signed', 'sent', 'confirmed'))), fields=('kind', 'source_id'), name='cpsb_unique_active_payroll_payout'),
        ),
    ]
