# Generated by Django 5.2 on 2026-08-02 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0010_payment_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sponsoredbatch',
            name='cpsb_unique_active_payment',
        ),
        migrations.AddConstraint(
            model_name='sponsoredbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ('pay_cusd_plus', 'pay_usdt', 'pay_confio')), ('status__in', ('signed', 'sent', 'confirmed'))), fields=('source_id',), name='cpsb_unique_active_payment'),
        ),
    ]
