# Generated by Django 4.2.20 on 2025-08-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0010_cleanup_sui_balances'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionProcessingLog',
        ),
        migrations.DeleteModel(
            name='RawBlockchainEvent',
        ),
    ]

