# Generated by Django 5.2 on 2026-08-06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0011_payment_unique_by_source'),
        ('users', '0038_account_solana_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolanaSponsorGlobalDailySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('spent_lamports', models.BigIntegerField(default=0)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('spent_lamports__gte', 0)), name='solana_global_spend_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='SolanaSponsorBalanceState',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('observed_balance_lamports', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('observed_balance_lamports__gte', 0)), name='sol_sponsor_observed_balance_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='SolanaSponsorDailySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('spent_lamports', models.BigIntegerField(default=0)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solana_sponsor_daily_spend', to='users.account')),
            ],
        ),
        migrations.CreateModel(
            name='SolanaSponsoredTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_hash', models.CharField(max_length=64, unique=True)),
                ('recent_blockhash', models.CharField(max_length=64)),
                ('confirmation_slot', models.BigIntegerField(blank=True, null=True)),
                ('fee_lamports', models.BigIntegerField()),
                ('signature', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('reserved', 'Fee reserved, broadcast not confirmed'), ('signed', 'Sponsor signature recorded before RPC exposure'), ('sent', 'RPC accepted transaction'), ('unknown', 'Broadcast outcome unknown'), ('confirmed_pending', 'Confirmed; awaiting a balance observation at that slot'), ('confirmed', 'Transaction reached confirmed commitment'), ('expired', 'Blockhash expired without a recorded transaction'), ('failed', 'Failed before a sponsor signature was exposed')], default='reserved', max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solana_sponsored_transactions', to='users.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solana_sponsored_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'created_at'], name='sol_sponsor_acct_created'), models.Index(fields=['status'], name='sol_sponsor_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fee_lamports__gte', 0)), name='sol_sponsor_fee_nonnegative')],
            },
        ),
        migrations.AddConstraint(
            model_name='solanasponsordailyspend',
            constraint=models.UniqueConstraint(fields=('account', 'day'), name='solana_spend_account_day_unique'),
        ),
        migrations.AddConstraint(
            model_name='solanasponsordailyspend',
            constraint=models.CheckConstraint(condition=models.Q(('spent_lamports__gte', 0)), name='solana_account_spend_nonnegative'),
        ),
    ]
