# Generated by Django 5.2 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0012_ondostocktrade_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredbatch',
            name='client_request_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sponsoredbatch',
            name='delegate_nonce_claimed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='sponsoredbatch',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('delegate_nonce__isnull', False),
                    ('delegate_nonce_claimed', True),
                    ('status__in', ('signed', 'sent', 'confirmed')),
                ),
                fields=('user_bsc_address', 'delegate_nonce'),
                name='cpsb_unique_active_delegate_nonce',
            ),
        ),
        migrations.AddConstraint(
            model_name='sponsoredbatch',
            constraint=models.UniqueConstraint(
                condition=models.Q(('client_request_id__gt', '')),
                fields=('user', 'client_request_id'),
                name='cpsb_unique_client_request',
            ),
        ),
    ]
