# Generated by Django 5.2 on 2026-10-05 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0016_sponsoredbatch_addr_kind_idx'),
        ('users', '0050_cusd_plus_savings_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='address',
            field=models.CharField(blank=True, db_default='', default='', max_length=42),
        ),
        migrations.AlterField(
            model_name='balance',
            name='token',
            field=models.CharField(choices=[('ALGO', 'ALGO'), ('CUSD', 'cUSD'), ('CONFIO', 'CONFIO'), ('CONFIO_PRESALE', 'CONFIO_PRESALE'), ('USDC', 'USDC'), ('CUSD_BSC', 'cUSD (BSC)'), ('CONFIO_BSC', 'CONFIO (BSC)'), ('USDT_BSC', 'USDT (BSC)'), ('CUSD_PLUS', 'cUSD+ shares (BSC)')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsc_address', models.CharField(help_text='Lowercase BSC wallet address', max_length=42, unique=True)),
                ('held', models.JSONField(default=dict, help_text='{symbol: units} for every nonzero balance, delisted included')),
                ('blocks', models.JSONField(default=dict, help_text='{symbol: block the balance was read at}')),
                ('scanned_at', models.DateTimeField()),
                ('is_stale', models.BooleanField(default=False, help_text='True if the next read must re-scan the chain')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_holdings', to='users.account')),
            ],
            options={
                'verbose_name': 'Stock holdings',
                'verbose_name_plural': 'Stock holdings',
            },
        ),
    ]
