name = "confio-link-shortener"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Routes for custom domain
routes = [
  { pattern = "confio.lat/*", zone_id = "1fae8d4a5dbd820442e673422099f4ec" },
  { pattern = "www.confio.lat/*", zone_id = "1fae8d4a5dbd820442e673422099f4ec" }
]

# KV namespaces for storing link data
[[kv_namespaces]]
binding = "LINKS"
id = "6c2befc8ea7e41f9a755a2c84a8fe0cf"

[[kv_namespaces]]
binding = "ANALYTICS"
id = "dffde50153144ae1ad733007e1d01991"

# Environment variables
[vars]
APPLE_APP_ID = "YOUR_APPLE_APP_ID"
ANDROID_PACKAGE_ID = "com.Confio.Confio"
IOS_BUNDLE_ID = "com.Confio.Confio"
TESTFLIGHT_URL = "https://testflight.apple.com/join/YOUR_CODE"
PLAY_STORE_URL = "https://play.google.com/store/apps/details?id=com.Confio.Confio"
LANDING_PAGE_URL = "https://confio.lat"

# Production environment (inherits all settings above)
[env.production]
vars = { LANDING_PAGE_URL = "https://confio.lat" }