module invite_send::invite_send {
    use aptos_framework::fungible_asset::{Self, FungibleAsset, Metadata};
    use aptos_framework::primary_fungible_store;
    use aptos_framework::object::{Self, Object};
    use aptos_framework::signer::address_of;
    use aptos_framework::timestamp;
    use aptos_framework::event;
    use aptos_framework::table::{Self, Table};
    use aptos_framework::account;
    use aptos_framework::resource_account;
    use std::error;
    use std::signer;
    use cusd::cusd;
    use confio::confio;

    // Error codes
    const E_NOT_AUTHORIZED: u64 = 1;
    const E_INVALID_AMOUNT: u64 = 2;
    const E_INVITATION_NOT_FOUND: u64 = 3;
    const E_INVITATION_ALREADY_CLAIMED: u64 = 4;
    const E_INVITATION_EXPIRED: u64 = 5;
    const E_INVITATION_NOT_EXPIRED: u64 = 6;
    const E_SYSTEM_PAUSED: u64 = 7;
    const E_NOT_ADMIN: u64 = 8;
    const E_INVITATION_EXISTS: u64 = 9;

    // Constants
    const RECLAIM_PERIOD_MS: u64 = 604800000000; // 7 days in microseconds

    // Resources
    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct AdminConfig has key {
        admin: address,
        is_paused: bool,
        // Statistics
        total_invitations_created: u64,
        total_invitations_claimed: u64,
        total_invitations_reclaimed: u64,
        total_cusd_locked: u64,
        total_confio_locked: u64
    }

    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct InvitationRegistry has key {
        invitations: Table<vector<u8>, Invitation>,
    }

    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct InvitationVault has key {
        cusd_balances: Table<vector<u8>, u64>,
        confio_balances: Table<vector<u8>, u64>,
    }

    struct Invitation has store, copy, drop {
        // Sender information
        sender: address,
        // Amount locked
        amount: u64,
        // Token type: "CUSD" or "CONFIO"
        token_type: vector<u8>,
        // Creation timestamp
        created_at: u64,
        // Expiry timestamp (created_at + 7 days)
        expires_at: u64,
        // Status
        is_claimed: bool,
        is_reclaimed: bool,
        // Optional message from sender
        message: vector<u8>
    }

    // Events
    #[event]
    struct InvitationCreated has drop, store {
        invitation_id: vector<u8>,
        sender: address,
        amount: u64,
        token_type: vector<u8>,
        expires_at: u64,
        message: vector<u8>,
        timestamp: u64
    }

    #[event]
    struct InvitationClaimed has drop, store {
        invitation_id: vector<u8>,
        sender: address,
        recipient: address,
        amount: u64,
        token_type: vector<u8>,
        timestamp: u64
    }

    #[event]
    struct InvitationReclaimed has drop, store {
        invitation_id: vector<u8>,
        sender: address,
        amount: u64,
        token_type: vector<u8>,
        timestamp: u64
    }

    #[event]
    struct SystemPaused has drop, store {
        timestamp: u64
    }

    #[event]
    struct SystemUnpaused has drop, store {
        timestamp: u64
    }

    // Initialize
    fun init_module(admin: &signer) {
        // Initialize admin config
        move_to(admin, AdminConfig {
            admin: address_of(admin),
            is_paused: false,
            total_invitations_created: 0,
            total_invitations_claimed: 0,
            total_invitations_reclaimed: 0,
            total_cusd_locked: 0,
            total_confio_locked: 0
        });

        move_to(admin, InvitationRegistry {
            invitations: table::new(),
        });

        move_to(admin, InvitationVault {
            cusd_balances: table::new(),
            confio_balances: table::new(),
        });
    }

    // Create invitation with cUSD
    public entry fun create_cusd_invitation(
        sender: &signer,
        amount: u64,
        invitation_id: vector<u8>, // Generated by Django (e.g., UUID)
        message: vector<u8>,
    ) acquires AdminConfig, InvitationRegistry, InvitationVault {
        let admin_config = borrow_global_mut<AdminConfig>(@invite_send);
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        assert!(amount > 0, error::invalid_argument(E_INVALID_AMOUNT));
        
        let registry = borrow_global_mut<InvitationRegistry>(@invite_send);
        assert!(!table::contains(&registry.invitations, invitation_id), error::already_exists(E_INVITATION_EXISTS));
        
        let current_time = timestamp::now_microseconds();
        let expires_at = current_time + RECLAIM_PERIOD_MS;
        
        // Create invitation record
        let invitation = Invitation {
            sender: address_of(sender),
            amount,
            token_type: b"CUSD",
            created_at: current_time,
            expires_at,
            is_claimed: false,
            is_reclaimed: false,
            message
        };
        
        // Store invitation
        table::add(&mut registry.invitations, invitation_id, invitation);
        
        // Lock the funds by transferring to the module account
        let cusd_metadata = cusd::get_metadata();
        primary_fungible_store::transfer(sender, cusd_metadata, @invite_send, amount);
        
        let vault = borrow_global_mut<InvitationVault>(@invite_send);
        table::add(&mut vault.cusd_balances, invitation_id, amount);
        
        // Update statistics
        admin_config.total_invitations_created = admin_config.total_invitations_created + 1;
        admin_config.total_cusd_locked = admin_config.total_cusd_locked + amount;
        
        // Emit event
        event::emit(InvitationCreated {
            invitation_id,
            sender: address_of(sender),
            amount,
            token_type: b"CUSD",
            expires_at,
            message,
            timestamp: current_time
        });
    }

    // Create invitation with CONFIO
    public entry fun create_confio_invitation(
        sender: &signer,
        amount: u64,
        invitation_id: vector<u8>,
        message: vector<u8>,
    ) acquires AdminConfig, InvitationRegistry, InvitationVault {
        let admin_config = borrow_global_mut<AdminConfig>(@invite_send);
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        assert!(amount > 0, error::invalid_argument(E_INVALID_AMOUNT));
        
        let registry = borrow_global_mut<InvitationRegistry>(@invite_send);
        assert!(!table::contains(&registry.invitations, invitation_id), error::already_exists(E_INVITATION_EXISTS));
        
        let current_time = timestamp::now_microseconds();
        let expires_at = current_time + RECLAIM_PERIOD_MS;
        
        // Create invitation record
        let invitation = Invitation {
            sender: address_of(sender),
            amount,
            token_type: b"CONFIO",
            created_at: current_time,
            expires_at,
            is_claimed: false,
            is_reclaimed: false,
            message
        };
        
        // Store invitation
        table::add(&mut registry.invitations, invitation_id, invitation);
        
        // Lock the funds by transferring to the module account
        let confio_metadata = confio::get_metadata();
        primary_fungible_store::transfer(sender, confio_metadata, @invite_send, amount);
        
        let vault = borrow_global_mut<InvitationVault>(@invite_send);
        table::add(&mut vault.confio_balances, invitation_id, amount);
        
        // Update statistics
        admin_config.total_invitations_created = admin_config.total_invitations_created + 1;
        admin_config.total_confio_locked = admin_config.total_confio_locked + amount;
        
        // Emit event
        event::emit(InvitationCreated {
            invitation_id,
            sender: address_of(sender),
            amount,
            token_type: b"CONFIO",
            expires_at,
            message,
            timestamp: current_time
        });
    }

    // Admin claims invitation on behalf of verified user
    public entry fun claim_invitation(
        admin: &signer,
        invitation_id: vector<u8>,
        recipient: address, // New user's Aptos address from keyless account
    ) acquires AdminConfig, InvitationRegistry, InvitationVault {
        let admin_config = borrow_global_mut<AdminConfig>(@invite_send);
        assert!(address_of(admin) == admin_config.admin, error::permission_denied(E_NOT_ADMIN));
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        
        let registry = borrow_global_mut<InvitationRegistry>(@invite_send);
        assert!(table::contains(&registry.invitations, invitation_id), error::not_found(E_INVITATION_NOT_FOUND));
        
        let invitation = table::borrow_mut(&mut registry.invitations, invitation_id);
        assert!(!invitation.is_claimed, error::invalid_state(E_INVITATION_ALREADY_CLAIMED));
        assert!(!invitation.is_reclaimed, error::invalid_state(E_INVITATION_ALREADY_CLAIMED));
        
        let current_time = timestamp::now_microseconds();
        assert!(current_time <= invitation.expires_at, error::invalid_state(E_INVITATION_EXPIRED));
        
        // Mark as claimed
        invitation.is_claimed = true;
        
        // Get amount and token type
        let amount = invitation.amount;
        let token_type = invitation.token_type;
        let sender = invitation.sender;
        
        let vault = borrow_global_mut<InvitationVault>(@invite_send);
        
        // Transfer funds based on token type
        // Note: In a production system, this would need proper escrow mechanism
        // For now, we track amounts and assume the admin manages the actual transfers
        if (token_type == b"CUSD") {
            let locked_amount = table::remove(&mut vault.cusd_balances, invitation_id);
            
            // Update statistics
            admin_config.total_cusd_locked = admin_config.total_cusd_locked - locked_amount;
        } else {
            let locked_amount = table::remove(&mut vault.confio_balances, invitation_id);
            
            // Update statistics
            admin_config.total_confio_locked = admin_config.total_confio_locked - locked_amount;
        };
        
        admin_config.total_invitations_claimed = admin_config.total_invitations_claimed + 1;
        
        // Emit event
        event::emit(InvitationClaimed {
            invitation_id,
            sender,
            recipient,
            amount,
            token_type,
            timestamp: current_time
        });
    }

    // Sender reclaims expired invitation
    public entry fun reclaim_invitation(
        sender: &signer,
        invitation_id: vector<u8>,
    ) acquires AdminConfig, InvitationRegistry, InvitationVault {
        let admin_config = borrow_global_mut<AdminConfig>(@invite_send);
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        
        let registry = borrow_global_mut<InvitationRegistry>(@invite_send);
        assert!(table::contains(&registry.invitations, invitation_id), error::not_found(E_INVITATION_NOT_FOUND));
        
        let invitation = table::borrow_mut(&mut registry.invitations, invitation_id);
        assert!(invitation.sender == address_of(sender), error::permission_denied(E_NOT_AUTHORIZED));
        assert!(!invitation.is_claimed, error::invalid_state(E_INVITATION_ALREADY_CLAIMED));
        assert!(!invitation.is_reclaimed, error::invalid_state(E_INVITATION_ALREADY_CLAIMED));
        
        let current_time = timestamp::now_microseconds();
        assert!(current_time > invitation.expires_at, error::invalid_state(E_INVITATION_NOT_EXPIRED));
        
        // Mark as reclaimed
        invitation.is_reclaimed = true;
        
        // Get amount and token type
        let amount = invitation.amount;
        let token_type = invitation.token_type;
        
        let vault = borrow_global_mut<InvitationVault>(@invite_send);
        
        // Return funds to sender
        // Note: In a production system, this would need proper escrow mechanism
        // For now, we track amounts and assume the admin manages the actual transfers
        if (token_type == b"CUSD") {
            let locked_amount = table::remove(&mut vault.cusd_balances, invitation_id);
            
            // Update statistics
            admin_config.total_cusd_locked = admin_config.total_cusd_locked - locked_amount;
        } else {
            let locked_amount = table::remove(&mut vault.confio_balances, invitation_id);
            
            // Update statistics
            admin_config.total_confio_locked = admin_config.total_confio_locked - locked_amount;
        };
        
        admin_config.total_invitations_reclaimed = admin_config.total_invitations_reclaimed + 1;
        
        // Emit event
        event::emit(InvitationReclaimed {
            invitation_id,
            sender: address_of(sender),
            amount,
            token_type,
            timestamp: current_time
        });
    }

    // Admin functions
    public entry fun pause(admin: &signer) acquires AdminConfig {
        let admin_config = borrow_global_mut<AdminConfig>(@invite_send);
        assert!(address_of(admin) == admin_config.admin, error::permission_denied(E_NOT_ADMIN));
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        
        admin_config.is_paused = true;
        
        event::emit(SystemPaused {
            timestamp: timestamp::now_microseconds()
        });
    }

    public entry fun unpause(admin: &signer) acquires AdminConfig {
        let admin_config = borrow_global_mut<AdminConfig>(@invite_send);
        assert!(address_of(admin) == admin_config.admin, error::permission_denied(E_NOT_ADMIN));
        assert!(admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        
        admin_config.is_paused = false;
        
        event::emit(SystemUnpaused {
            timestamp: timestamp::now_microseconds()
        });
    }

    // View functions
    #[view]
    public fun get_invitation(invitation_id: vector<u8>): Invitation acquires InvitationRegistry {
        let registry = borrow_global<InvitationRegistry>(@invite_send);
        assert!(table::contains(&registry.invitations, invitation_id), error::not_found(E_INVITATION_NOT_FOUND));
        *table::borrow(&registry.invitations, invitation_id)
    }

    #[view]
    public fun is_invitation_claimable(
        invitation_id: vector<u8>
    ): bool acquires InvitationRegistry {
        let registry = borrow_global<InvitationRegistry>(@invite_send);
        if (!table::contains(&registry.invitations, invitation_id)) {
            return false
        };
        
        let invitation = table::borrow(&registry.invitations, invitation_id);
        let current_time = timestamp::now_microseconds();
        
        !invitation.is_claimed && 
        !invitation.is_reclaimed && 
        current_time <= invitation.expires_at
    }

    #[view]
    public fun is_invitation_reclaimable(
        invitation_id: vector<u8>,
        sender_address: address
    ): bool acquires InvitationRegistry {
        let registry = borrow_global<InvitationRegistry>(@invite_send);
        if (!table::contains(&registry.invitations, invitation_id)) {
            return false
        };
        
        let invitation = table::borrow(&registry.invitations, invitation_id);
        let current_time = timestamp::now_microseconds();
        
        invitation.sender == sender_address &&
        !invitation.is_claimed && 
        !invitation.is_reclaimed && 
        current_time > invitation.expires_at
    }

    #[view]
    public fun get_stats(): (u64, u64, u64, u64, u64) acquires AdminConfig {
        let admin_config = borrow_global<AdminConfig>(@invite_send);
        (
            admin_config.total_invitations_created,
            admin_config.total_invitations_claimed,
            admin_config.total_invitations_reclaimed,
            admin_config.total_cusd_locked,
            admin_config.total_confio_locked
        )
    }
}