MEXICO_ECONOMIC_ACTIVITIES = {
    'Comercio al por menor de abarrotes y alimentos',
    'Comercio al por menor por internet',
    'Comercio al por mayor',
    'Servicios profesionales, científicos y técnicos',
    'Servicios de consultoría en administración',
    'Servicios de programación y desarrollo de software',
    'Servicios de diseño gráfico',
    'Servicios de publicidad y marketing',
    'Servicios de contabilidad y auditoría',
    'Servicios legales',
    'Servicios médicos y de salud',
    'Servicios educativos',
    'Restaurantes y servicios de preparación de alimentos',
    'Servicios de transporte de pasajeros',
    'Servicios de transporte de carga',
    'Construcción y trabajos especializados',
    'Servicios inmobiliarios y alquiler de inmuebles',
    'Servicios de reparación y mantenimiento',
    'Servicios personales',
    'Servicios de belleza y peluquería',
    'Agricultura, ganadería, pesca o actividades forestales',
    'Manufactura o elaboración de productos',
    'Actividades artísticas, deportivas o recreativas',
    'Empleado asalariado',
    'Jubilado o pensionado',
    'Estudiante sin actividad económica',
}

