# Curated SAT-style economic activity descriptions for Koywe compliance.
#
# Legacy labels are normalized into the current catalog before storage. Keep the
# mapping so users who saved older labels remain valid and converge to the new
# SAT-style options without being forced through a manual reselect.

LEGACY_MEXICO_ECONOMIC_ACTIVITY_MAP = {
    'Comercio al por menor de abarrotes y alimentos': 'Comercio al por menor de abarrotes, alimentos, bebidas, hielo y tabaco',
    'Comercio al por menor por internet': 'Comercio al por menor exclusivamente a través de Internet, y catálogos impresos, televisión y similares',
    'Comercio al por mayor': 'Comercio al por mayor de maquinaria, equipo y mobiliario',
    'Servicios profesionales, científicos y técnicos': 'Servicios de consultoría en administración',
    'Servicios de consultoría en administración': 'Servicios de consultoría en administración',
    'Servicios de programación y desarrollo de software': 'Servicios de consultoría en computación',
    'Servicios de diseño gráfico': 'Diseño gráfico',
    'Servicios de publicidad y marketing': 'Servicios de publicidad y actividades relacionadas',
    'Servicios de contabilidad y auditoría': 'Servicios de contabilidad, auditoría y servicios relacionados',
    'Servicios legales': 'Servicios legales',
    'Servicios médicos y de salud': 'Servicios médicos de consulta externa y servicios relacionados',
    'Servicios educativos': 'Servicios educativos',
    'Restaurantes y servicios de preparación de alimentos': 'Servicios de preparación de alimentos y bebidas',
    'Servicios de transporte de pasajeros': 'Transporte terrestre de pasajeros, excepto por ferrocarril',
    'Servicios de transporte de carga': 'Autotransporte de carga',
    'Construcción y trabajos especializados': 'Trabajos especializados para la construcción',
    'Servicios inmobiliarios y alquiler de inmuebles': 'Servicios inmobiliarios',
    'Servicios de reparación y mantenimiento': 'Reparación y mantenimiento de maquinaria y equipo',
    'Servicios personales': 'Servicios de apoyo a los negocios',
    'Servicios de belleza y peluquería': 'Salones y clínicas de belleza, baños públicos y bolerías',
    'Agricultura, ganadería, pesca o actividades forestales': 'Agricultura',
    'Manufactura o elaboración de productos': 'Industria alimentaria',
    'Actividades artísticas, deportivas o recreativas': 'Servicios artísticos, culturales y deportivos',
    'Empleado asalariado': 'Asalariados',
    'Jubilado o pensionado': 'Jubilados y pensionados',
    'Estudiante sin actividad económica': 'Sin actividad económica',
}

SAT_STYLE_MEXICO_ECONOMIC_ACTIVITIES = {
    'Agricultura',
    'Cría y explotación de animales',
    'Pesca',
    'Aprovechamiento forestal',
    'Minería',
    'Generación, transmisión y distribución de energía eléctrica',
    'Construcción de obras de edificación',
    'Construcción de obras de ingeniería civil',
    'Trabajos especializados para la construcción',
    'Industria alimentaria',
    'Industria de las bebidas y del tabaco',
    'Fabricación de productos textiles',
    'Fabricación de prendas de vestir',
    'Industria de la madera',
    'Industria del papel',
    'Impresión e industrias conexas',
    'Industria química',
    'Fabricación de productos de plástico y hule',
    'Fabricación de productos metálicos',
    'Fabricación de maquinaria y equipo',
    'Fabricación de equipo de computación, comunicación, medición y de otros equipos',
    'Fabricación de muebles, colchones y persianas',
    'Comercio al por mayor de abarrotes, alimentos, bebidas, hielo y tabaco',
    'Comercio al por mayor de productos textiles y calzado',
    'Comercio al por mayor de productos farmacéuticos, de perfumería y artículos para el esparcimiento',
    'Comercio al por mayor de materias primas agropecuarias y forestales',
    'Comercio al por mayor de maquinaria, equipo y mobiliario',
    'Comercio al por menor de abarrotes, alimentos, bebidas, hielo y tabaco',
    'Comercio al por menor en tiendas de autoservicio y departamentales',
    'Comercio al por menor de productos textiles, bisutería, accesorios de vestir y calzado',
    'Comercio al por menor de artículos para el cuidado de la salud',
    'Comercio al por menor de artículos de papelería, para el esparcimiento y otros artículos de uso personal',
    'Comercio al por menor de enseres domésticos, computadoras y artículos para la decoración de interiores',
    'Comercio al por menor de artículos de ferretería, tlapalería y vidrios',
    'Comercio al por menor de vehículos de motor, refacciones, combustibles y lubricantes',
    'Comercio al por menor exclusivamente a través de Internet, y catálogos impresos, televisión y similares',
    'Transporte aéreo',
    'Transporte por ferrocarril',
    'Autotransporte de carga',
    'Transporte terrestre de pasajeros, excepto por ferrocarril',
    'Servicios de mensajería y paquetería',
    'Servicios de almacenamiento',
    'Edición de periódicos, revistas, libros, software y otros materiales',
    'Industria fílmica y del video',
    'Industria del sonido',
    'Radio y televisión',
    'Telecomunicaciones',
    'Procesamiento electrónico de información, hospedaje y otros servicios relacionados',
    'Otros servicios de información',
    'Servicios financieros y de seguros',
    'Servicios inmobiliarios',
    'Servicios de alquiler de bienes muebles',
    'Servicios de alquiler de marcas registradas, patentes y franquicias',
    'Servicios legales',
    'Servicios de contabilidad, auditoría y servicios relacionados',
    'Servicios de arquitectura, ingeniería y actividades relacionadas',
    'Diseño gráfico',
    'Servicios de consultoría en computación',
    'Servicios de consultoría en administración',
    'Servicios de investigación científica y desarrollo',
    'Servicios de publicidad y actividades relacionadas',
    'Servicios de investigación de mercados y encuestas de opinión pública',
    'Servicios de fotografía y videograbación',
    'Servicios veterinarios',
    'Servicios de apoyo a los negocios',
    'Servicios de empleo',
    'Servicios de agencias de viajes y reservaciones',
    'Servicios de investigación, protección y seguridad',
    'Servicios de limpieza',
    'Servicios educativos',
    'Servicios médicos de consulta externa y servicios relacionados',
    'Hospitales',
    'Servicios de asistencia social',
    'Servicios artísticos, culturales y deportivos',
    'Museos, sitios históricos, zoológicos y similares',
    'Servicios de entretenimiento en instalaciones recreativas y otros servicios recreativos',
    'Servicios de alojamiento temporal',
    'Servicios de preparación de alimentos y bebidas',
    'Reparación y mantenimiento de automóviles y camiones',
    'Reparación y mantenimiento de equipo electrónico y de equipo de precisión',
    'Reparación y mantenimiento de maquinaria y equipo',
    'Salones y clínicas de belleza, baños públicos y bolerías',
    'Lavanderías y tintorerías',
    'Servicios funerarios y administración de cementerios',
    'Asalariados',
    'Jubilados y pensionados',
    'Sin actividad económica',
}

MEXICO_ECONOMIC_ACTIVITIES = SAT_STYLE_MEXICO_ECONOMIC_ACTIVITIES


def normalize_mexico_economic_activity(value: str) -> str:
    activity = str(value or '').strip()
    return LEGACY_MEXICO_ECONOMIC_ACTIVITY_MAP.get(activity, activity)
