# Generated by Django 5.2 on 2026-07-31 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanitarian', '0003_seed_venezuela_volunteer_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanitarianrelease',
            name='donation',
            field=models.OneToOneField(blank=True, help_text='Set for kind=reimbursement: the donation being refunded to its donor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reimbursement', to='humanitarian.humanitariandonation'),
        ),
        migrations.AddField(
            model_name='humanitarianrelease',
            name='kind',
            field=models.CharField(choices=[('volunteer', 'Volunteer aid'), ('reimbursement', 'Donor reimbursement')], db_index=True, default='volunteer', max_length=20),
        ),
        migrations.AlterField(
            model_name='humanitarianrelease',
            name='volunteer_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='humanitarian.humanitarianvolunteerapplication'),
        ),
    ]
