require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'
prepare_react_native_project!

target 'Confio' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])
end 