// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * Differential replay (2026-07-06): executes the op sequences frozen in
 * test/mirror/vectors.json — generated by the INDEPENDENT Python mirror of
 * the accrual/share math (test/mirror/mirror_accrual.py) — against the real
 * contract, asserting EXACT state equality after every step:
 * pPlus, lastOraclePrice, guard flag, totalSupply, vault USDY balance, and
 * every mint/redeem return value, to the wei.
 *
 * This is the rounding-direction net: an inequality-based invariant test
 * cannot see a floor that should be a ceil slowly leaking value; two
 * independently written implementations agreeing exactly across 400+ mixed
 * ops (including oracle-guard trips and resets) can.
 *
 * Regenerate vectors: python3 test/mirror/mirror_accrual.py
 */
import {Test} from "forge-std/Test.sol";
import {ERC1967Proxy} from "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
import {CusdPlusVault} from "../CusdPlusVault.sol";
import {MockToken, MockOracle, MockInstantManager} from "./CusdPlusVault.t.sol";

contract CusdPlusVaultDifferentialTest is Test {
    // Raw depositAndMint/redeem are owner-gated (PP representations), so
    // the replay drives them as the treasury — the share/accrual math the
    // mirror checks is caller-agnostic.
    address treasury = makeAddr("treasury");

    string json;

    function setUp() public {
        json = vm.readFile("test/mirror/vectors.json");
    }

    function _freshVault()
        internal
        returns (CusdPlusVault vault, MockToken usdy, MockOracle oracle)
    {
        MockToken usdt = new MockToken("USDT");
        usdy = new MockToken("USDY");
        oracle = new MockOracle();
        MockInstantManager im = new MockInstantManager(usdt, usdy, oracle);
        usdt.mint(address(im), 1e33);
        usdy.mint(address(im), 1e33);

        CusdPlusVault impl = new CusdPlusVault(
            address(usdy), address(usdt), address(im), address(oracle), 1500
        );
        ERC1967Proxy proxy = new ERC1967Proxy(
            address(impl), abi.encodeCall(CusdPlusVault.initialize, (treasury))
        );
        vault = CusdPlusVault(address(proxy));
        vm.prank(treasury);
        usdy.approve(address(vault), type(uint256).max);
    }

    function _replay(uint256 seq) internal {
        (CusdPlusVault vault, MockToken usdy, MockOracle oracle) = _freshVault();
        string memory base = string.concat(".sequences[", vm.toString(seq), "]");
        uint256 n = vm.parseJsonUint(json, string.concat(base, ".n"));

        for (uint256 i = 0; i < n; i++) {
            string memory k = string.concat(base, ".steps[", vm.toString(i), "]");
            string memory op = vm.parseJsonString(json, string.concat(k, ".op"));
            uint256 arg = vm.parseJsonUint(json, string.concat(k, ".arg"));
            bytes32 opH = keccak256(bytes(op));

            if (opH == keccak256("setPriceAccrue")) {
                oracle.setPrice(arg);
                vault.accrue();
            } else if (opH == keccak256("setPriceOnly")) {
                oracle.setPrice(arg);
            } else if (opH == keccak256("resetBaseline")) {
                vm.prank(treasury);
                vault.resetOracleBaseline();
            } else if (opH == keccak256("mint")) {
                usdy.mint(treasury, arg);
                vm.prank(treasury);
                uint256 shares = vault.depositAndMint(arg, treasury);
                assertEq(
                    shares,
                    vm.parseJsonUint(json, string.concat(k, ".ret")),
                    _at(seq, i, "sharesOut")
                );
            } else if (opH == keccak256("redeem")) {
                vm.prank(treasury);
                uint256 usdyOut = vault.redeem(arg);
                assertEq(
                    usdyOut,
                    vm.parseJsonUint(json, string.concat(k, ".ret")),
                    _at(seq, i, "usdyOut")
                );
            } else if (opH == keccak256("collect")) {
                vm.prank(treasury);
                vault.collectFees(arg);
            } else {
                revert(string.concat("unknown op: ", op));
            }

            // Exact state equality after EVERY step.
            assertEq(
                vault.pPlus(),
                vm.parseJsonUint(json, string.concat(k, ".pPlus")),
                _at(seq, i, "pPlus")
            );
            assertEq(
                vault.lastOraclePrice(),
                vm.parseJsonUint(json, string.concat(k, ".lastOraclePrice")),
                _at(seq, i, "lastOraclePrice")
            );
            assertEq(
                vault.oracleGuardTripped(),
                vm.parseJsonBool(json, string.concat(k, ".tripped")),
                _at(seq, i, "tripped")
            );
            assertEq(
                vault.totalSupply(),
                vm.parseJsonUint(json, string.concat(k, ".totalSupply")),
                _at(seq, i, "totalSupply")
            );
            assertEq(
                usdy.balanceOf(address(vault)),
                vm.parseJsonUint(json, string.concat(k, ".vaultUsdy")),
                _at(seq, i, "vaultUsdy")
            );
        }
    }

    function _at(uint256 seq, uint256 step, string memory what)
        internal
        pure
        returns (string memory)
    {
        return string.concat(
            "mirror mismatch: seq ", vm.toString(seq),
            " step ", vm.toString(step), " ", what
        );
    }

    function test_differential_sequence0() public { _replay(0); }
    function test_differential_sequence1() public { _replay(1); }
    function test_differential_sequence2() public { _replay(2); }
}
