# Generated by Django 4.2.20 on 2025-07-29 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDeviceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, help_text='First time this IP-Device-User combination was seen')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, help_text='Last activity from this combination')),
                ('total_sessions', models.IntegerField(default=1, help_text='Total sessions from this combination')),
                ('location_info', models.JSONField(blank=True, default=dict, help_text='Location data: city, region, coordinates, etc.')),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flagged as suspicious combination')),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='List of risk factors: rapid_location_change, multiple_users_same_ip, etc.')),
                ('auth_method', models.CharField(blank=True, help_text='How user authenticated: google, apple, etc.', max_length=50)),
                ('device_fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_user_associations', to='security.devicefingerprint')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_user_associations', to='security.ipaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_device_associations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP-Device-User Association',
                'verbose_name_plural': 'IP-Device-User Associations',
                'indexes': [models.Index(fields=['user', 'last_seen'], name='security_ip_user_id_925dfc_idx'), models.Index(fields=['device_fingerprint', 'last_seen'], name='security_ip_device__f5d67e_idx'), models.Index(fields=['ip_address', 'last_seen'], name='security_ip_ip_addr_f5ede0_idx'), models.Index(fields=['is_suspicious'], name='security_ip_is_susp_95ee35_idx'), models.Index(fields=['first_seen', 'last_seen'], name='security_ip_first_s_88d771_idx')],
                'unique_together': {('ip_address', 'device_fingerprint', 'user')},
            },
        ),
    ]
