# Generated by Django 5.2 on 2025-09-02 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amlcheck',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aml_checks_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amlcheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='user',
            field=models.ForeignKey(help_text='User being verified', on_delete=django.db.models.deletion.CASCADE, related_name='security_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who approved the verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_verifications_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips_blocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipdeviceuser',
            name='device_fingerprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_user_associations', to='security.devicefingerprint'),
        ),
        migrations.AddField(
            model_name='ipdeviceuser',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_user_associations', to='security.ipaddress'),
        ),
        migrations.AddField(
            model_name='ipdeviceuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_device_associations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='investigated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_investigated_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='related_users',
            field=models.ManyToManyField(blank=True, help_text='Other users potentially involved', related_name='related_suspicious_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_suspicious_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userban',
            name='appeal_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ban_appeals_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userban',
            name='banned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userban',
            name='suspicious_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_bans', to='security.suspiciousactivity'),
        ),
        migrations.AddField(
            model_name='userban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.devicefingerprint'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicefingerprint',
            name='users',
            field=models.ManyToManyField(related_name='device_fingerprints', through='security.UserDevice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='ip_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='security.ipaddress'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='amlcheck',
            index=models.Index(fields=['user', 'status'], name='security_am_user_id_a05674_idx'),
        ),
        migrations.AddIndex(
            model_name='amlcheck',
            index=models.Index(fields=['risk_score', 'status'], name='security_am_risk_sc_0989af_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['country_code'], name='security_ip_country_48b11c_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['is_vpn', 'is_tor', 'is_datacenter'], name='security_ip_is_vpn_cb6b77_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['risk_score'], name='security_ip_risk_sc_e01b58_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdeviceuser',
            index=models.Index(fields=['user', 'last_seen'], name='security_ip_user_id_925dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdeviceuser',
            index=models.Index(fields=['device_fingerprint', 'last_seen'], name='security_ip_device__f5d67e_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdeviceuser',
            index=models.Index(fields=['ip_address', 'last_seen'], name='security_ip_ip_addr_f5ede0_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdeviceuser',
            index=models.Index(fields=['is_suspicious'], name='security_ip_is_susp_95ee35_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdeviceuser',
            index=models.Index(fields=['first_seen', 'last_seen'], name='security_ip_first_s_88d771_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ipdeviceuser',
            unique_together={('ip_address', 'device_fingerprint', 'user')},
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['user', 'activity_type', 'status'], name='security_su_user_id_924d34_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['severity_score', 'status'], name='security_su_severit_cd0dde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user', 'device')},
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['risk_score'], name='security_de_risk_sc_6f4955_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['total_users'], name='security_de_total_u_28ae30_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'started_at'], name='security_us_user_id_78e6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['device_fingerprint'], name='security_us_device__92765c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_suspicious'], name='security_us_is_susp_549551_idx'),
        ),
    ]
