# Generated by Django 5.2 on 2025-12-20 10:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_unique_personal_verified_doc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(blank=True, help_text='Device fingerprint hash at time of check', max_length=255)),
                ('app_recognition', models.CharField(choices=[('PLAY_RECOGNIZED', 'Play Recognized'), ('UNRECOGNIZED_VERSION', 'Unrecognized Version'), ('UNEVALUATED', 'Unevaluated')], default='UNEVALUATED', help_text='Whether app is recognized by Play Store', max_length=50)),
                ('device_integrity', models.JSONField(default=list, help_text='Device integrity labels: MEETS_DEVICE_INTEGRITY, MEETS_BASIC_INTEGRITY, etc.')),
                ('app_licensing', models.CharField(choices=[('LICENSED', 'Licensed'), ('UNLICENSED', 'Unlicensed'), ('UNEVALUATED', 'Unevaluated')], default='UNEVALUATED', help_text='Whether app is licensed from Play Store', max_length=50)),
                ('is_emulator', models.BooleanField(default=False, help_text='No device integrity = likely emulator')),
                ('is_rooted', models.BooleanField(default=False, help_text='Only MEETS_BASIC_INTEGRITY = likely rooted')),
                ('passed', models.BooleanField(default=False, help_text='Did this check pass our requirements?')),
                ('trigger_action', models.CharField(choices=[('signup', 'Signup'), ('reward_claim', 'Reward Claim'), ('transfer', 'Transfer/Withdrawal'), ('login', 'Login')], help_text='What action triggered this check', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Raw decoded response from Google (for debugging)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if verification failed')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(help_text='User being verified', on_delete=django.db.models.deletion.CASCADE, related_name='integrity_verdicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integrity Verdict',
                'verbose_name_plural': 'Integrity Verdicts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'passed'], name='security_in_user_id_7a964b_idx'), models.Index(fields=['user', 'trigger_action', 'created_at'], name='security_in_user_id_cadc1b_idx'), models.Index(fields=['is_emulator'], name='security_in_is_emul_3ab54a_idx'), models.Index(fields=['is_rooted'], name='security_in_is_root_f6ed90_idx')],
            },
        ),
    ]
