# Generated by Django 5.2 on 2025-12-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_add_integrity_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrityverdict',
            name='trigger_action',
            field=models.CharField(choices=[('signup', 'Signup'), ('reward_claim', 'Reward Claim'), ('transfer', 'Transfer/Withdrawal'), ('login', 'Login'), ('payroll', 'Payroll')], help_text='What action triggered this check', max_length=20),
        ),
    ]
