# Generated by Django 5.2 on 2026-09-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_identityverification_is_additional_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdeviceuser',
            name='daily_sessions',
            field=models.JSONField(blank=True, default=dict, help_text='Sessions per UTC day (YYYY-MM-DD -> count), last 120 days: residence counts recent sessions'),
        ),
    ]
