# Generated by Django 5.2 on 2026-09-29 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_ipdeviceuser_daily_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_references', to='security.identityverification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_references', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FaceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('on_ramp', 'Deposit order'), ('withdrawal', 'Withdrawal'), ('emergency_exit', 'Emergency exit')], max_length=20)),
                ('liveness_session_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('passed', 'Passed'), ('failed', 'Failed')], default='created', max_length=10)),
                ('liveness_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('similarity', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_by', models.CharField(blank=True, max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_checks', to=settings.AUTH_USER_MODEL)),
                ('face_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.facereference')),
            ],
        ),
        migrations.AddIndex(
            model_name='facereference',
            index=models.Index(fields=['user', 'is_active'], name='security_fa_user_id_368ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='facecheck',
            index=models.Index(fields=['user', 'status', 'completed_at'], name='security_fa_user_id_00efc0_idx'),
        ),
    ]
