# Generated by Django 5.2 on 2026-09-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_face_reference_one_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecheck',
            name='purpose',
            field=models.CharField(choices=[('on_ramp', 'Deposit order'), ('withdrawal', 'Withdrawal'), ('emergency_exit', 'Emergency exit'), ('payin_release', 'Receive held pay-in')], max_length=20),
        ),
    ]
