# Generated by Django 5.2 on 2026-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_face_app_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='facecheck',
            name='evidence_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facecheck',
            name='evidence_purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
