# Generated by Django 5.2 on 2026-10-01 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0021_userban_phone_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='integrityverdict',
            index=models.Index(fields=['device_fingerprint', 'passed'], name='security_in_device__30cfd8_idx'),
        ),
    ]
