"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import logging
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&(hehrlb0sqdkf8awe$55l!k9k)u_6a-5wn1ro))s(prkri2_t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

if DEBUG:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
else:
    ALLOWED_HOSTS = ['.confio.me', '194.182.166.232', '194.182.166.225', '10.0.0.1', '10.0.0.2']


# Application definition

INSTALLED_APPS = [
    'graphene_django',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
]

if DEBUG:
    INSTALLED_APPS += ['corsheaders']

GRAPHENE = {
    'SCHEMA': 'config.schema.schema',
}

ASGI_APPLICATION = "config.asgi.application"

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

SESSION_COOKIE_SECURE = not DEBUG
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 60,  # in seconds
        }
    }
}

CHANNEL_LAYERS = {
    'default': {
        #'BACKEND': 'channels.layers.InMemoryChannelLayer',
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('localhost', 6379)],
            'capacity': 10000000,
        },
    },
}

CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'


MIDDLEWARE = []
if DEBUG:
    MIDDLEWARE += ['corsheaders.middleware.CorsMiddleware']
MIDDLEWARE += [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

if DEBUG:
    from corsheaders.defaults import default_headers
    CORS_ORIGIN_ALLOW_ALL = True
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_HEADERS = list(default_headers) + ['xsrfheadername', 'xsrfcookiename']

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['web/build'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'duende',
        'USER': 'julian',
    }
}
if DEBUG:
    DATABASES['default']['USER'] = 'postgres'
    DATABASES['default']['PASSWORD'] = '12345678'
    DATABASES['default']['HOST'] = 'localhost'
    DATABASES['default']['PORT'] = ''

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.elasticemail.com'
EMAIL_HOST_USER = 'julian@duende.me'
EMAIL_HOST_PASSWORD = '5A37734AC679F5B525C266BCCDF6EBC0285C'
DEFAULT_FROM_EMAIL = 'Duende <support@duende.me>'
EMAIL_PORT = 587

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

LEAFLET_CONFIG = {
    'DEFAULT_ZOOM': 3,
    'MAX_ZOOM': 20,
    'MIN_ZOOM': 2,
}

STATIC_URL = '/static/'

EXOSCALE_ACCESS_KEY_ID = 'EXO53716446d63d880bf0980088'
EXOSCALE_SECRET_KEY = 'AaKrbeLtx7PxfKdwUvf6VdVuJMJ_xFyHfztGdE0GPs0'
SOS_ENDPOINT = 'sos-ch-dk-2.exo.io'
SOS_BUCKET_TEST = 'duende-test-image'
SOS_BUCKET_USER = 'duende-user-image' if not DEBUG else SOS_BUCKET_TEST
SOS_BUCKET_BUSINESS_VERIFICATION = 'duende-business-verification-image' if not DEBUG else SOS_BUCKET_TEST
SOS_BUCKET_USER_VERIFICATION = 'duende-user-verification-image' if not DEBUG else SOS_BUCKET_TEST

NODE_API_KEY = 'NODEKLSDF%^$540HR*%&%^#SGUBSEBtyg45$#^dtvtes*(!)'
NODE_SECRET_KEY = 'NODElso-4k09g954ktJU@#$dfhrf9JD)DKFKDJFOK))099sfief'

if DEBUG:
    STATICFILES_DIRS = (#Development Mode
        'static',
    )

else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'web/build/static')
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file': {
                'level': 'INFO',
                'filters': None,
                'class': 'logging.FileHandler',
                'filename': os.path.join(BASE_DIR, 'logs/')
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'INFO',
            },
        },
    }

if os.name == 'nt':
    VENV_BASE = os.environ['VIRTUAL_ENV']
    os.environ['PATH'] = os.path.join(VENV_BASE, 'Lib\\site-packages\\osgeo') + ';' + os.environ['PATH']
    os.environ['PROJ_LIB'] = os.path.join(VENV_BASE, 'Lib\\site-packages\\osgeo\\data\\proj') + ';' + os.environ['PATH']