from django.urls import path

from .views import (
    ApplicationListView,
    ApplicationDetailView,
    EventDetailView,
    EventListView,
    ObligationDetailView,
    ObligationListCreateView,
    SubjectDetailView,
    SubjectListCreateView,
    PaymentDetailView,
    PaymentListView,
    SettlementListView,
    WebhookDeliveryReplayView,
    WebhookDeliveryDetailView,
    WebhookDeliveryListView,
    WebhookEndpointDetailView,
    WebhookEndpointListCreateView,
    WebhookEndpointRotateSecretView,
    WebhookEndpointTestView,
)
from billing.sandbox_views import cip_sandbox_apply, cip_sandbox_verify


urlpatterns = [
    path('sandbox/cip/verify', cip_sandbox_verify, name='cip_sandbox_verify'),
    path('sandbox/cip/payments/apply', cip_sandbox_apply, name='cip_sandbox_apply'),
    path('subjects', SubjectListCreateView.as_view(), name='billing_subjects'),
    path('subjects/<str:public_id>', SubjectDetailView.as_view(),
         name='billing_subject_detail'),
    path('obligations', ObligationListCreateView.as_view(),
         name='billing_obligations'),
    path('obligations/<str:public_id>', ObligationDetailView.as_view(),
         name='billing_obligation_detail'),
    path('payments', PaymentListView.as_view(), name='billing_payments'),
    path('payments/<str:public_id>', PaymentDetailView.as_view(), name='billing_payment_detail'),
    path('settlements', SettlementListView.as_view(), name='billing_settlements'),
    path('applications', ApplicationListView.as_view(), name='billing_applications'),
    path('applications/<str:public_id>', ApplicationDetailView.as_view(),
         name='billing_application_detail'),
    path('events', EventListView.as_view(), name='billing_events'),
    path('events/<str:public_id>', EventDetailView.as_view(), name='billing_event_detail'),
    path('webhook_endpoints', WebhookEndpointListCreateView.as_view(),
         name='billing_webhook_endpoints'),
    path('webhook_endpoints/<str:public_id>', WebhookEndpointDetailView.as_view(),
         name='billing_webhook_endpoint_detail'),
    path('webhook_endpoints/<str:public_id>/rotate_secret',
         WebhookEndpointRotateSecretView.as_view(), name='billing_webhook_rotate'),
    path('webhook_endpoints/<str:public_id>/test', WebhookEndpointTestView.as_view(),
         name='billing_webhook_test'),
    path('webhook_deliveries', WebhookDeliveryListView.as_view(),
         name='billing_webhook_deliveries'),
    path('webhook_deliveries/<str:public_id>', WebhookDeliveryDetailView.as_view(),
         name='billing_webhook_delivery_detail'),
    path('webhook_deliveries/<str:public_id>/replay', WebhookDeliveryReplayView.as_view(),
         name='billing_webhook_delivery_replay'),
]
