# Generated by Django 4.2.20 on 2025-07-27 10:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0022_fix_system_counterparty_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USDCWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], help_text='Type of actor (user or business)', max_length=10)),
                ('actor_display_name', models.CharField(blank=True, help_text='Display name of the actor at withdrawal time', max_length=255)),
                ('actor_address', models.CharField(blank=True, help_text='Confío wallet address making the withdrawal', max_length=66)),
                ('amount', models.DecimalField(decimal_places=6, help_text='Amount of USDC withdrawn', max_digits=19)),
                ('destination_address', models.CharField(help_text='External wallet address receiving the USDC', max_length=66)),
                ('network', models.CharField(default='SUI', help_text='Blockchain network used', max_length=20)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66, null=True)),
                ('block_number', models.BigIntegerField(blank=True, help_text='Block number where transaction was confirmed', null=True)),
                ('network_fee', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Network transaction fee', max_digits=19)),
                ('service_fee', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Confío service fee', max_digits=19)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('actor_business', models.ForeignKey(blank=True, help_text='Business that made the withdrawal (if business account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_usdc_withdrawals', to='users.business')),
                ('actor_user', models.ForeignKey(blank=True, help_text='User who made the withdrawal (if personal account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_usdc_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usdc_withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_user', 'status'], name='usdc_w_actor_user_status_idx'), models.Index(fields=['actor_business', 'status'], name='usdc_w_actor_bus_status_idx'), models.Index(fields=['actor_type', 'status'], name='usdc_w_actor_type_status_idx'), models.Index(fields=['withdrawal_id'], name='usdc_withdr_withdra_226ec0_idx'), models.Index(fields=['created_at'], name='usdc_withdr_created_42cc94_idx'), models.Index(fields=['transaction_hash'], name='usdc_withdr_transac_c84366_idx')],
            },
        ),
        migrations.CreateModel(
            name='USDCDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], help_text='Type of actor (user or business)', max_length=10)),
                ('actor_display_name', models.CharField(blank=True, help_text='Display name of the actor at deposit time', max_length=255)),
                ('actor_address', models.CharField(blank=True, help_text='Confío wallet address receiving the deposit', max_length=66)),
                ('amount', models.DecimalField(decimal_places=6, help_text='Amount of USDC deposited', max_digits=19)),
                ('source_address', models.CharField(help_text='External wallet address that sent the USDC', max_length=66)),
                ('network', models.CharField(default='SUI', help_text='Blockchain network used', max_length=20)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66, null=True)),
                ('block_number', models.BigIntegerField(blank=True, help_text='Block number where transaction was confirmed', null=True)),
                ('network_fee', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Network transaction fee', max_digits=19)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('actor_business', models.ForeignKey(blank=True, help_text='Business that made the deposit (if business account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_usdc_deposits', to='users.business')),
                ('actor_user', models.ForeignKey(blank=True, help_text='User who made the deposit (if personal account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_usdc_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usdc_deposits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_user', 'status'], name='usdc_dep_actor_user_status_idx'), models.Index(fields=['actor_business', 'status'], name='usdc_dep_actor_bus_status_idx'), models.Index(fields=['actor_type', 'status'], name='usdc_dep_actor_type_status_idx'), models.Index(fields=['deposit_id'], name='usdc_deposi_deposit_d05aca_idx'), models.Index(fields=['created_at'], name='usdc_deposi_created_c60b70_idx'), models.Index(fields=['transaction_hash'], name='usdc_deposi_transac_8d97db_idx')],
            },
        ),
    ]
