# Generated by Django 5.2 on 2025-09-02 02:45

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedUSDCTransactionTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(help_text='UUID of the source transaction', unique=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('conversion', 'Conversion')], db_index=True, max_length=20)),
                ('actor_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], max_length=10)),
                ('actor_display_name', models.CharField(blank=True, max_length=255)),
                ('actor_address', models.CharField(blank=True, max_length=66)),
                ('amount', models.DecimalField(decimal_places=6, help_text='Primary amount (USDC for deposits/withdrawals, source amount for conversions)', max_digits=19)),
                ('currency', models.CharField(default='USDC', help_text='Primary currency', max_length=10)),
                ('secondary_amount', models.DecimalField(blank=True, decimal_places=6, help_text='Converted amount for conversions', max_digits=19, null=True)),
                ('secondary_currency', models.CharField(blank=True, help_text='Converted currency for conversions', max_length=10)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('network_fee', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('service_fee', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('source_address', models.CharField(blank=True, help_text='Source address (for deposits and conversions)', max_length=66)),
                ('destination_address', models.CharField(blank=True, help_text='Destination address (for withdrawals and conversions)', max_length=66)),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('network', models.CharField(default='ALGORAND', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_SIG', 'Pending Signature'), ('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(help_text='When the transaction was created')),
                ('transaction_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unified_usdc_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='USDCDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], help_text='Type of actor (user or business)', max_length=10)),
                ('actor_display_name', models.CharField(blank=True, help_text='Display name of the actor at deposit time', max_length=255)),
                ('actor_address', models.CharField(blank=True, help_text='Confío wallet address receiving the deposit', max_length=66)),
                ('amount', models.DecimalField(decimal_places=6, help_text='Amount of USDC deposited', max_digits=19)),
                ('source_address', models.CharField(help_text='External wallet address that sent the USDC', max_length=66)),
                ('network', models.CharField(default='ALGORAND', help_text='Blockchain network used', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'USDC Deposit',
                'verbose_name_plural': 'USDC Deposits',
                'db_table': 'usdc_deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='USDCWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], help_text='Type of actor (user or business)', max_length=10)),
                ('actor_display_name', models.CharField(blank=True, help_text='Display name of the actor at withdrawal time', max_length=255)),
                ('actor_address', models.CharField(blank=True, help_text='Confío wallet address making the withdrawal', max_length=66)),
                ('amount', models.DecimalField(decimal_places=6, help_text='Amount of USDC withdrawn', max_digits=19)),
                ('destination_address', models.CharField(help_text='External wallet address receiving the USDC', max_length=66)),
                ('network', models.CharField(default='ALGORAND', help_text='Blockchain network used', max_length=20)),
                ('service_fee', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Confío service fee', max_digits=19)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'USDC Withdrawal',
                'verbose_name_plural': 'USDC Withdrawals',
                'db_table': 'usdc_withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
