# Generated by Django 5.2 on 2025-09-02 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversion', '0002_initial'),
        ('usdc_transactions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedusdctransactiontable',
            name='actor_business',
            field=models.ForeignKey(blank=True, help_text='Business associated with the transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_usdc_table_transactions', to='users.business'),
        ),
        migrations.AddField(
            model_name='unifiedusdctransactiontable',
            name='actor_user',
            field=models.ForeignKey(blank=True, help_text='User associated with the transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_usdc_table_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unifiedusdctransactiontable',
            name='conversion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_usdc_transaction', to='conversion.conversion'),
        ),
        migrations.AddField(
            model_name='usdcdeposit',
            name='actor_business',
            field=models.ForeignKey(blank=True, help_text='Business that made the deposit (if business account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_usdc_deposits', to='users.business'),
        ),
        migrations.AddField(
            model_name='usdcdeposit',
            name='actor_user',
            field=models.ForeignKey(blank=True, help_text='User who made the deposit (if personal account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_usdc_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unifiedusdctransactiontable',
            name='usdc_deposit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_transaction', to='usdc_transactions.usdcdeposit'),
        ),
        migrations.AddField(
            model_name='usdcwithdrawal',
            name='actor_business',
            field=models.ForeignKey(blank=True, help_text='Business that made the withdrawal (if business account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_usdc_withdrawals', to='users.business'),
        ),
        migrations.AddField(
            model_name='usdcwithdrawal',
            name='actor_user',
            field=models.ForeignKey(blank=True, help_text='User who made the withdrawal (if personal account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_usdc_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unifiedusdctransactiontable',
            name='usdc_withdrawal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_transaction', to='usdc_transactions.usdcwithdrawal'),
        ),
        migrations.AddIndex(
            model_name='usdcdeposit',
            index=models.Index(fields=['actor_user', 'status'], name='usdc_dep_actor_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usdcdeposit',
            index=models.Index(fields=['actor_business', 'status'], name='usdc_dep_actor_bus_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usdcdeposit',
            index=models.Index(fields=['actor_type', 'status'], name='usdc_dep_actor_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usdcdeposit',
            index=models.Index(fields=['deposit_id'], name='usdc_deposi_deposit_d05aca_idx'),
        ),
        migrations.AddIndex(
            model_name='usdcdeposit',
            index=models.Index(fields=['created_at'], name='usdc_deposi_created_c60b70_idx'),
        ),
        migrations.AddIndex(
            model_name='usdcwithdrawal',
            index=models.Index(fields=['actor_user', 'status'], name='usdc_w_actor_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usdcwithdrawal',
            index=models.Index(fields=['actor_business', 'status'], name='usdc_w_actor_bus_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usdcwithdrawal',
            index=models.Index(fields=['actor_type', 'status'], name='usdc_w_actor_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usdcwithdrawal',
            index=models.Index(fields=['withdrawal_id'], name='usdc_withdr_withdra_226ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='usdcwithdrawal',
            index=models.Index(fields=['created_at'], name='usdc_withdr_created_42cc94_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedusdctransactiontable',
            index=models.Index(fields=['-created_at'], name='unified_usd_created_090a62_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedusdctransactiontable',
            index=models.Index(fields=['transaction_type', '-created_at'], name='unified_usd_transac_165ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedusdctransactiontable',
            index=models.Index(fields=['actor_user', '-created_at'], name='unified_usd_actor_u_b20951_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedusdctransactiontable',
            index=models.Index(fields=['actor_business', '-created_at'], name='unified_usd_actor_b_34bde1_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedusdctransactiontable',
            index=models.Index(fields=['status', '-created_at'], name='unified_usd_status_2bd9a9_idx'),
        ),
    ]
