# Generated by Django 5.2 on 2025-12-16 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdc_transactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardarianTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardarian_id', models.CharField(help_text='Guardarian Transaction ID', max_length=100, unique=True)),
                ('external_id', models.CharField(blank=True, help_text='Our generic external tracking ID', max_length=100, null=True)),
                ('from_currency', models.CharField(help_text='Fiat currency (e.g., USD, EUR)', max_length=20)),
                ('from_amount', models.DecimalField(decimal_places=6, help_text='Fiat amount sent', max_digits=19)),
                ('to_currency', models.CharField(default='USDC', help_text='Crypto currency received', max_length=20)),
                ('to_amount_estimated', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated crypto amount', max_digits=19, null=True)),
                ('to_amount_actual', models.DecimalField(blank=True, decimal_places=6, help_text='Actual crypto amount received', max_digits=19, null=True)),
                ('network', models.CharField(default='ALGO', help_text='Network (ALGO)', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('exchanging', 'Exchanging'), ('sending', 'Sending'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('hold', 'Hold'), ('expired', 'Expired')], default='waiting', max_length=20)),
                ('status_details', models.TextField(blank=True, help_text='Additional status info or error message', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onchain_deposit', models.OneToOneField(blank=True, help_text='Matched on-chain deposit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardarian_source', to='usdc_transactions.usdcdeposit')),
                ('user', models.ForeignKey(help_text='User who initiated the top-up', on_delete=django.db.models.deletion.CASCADE, related_name='guardarian_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardarian Transaction',
                'verbose_name_plural': 'Guardarian Transactions',
                'db_table': 'guardarian_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='guardarian__user_id_45197f_idx'), models.Index(fields=['guardarian_id'], name='guardarian__guardar_6fbc83_idx'), models.Index(fields=['external_id'], name='guardarian__externa_b97d04_idx'), models.Index(fields=['created_at'], name='guardarian__created_bf5019_idx')],
            },
        ),
    ]
