# Generated by Django 5.2 on 2025-12-17 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdc_transactions', '0003_guardariantransaction'),
        ('users', '0013_user_platform_os'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usdcdeposit',
            name='usdc_deposi_deposit_d05aca_idx',
        ),
        migrations.RemoveIndex(
            model_name='usdcwithdrawal',
            name='usdc_withdr_withdra_226ec0_idx',
        ),
        migrations.RenameField(
            model_name='usdcdeposit',
            old_name='deposit_id',
            new_name='internal_id',
        ),
        migrations.RenameField(
            model_name='usdcwithdrawal',
            old_name='withdrawal_id',
            new_name='internal_id',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='guardariantransaction',
                    name='onchain_withdrawal',
                    field=models.OneToOneField(blank=True, help_text='Matched on-chain withdrawal (Sell)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardarian_dest', to='usdc_transactions.usdcwithdrawal'),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='guardariantransaction',
            name='onchain_deposit',
            field=models.OneToOneField(blank=True, help_text='Matched on-chain deposit (Buy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardarian_source', to='usdc_transactions.usdcdeposit'),
        ),
        migrations.AlterField(
            model_name='guardariantransaction',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('waiting_for_customer', 'Waiting for Customer'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('exchanging', 'Exchanging'), ('sending', 'Sending'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('hold', 'Hold'), ('expired', 'Expired')], default='waiting', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usdcdeposit',
            index=models.Index(fields=['internal_id'], name='usdc_deposi_interna_9bf664_idx'),
        ),
        migrations.AddIndex(
            model_name='usdcwithdrawal',
            index=models.Index(fields=['internal_id'], name='usdc_withdr_interna_38aa2e_idx'),
        ),
    ]
