# Generated by Django 4.2.20 on 2025-07-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usdc_transactions', '0005_update_unified_view_remove_blockchain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usdcdeposit',
            options={'ordering': ['-created_at'], 'verbose_name': 'USDC Deposit', 'verbose_name_plural': 'USDC Deposits'},
        ),
        migrations.AlterModelOptions(
            name='usdcwithdrawal',
            options={'ordering': ['-created_at'], 'verbose_name': 'USDC Withdrawal', 'verbose_name_plural': 'USDC Withdrawals'},
        ),
        migrations.RemoveIndex(
            model_name='usdcdeposit',
            name='usdc_deposi_transac_8d97db_idx',
        ),
        migrations.RemoveIndex(
            model_name='usdcwithdrawal',
            name='usdc_withdr_transac_c84366_idx',
        ),
    ]
