# Generated by Django 4.2.20 on 2025-07-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usdc_transactions', '0005_update_unified_view_remove_blockchain'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP VIEW IF EXISTS unified_usdc_transactions;",
            reverse_sql="-- View will be recreated by reversing other migrations"
        ),
    ]