# Generated by Django 5.2 on 2026-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdc_transactions', '0005_alter_guardariantransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardariantransaction',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('waiting_for_deposit', 'Waiting for Deposit'), ('waiting_for_customer', 'Waiting for Customer'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('exchanging', 'Exchanging'), ('sending', 'Sending'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('hold', 'Hold'), ('expired', 'Expired')], default='waiting', max_length=20),
        ),
    ]
