# Generated by Django 5.2 on 2026-08-01 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdc_transactions', '0006_alter_guardariantransaction_status'),
        ('users', '0029_unifiedtransactiontable_cusd_plus_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardariantransaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account context that created the order (authorization scope)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardarian_transactions', to='users.account'),
        ),
    ]
