# Generated by Django 4.2.20 on 2025-07-27 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_create_unified_transaction_table'),
        ('conversion', '0005_create_unified_transaction_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usdc_transactions', '0007_alter_usdcdeposit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedUSDCTransactionTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(help_text='UUID of the source transaction', unique=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('conversion', 'Conversion')], db_index=True, max_length=20)),
                ('actor_type', models.CharField(choices=[('user', 'Personal'), ('business', 'Business')], max_length=10)),
                ('actor_display_name', models.CharField(blank=True, max_length=255)),
                ('actor_address', models.CharField(blank=True, max_length=66)),
                ('amount', models.DecimalField(decimal_places=6, help_text='Primary amount (USDC for deposits/withdrawals, source amount for conversions)', max_digits=19)),
                ('currency', models.CharField(default='USDC', help_text='Primary currency', max_length=10)),
                ('secondary_amount', models.DecimalField(blank=True, decimal_places=6, help_text='Converted amount for conversions', max_digits=19, null=True)),
                ('secondary_currency', models.CharField(blank=True, help_text='Converted currency for conversions', max_length=10)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('network_fee', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('service_fee', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('source_address', models.CharField(blank=True, help_text='Source address (for deposits and conversions)', max_length=66)),
                ('destination_address', models.CharField(blank=True, help_text='Destination address (for withdrawals and conversions)', max_length=66)),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('network', models.CharField(default='SUI', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actor_business', models.ForeignKey(blank=True, help_text='Business associated with the transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_usdc_table_transactions', to='users.business')),
                ('actor_user', models.ForeignKey(blank=True, help_text='User associated with the transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_usdc_table_transactions', to=settings.AUTH_USER_MODEL)),
                ('conversion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_usdc_transaction', to='conversion.conversion')),
                ('usdc_deposit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_transaction', to='usdc_transactions.usdcdeposit')),
                ('usdc_withdrawal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_transaction', to='usdc_transactions.usdcwithdrawal')),
            ],
            options={
                'db_table': 'unified_usdc_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='unified_usd_created_090a62_idx'), models.Index(fields=['transaction_type', '-created_at'], name='unified_usd_transac_165ef4_idx'), models.Index(fields=['actor_user', '-created_at'], name='unified_usd_actor_u_b20951_idx'), models.Index(fields=['actor_business', '-created_at'], name='unified_usd_actor_b_34bde1_idx'), models.Index(fields=['status', '-created_at'], name='unified_usd_status_2bd9a9_idx')],
            },
        ),
    ]
