# Generated by Codex on 2025-08-24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdc_transactions', '0008_create_unified_usdc_transaction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedusdctransactiontable',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('PENDING_SIG', 'Pending Signature'),
                    ('SUBMITTED', 'Submitted'),
                    ('PROCESSING', 'Processing'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                ],
                max_length=20,
                db_index=True,
            ),
        ),
    ]

