# Generated by Django 5.2 on 2025-08-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdc_transactions', '0009_fix_created_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedusdctransactiontable',
            name='network',
            field=models.CharField(default='ALGORAND', max_length=20),
        ),
        migrations.AlterField(
            model_name='usdcdeposit',
            name='network',
            field=models.CharField(default='ALGORAND', help_text='Blockchain network used', max_length=20),
        ),
        migrations.AlterField(
            model_name='usdcwithdrawal',
            name='network',
            field=models.CharField(default='ALGORAND', help_text='Blockchain network used', max_length=20),
        ),
    ]
