# Generated by Django 5.2 on 2025-08-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usdc_transactions', '0009_add_submitted_status_unified'),
        ('usdc_transactions', '0010_alter_unifiedusdctransactiontable_network_and_more'),
    ]

    operations = [
    ]
