# Generated by Django 5.2 on 2025-11-22 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollrecipient'),
        ('users', '0005_employee_invitation_username_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payrollitem',
            new_name='payroll_pay_item_id_ebac96_idx',
            old_name='payrollitem_item_id_e5e3f2_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollitem',
            new_name='payroll_pay_run_id_acf009_idx',
            old_name='payrollitem_run_id_dac8f4_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollitem',
            new_name='payroll_pay_recipie_2477a7_idx',
            old_name='payrollitem_recipient_302316_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollitem',
            new_name='payroll_pay_recipie_932a20_idx',
            old_name='payrollitem_recipient_1014f6_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollrecipient',
            new_name='payroll_pay_busines_d4d658_idx',
            old_name='payrollrecipient_business_recipient_user_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollrecipient',
            new_name='payroll_pay_busines_bf961a_idx',
            old_name='payrollrecipient_business_recipient_account_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollrun',
            new_name='payroll_pay_run_id_5a6a31_idx',
            old_name='payrollrun_run_id_8b1c37_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollrun',
            new_name='payroll_pay_busines_ef30ea_idx',
            old_name='payrollrun_business_42e8c2_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollrun',
            new_name='payroll_pay_created_e44dfa_idx',
            old_name='payrollrun_created_fa7c14_idx',
        ),
        migrations.RunSQL(
            [
                "ALTER TABLE payroll_payrollitem DROP CONSTRAINT IF EXISTS unique_recipient_per_run_if_not_deleted;",
                "ALTER TABLE payroll_payrollitem DROP CONSTRAINT IF EXISTS unique_recipient_per_run_if_not_deleted_v2;",
            ],
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AddConstraint(
            model_name='payrollitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('run', 'recipient_account'), name='unique_recipient_per_run_if_not_deleted_v2'),
        ),
    ]
