# Generated by Django 5.2 on 2025-12-17 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_rename_payrollitem_item_id_e5e3f2_idx_payroll_pay_item_id_ebac96_idx_and_more'),
        ('users', '0013_user_platform_os'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payrollitem',
            name='payroll_pay_item_id_ebac96_idx',
        ),
        migrations.RenameField(
            model_name='payrollitem',
            old_name='item_id',
            new_name='internal_id',
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['internal_id'], name='payroll_pay_interna_3da7d5_idx'),
        ),
    ]
