# Generated by Django 5.2 on 2026-07-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_payrollitem_payroll_pay_item_id_ebac96_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollitem',
            name='token_type',
            field=models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin'), ('CUSD_PLUS', 'Confío Dollar Plus'), ('USDT', 'Tether USD (BSC)')], default='CUSD', max_length=10),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='token_type',
            field=models.CharField(choices=[('CUSD', 'Confío Dollar'), ('CONFIO', 'Confío Token'), ('USDC', 'USD Coin'), ('CUSD_PLUS', 'Confío Dollar Plus'), ('USDT', 'Tether USD (BSC)')], default='CUSD', max_length=10),
        ),
    ]
