# Generated by Django 5.2 on 2026-08-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_payrollitem_token_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollitem',
            name='recipient_address',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Recipient address at broadcast time (ledger ownership proof)', max_length=66),
        ),
    ]
