# Generated by Django 5.2 on 2026-08-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrollitem_recipient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollitem',
            name='settled_amount',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Amount actually delivered, decoded from PaidOut', max_digits=19, null=True),
        ),
    ]
