platform :ios, "15.1"

# bring in RN's own pod helpers (this will include autolinking)
require_relative "../node_modules/react-native/scripts/react_native_pods"

prepare_react_native_project!

# Build Swift pods (like FirebaseAuth) as static frameworks:
use_frameworks! :linkage => :static

target 'Confio' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :new_arch_enabled => false
  )

  # (You do NOT need to manually pod RNFBApp & RNFBAuth here;
  #  react-native-firebase will auto-link for you.)
end

post_install do |installer|
  react_native_post_install(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # keep your C++ flags happy
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
      config.build_settings['CLANG_CXX_LIBRARY']        = 'libc++'
      # M1 simulator hack
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']          = '16.0'
      # ensure Swift pods compile with Swift 5+
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end 