require_relative '../node_modules/react-native/scripts/react_native_pods'

# Disable VisionCamera Frame Processors to avoid worklets-core issues
$VCEnableFrameProcessors = false

# Force disable New Architecture to prevent React Native Screens crashes
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

platform :ios, '15.1'
prepare_react_native_project!

# Flipper is disabled due to Firebase use_frameworks requirement
# flipper_config = ENV['NO_FLIPPER'] == '1' ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# Firebase requires frameworks linkage
use_frameworks! :linkage => :static

target 'Confio' do
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is enabled for better debugging and performance
    :hermes_enabled => true,
    # Fabric is disabled - using old architecture
    :fabric_enabled => false,
    # An absolute path to your application root
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Standard fixes for React Native
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Disable bitcode
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        
        # Fix for arm64 simulator
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        
        # Minimum iOS deployment target
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        
        # Fix for React Native Screens sheet presentation
        if target.name == 'RNScreens'
          config.build_settings['RCT_NEW_ARCH_ENABLED'] = '0'
        end
      end
    end
  end
end