# Generated by Django 5.2 on 2026-03-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramps', '0002_ramptransaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ramptransaction',
            new_name='ramps_rampt_provide_c12b6c_idx',
            old_name='ramps_rampt_provide_e3d64c_idx',
        ),
        migrations.RenameIndex(
            model_name='ramptransaction',
            new_name='ramps_rampt_actor_u_c4901c_idx',
            old_name='ramps_rampt_actor_u_f8d7c1_idx',
        ),
        migrations.RenameIndex(
            model_name='ramptransaction',
            new_name='ramps_rampt_actor_b_75bf89_idx',
            old_name='ramps_rampt_actor_b_3e8f58_idx',
        ),
        migrations.RenameIndex(
            model_name='ramptransaction',
            new_name='ramps_rampt_status_55ef8c_idx',
            old_name='ramps_rampt_status_d1bcca_idx',
        ),
        migrations.RenameIndex(
            model_name='ramptransaction',
            new_name='ramps_rampt_provide_d13c9e_idx',
            old_name='ramps_rampt_provide_4f3dad_idx',
        ),
        migrations.RenameIndex(
            model_name='ramptransaction',
            new_name='ramps_rampt_externa_d9fd6c_idx',
            old_name='ramps_rampt_externa_98e5bc_idx',
        ),
    ]
