# Generated by Django 5.2 on 2026-03-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramps', '0004_rampwebhookevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rampwebhookevent',
            new_name='ramps_rampw_provide_c3362b_idx',
            old_name='ramps_ramp_provide_8e5d53_idx',
        ),
        migrations.RenameIndex(
            model_name='rampwebhookevent',
            new_name='ramps_rampw_event_t_d42ae0_idx',
            old_name='ramps_ramp_event_t_1f9d0d_idx',
        ),
    ]
