# Generated by Django 5.2 on 2026-03-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramps', '0005_rename_ramps_ramp_provide_8e5d53_idx_ramps_rampw_provide_c3362b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoyweBankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(help_text='Koywe bankCode value', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-3 country code used by Koywe', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country_code', 'name'],
                'indexes': [models.Index(fields=['country_code', 'is_active'], name='ramps_koywe_country_65e732_idx')],
                'unique_together': {('bank_code', 'country_code')},
            },
        ),
    ]
