# Generated by Django 5.2 on 2026-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramps', '0010_conversion_fk_many_to_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramptransaction',
            name='destination',
            field=models.CharField(choices=[('cusd', 'cUSD (day-to-day, USDC-Algorand)'), ('cusd_plus', 'cUSD+ savings (USDT-BSC)')], default='cusd', help_text='Which product rail this ramp serves; decides token, network and delivery address', max_length=12),
        ),
    ]
