# Generated by Django 5.2 on 2026-07-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramps', '0011_ramptransaction_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramptransaction',
            name='provider',
            field=models.CharField(choices=[('guardarian', 'Guardarian'), ('koywe', 'Koywe'), ('coinbase', 'Coinbase')], max_length=20),
        ),
    ]
