# Generated by Django 5.2 on 2026-09-24 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramps', '0018_repair_bsc_offramp_history_currency'),
        ('usdc_transactions', '0009_ensure_guardarian_withdrawal_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectTransferProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('transaction_hash', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=6, help_text='On-chain USDC amount', max_digits=19)),
                ('counterparty_address', models.CharField(max_length=66)),
                ('confirmed_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('usdc_deposit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_proof', to='usdc_transactions.usdcdeposit')),
                ('usdc_withdrawal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_proof', to='usdc_transactions.usdcwithdrawal')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'deposit'), ('usdc_deposit__isnull', False), ('usdc_withdrawal__isnull', True)), models.Q(('kind', 'withdrawal'), ('usdc_deposit__isnull', True), ('usdc_withdrawal__isnull', False)), _connector='OR'), name='direct_proof_one_row_matching_kind')],
            },
        ),
    ]
