# Generated by Django 5.2 on 2026-09-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramps', '0019_direct_transfer_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoyweRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_order_id', models.CharField(max_length=100, unique=True)),
                ('destination_address', models.CharField(max_length=66)),
                ('auth_email', models.EmailField(blank=True, max_length=254)),
                ('state', models.CharField(db_index=True, default='pending', max_length=32)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('result_code', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ramp', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='koywe_refund', to='ramps.ramptransaction')),
            ],
        ),
    ]
