# Generated by Django 5.2 on 2026-09-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramps', '0020_koywerefund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectTransferProof',
        ),
    ]
