#!/bin/bash
# Distribute tokens on LocalNet with correct environment variables

# Export LocalNet configuration
export ALGORAND_NETWORK=localnet
export ALGORAND_ALGOD_ADDRESS=http://localhost:4001
export ALGORAND_ALGOD_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
export ALGORAND_INDEXER_ADDRESS=http://localhost:8980
export ALGORAND_INDEXER_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
export ALGORAND_CONFIO_ASSET_ID=1057
export ALGORAND_USDC_ASSET_ID=1020
export ALGORAND_CUSD_ASSET_ID=1036

# Export LocalNet creator accounts
export LOCALNET_CONFIO_CREATOR_ADDRESS=2R5BUCI2RWTL3YD5LNFTG5X4KPJGWAAW3F2272X6DAXPRBI2IERQ3JVTZE
export LOCALNET_CONFIO_CREATOR_KEY="oshlQ7WOT7cTLiLBlQFi3jLEf4nh/VgfiGTDvxjPLwnUehoJGo2mveB9W0szdvxT0msAFtl1r+r+GC74hRpBIw=="
export LOCALNET_USDC_CREATOR_ADDRESS=4MMTBHFZUH2IBIZEZ6BWLSMVEGMIKGETISFHV2WOJO5TF2APZYLPDSV2GE
export LOCALNET_USDC_CREATOR_KEY="9WMExgYR7uxpi/gzgulLvswh43jkwwIe+mqDZSYiWlfjGTCcuaH0gKMkz4NlyZUhmIUYk0SKeurOS7sy6A/OFg=="
export LOCALNET_CUSD_APP_ID=1037

# Export distribution amounts
export DISTRIBUTION_CONFIO=1000
export DISTRIBUTION_USDC=5000
export DISTRIBUTION_CUSD=100

# Run the distribution script
./myvenv/bin/python contracts/scripts/distribute_tokens_django.py