# LocalNet Token Configuration

# CONFIO Token (Governance) - 1B fixed supply
CONFIO_ASSET_ID = 1057
CONFIO_CREATOR_ADDRESS = "2R5BUCI2RWTL3YD5LNFTG5X4KPJGWAAW3F2272X6DAXPRBI2IERQ3JVTZE"
CONFIO_CREATOR_PRIVATE_KEY = "oshlQ7WOT7cTLiLBlQFi3jLEf4nh/VgfiGTDvxjPLwnUehoJGo2mveB9W0szdvxT0msAFtl1r+r+GC74hRpBIw=="

# Mock USDC (using old CONFIO with max supply)
MOCK_USDC_ASSET_ID = 1020

# cUSD (Stablecoin)
CUSD_ASSET_ID = 1036
CUSD_APP_ID = 1037
