# Generated by Django 5.2 on 2026-10-04 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbox', '0013_channel_official'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascot', models.CharField(choices=[('CONFI', 'Confi'), ('LLAMA', 'Llama'), ('CAPYBARA', 'Capibara'), ('CAT', 'Gato'), ('DOG', 'Perro')], default='CONFI', max_length=16)),
                ('mascot_name', models.CharField(blank=True, default='', max_length=24)),
                ('mascot_color', models.CharField(blank=True, default='', max_length=7)),
                ('bubble_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantThreadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handoff_at', models.DateTimeField(blank=True, null=True)),
                ('handoff_reason', models.CharField(blank=True, default='', max_length=280)),
                ('returned_to_ai_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_state', to='inbox.supportconversation')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('TEXT', 'Text'), ('VOICE_NOTE', 'Voice note'), ('REALTIME', 'Realtime voice')], default='TEXT', max_length=16)),
                ('screen', models.CharField(blank=True, default='', max_length=64)),
                ('models_used', models.JSONField(blank=True, default=list)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('audio_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_turns', to='inbox.supportconversation')),
                ('reply_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.supportmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_turns', to=settings.AUTH_USER_MODEL)),
                ('user_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.supportmessage')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='assistant_turn_user_idx'), models.Index(fields=['-created_at'], name='assistant_turn_created_idx')],
            },
        ),
    ]
