# Generated by Django 5.2 on 2026-10-04 10:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        ('inbox', '0013_channel_official'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantprofile',
            name='billing_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='assistantprofile',
            name='bubble_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assistantprofile',
            name='bubble_side',
            field=models.CharField(default='right', max_length=5),
        ),
        migrations.AddField(
            model_name='assistantprofile',
            name='wake_word_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StoreNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=8)),
                ('notification_id', models.CharField(max_length=128)),
                ('notification_type', models.CharField(blank=True, default='', max_length=64)),
                ('store_key', models.CharField(blank=True, default='', max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, default='', max_length=280)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'notification_id'), name='assistant_store_notif_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AssistantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'App Store'), ('android', 'Google Play')], max_length=8)),
                ('store_key', models.CharField(max_length=512)),
                ('product_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRACE', 'Grace period (billing retry, still entitled)'), ('ON_HOLD', 'On hold (payment failed, not entitled)'), ('PENDING', 'Pending payment'), ('EXPIRED', 'Expired'), ('REVOKED', 'Refunded / revoked')], max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('grace_until', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('environment', models.CharField(blank=True, default='', max_length=16)),
                ('latest_transaction_id', models.CharField(blank=True, default='', max_length=128)),
                ('acknowledged', models.BooleanField(default=False)),
                ('superseded_by', models.CharField(blank=True, default='', max_length=512)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='assistant_sub_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'store_key'), name='assistant_sub_store_key_uniq')],
            },
        ),
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=64)),
                ('screen', models.CharField(blank=True, default='', max_length=64)),
                ('tz_name', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inbox.supportconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-started_at'], name='assistant_voice_user_idx')],
            },
        ),
    ]
