# Generated by Django 5.2 on 2026-10-04 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_assistantprofile_billing_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantprofile',
            name='mascot',
            field=models.CharField(choices=[('CONFI', 'Confi'), ('LLAMA', 'Llama'), ('CAPYBARA', 'Capibara'), ('CAT', 'Gato'), ('DOG', 'Perro'), ('CUSTOM', 'Mascota creada por el usuario')], default='CONFI', max_length=16),
        ),
        migrations.CreateModel(
            name='CustomPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('idea', 'Idea'), ('photo', 'Photo')], max_length=8)),
                ('idea', models.CharField(blank=True, default='', max_length=300)),
                ('image_key', models.CharField(max_length=512)),
                ('model', models.CharField(max_length=64)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assistantprofile',
            name='custom_pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assistant.custompet'),
        ),
        migrations.AddIndex(
            model_name='custompet',
            index=models.Index(fields=['user', '-created_at'], name='assistant_pet_user_idx'),
        ),
    ]
