# Generated by Django 5.2 on 2026-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_assistantprofile_mascot_custompet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsubscription',
            name='last_signed_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='account_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='business_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='call_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
