# Generated by Django 5.2 on 2026-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_assistantsubscription_last_signed_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicesession',
            name='remote_ended',
            field=models.BooleanField(default=False),
        ),
    ]
