# Generated by Django 5.2 on 2026-10-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_voicesession_remote_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantprofile',
            name='mascot',
            field=models.CharField(choices=[('CONFI', 'Confi'), ('LLAMA', 'Llama'), ('CAPYBARA', 'Capibara'), ('CAT', 'Gato'), ('DOG', 'Perro'), ('CUSTOM', 'Personaje creado por el usuario')], default='CONFI', max_length=16),
        ),
    ]
