# Generated by Django 5.2 on 2026-10-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_alter_assistantprofile_mascot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_id', models.CharField(max_length=64)),
                ('answer', models.CharField(max_length=32)),
                ('phone_country', models.CharField(blank=True, default='', max_length=2)),
                ('funded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_probe_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['probe_id', 'answer'], name='assistant_probe_answer_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'probe_id'), name='assistant_probe_once_per_user')],
            },
        ),
    ]
