# Generated by Django 5.2 on 2026-10-06 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_probe_answer'),
        ('inbox', '0013_channel_official'),  # SupportMessage exists since here; don't pull later inbox work along
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('met_by_confio', models.BooleanField()),
                ('paraphrase', models.CharField(blank=True, default='', max_length=120)),
                ('phone_country', models.CharField(blank=True, default='', max_length=2)),
                ('funded', models.BooleanField(default=False)),
                ('message_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_need', to='inbox.supportmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_needs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['category', '-message_at'], name='assistant_need_cat_idx')],
            },
        ),
    ]
