# Generated by Django 5.2 on 2026-10-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_assistant_need'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreNotification',
        ),
        migrations.RemoveField(
            model_name='assistantprofile',
            name='billing_token',
        ),
    ]
