# Generated by Django 5.2 on 2026-10-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_drop_store_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompet',
            name='rejected_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
