// List of all country codes as [country_name, country_code, iso_code, flag] arrays
// Names are in Spanish. Lookups elsewhere key off the ISO code (index 2),
// never the display name.
const countryData = [
  ['Afganistán', '+93', 'AF', '🇦🇫'],
  ['Albania', '+355', 'AL', '🇦🇱'],
  ['Argelia', '+213', 'DZ', '🇩🇿'],
  ['Samoa Americana', '+1', 'AS', '🇦🇸'],
  ['Andorra', '+376', 'AD', '🇦🇩'],
  ['Angola', '+244', 'AO', '🇦🇴'],
  ['Anguila', '+1', 'AI', '🇦🇮'],
  ['Antigua y Barbuda', '+1', 'AG', '🇦🇬'],
  ['Argentina', '+54', 'AR', '🇦🇷'],
  ['Armenia', '+374', 'AM', '🇦🇲'],
  ['Aruba', '+297', 'AW', '🇦🇼'],
  ['Australia', '+61', 'AU', '🇦🇺'],
  ['Austria', '+43', 'AT', '🇦🇹'],
  ['Azerbaiyán', '+994', 'AZ', '🇦🇿'],
  ['Bahamas', '+1', 'BS', '🇧🇸'],
  ['Baréin', '+973', 'BH', '🇧🇭'],
  ['Bangladés', '+880', 'BD', '🇧🇩'],
  ['Barbados', '+1', 'BB', '🇧🇧'],
  ['Bielorrusia', '+375', 'BY', '🇧🇾'],
  ['Bélgica', '+32', 'BE', '🇧🇪'],
  ['Belice', '+501', 'BZ', '🇧🇿'],
  ['Benín', '+229', 'BJ', '🇧🇯'],
  ['Bermudas', '+1', 'BM', '🇧🇲'],
  ['Bután', '+975', 'BT', '🇧🇹'],
  ['Bolivia', '+591', 'BO', '🇧🇴'],
  ['Bosnia y Herzegovina', '+387', 'BA', '🇧🇦'],
  ['Botsuana', '+267', 'BW', '🇧🇼'],
  ['Brasil', '+55', 'BR', '🇧🇷'],
  ['Territorio Británico del Océano Índico', '+246', 'IO', '🇮🇴'],
  ['Islas Vírgenes Británicas', '+1', 'VG', '🇻🇬'],
  ['Brunéi', '+673', 'BN', '🇧🇳'],
  ['Bulgaria', '+359', 'BG', '🇧🇬'],
  ['Burkina Faso', '+226', 'BF', '🇧🇫'],
  ['Burundi', '+257', 'BI', '🇧🇮'],
  ['Camboya', '+855', 'KH', '🇰🇭'],
  ['Camerún', '+237', 'CM', '🇨🇲'],
  ['Canadá', '+1', 'CA', '🇨🇦'],
  ['Cabo Verde', '+238', 'CV', '🇨🇻'],
  ['Caribe Neerlandés', '+599', 'BQ', '🇧🇶'],
  ['Islas Caimán', '+1', 'KY', '🇰🇾'],
  ['República Centroafricana', '+236', 'CF', '🇨🇫'],
  ['Chad', '+235', 'TD', '🇹🇩'],
  ['Chile', '+56', 'CL', '🇨🇱'],
  ['China', '+86', 'CN', '🇨🇳'],
  ['Isla de Navidad', '+61', 'CX', '🇨🇽'],
  ['Islas Cocos', '+61', 'CC', '🇨🇨'],
  ['Colombia', '+57', 'CO', '🇨🇴'],
  ['Comoras', '+269', 'KM', '🇰🇲'],
  ['República Democrática del Congo', '+243', 'CD', '🇨🇩'],
  ['República del Congo', '+242', 'CG', '🇨🇬'],
  ['Islas Cook', '+682', 'CK', '🇨🇰'],
  ['Costa Rica', '+506', 'CR', '🇨🇷'],
  ['Costa de Marfil', '+225', 'CI', '🇨🇮'],
  ['Croacia', '+385', 'HR', '🇭🇷'],
  ['Cuba', '+53', 'CU', '🇨🇺'],
  ['Curazao', '+599', 'CW', '🇨🇼'],
  ['Chipre', '+357', 'CY', '🇨🇾'],
  ['República Checa', '+420', 'CZ', '🇨🇿'],
  ['Dinamarca', '+45', 'DK', '🇩🇰'],
  ['Yibuti', '+253', 'DJ', '🇩🇯'],
  ['Dominica', '+1', 'DM', '🇩🇲'],
  ['República Dominicana', '+1', 'DO', '🇩🇴'],
  ['Ecuador', '+593', 'EC', '🇪🇨'],
  ['Egipto', '+20', 'EG', '🇪🇬'],
  ['El Salvador', '+503', 'SV', '🇸🇻'],
  ['Guinea Ecuatorial', '+240', 'GQ', '🇬🇶'],
  ['Eritrea', '+291', 'ER', '🇪🇷'],
  ['Estonia', '+372', 'EE', '🇪🇪'],
  ['Etiopía', '+251', 'ET', '🇪🇹'],
  ['Islas Malvinas', '+500', 'FK', '🇫🇰'],
  ['Islas Feroe', '+298', 'FO', '🇫🇴'],
  ['Fiyi', '+679', 'FJ', '🇫🇯'],
  ['Finlandia', '+358', 'FI', '🇫🇮'],
  ['Francia', '+33', 'FR', '🇫🇷'],
  ['Guayana Francesa', '+594', 'GF', '🇬🇫'],
  ['Polinesia Francesa', '+689', 'PF', '🇵🇫'],
  ['Gabón', '+241', 'GA', '🇬🇦'],
  ['Gambia', '+220', 'GM', '🇬🇲'],
  ['Georgia', '+995', 'GE', '🇬🇪'],
  ['Alemania', '+49', 'DE', '🇩🇪'],
  ['Ghana', '+233', 'GH', '🇬🇭'],
  ['Gibraltar', '+350', 'GI', '🇬🇮'],
  ['Grecia', '+30', 'GR', '🇬🇷'],
  ['Groenlandia', '+299', 'GL', '🇬🇱'],
  ['Granada', '+1', 'GD', '🇬🇩'],
  ['Guadalupe', '+590', 'GP', '🇬🇵'],
  ['Guam', '+1', 'GU', '🇬🇺'],
  ['Guatemala', '+502', 'GT', '🇬🇹'],
  ['Guernsey', '+44', 'GG', '🇬🇬'],
  ['Guinea', '+224', 'GN', '🇬🇳'],
  ['Guinea-Bisáu', '+245', 'GW', '🇬🇼'],
  ['Guyana', '+592', 'GY', '🇬🇾'],
  ['Haití', '+509', 'HT', '🇭🇹'],
  ['Honduras', '+504', 'HN', '🇭🇳'],
  ['Hong Kong', '+852', 'HK', '🇭🇰'],
  ['Hungría', '+36', 'HU', '🇭🇺'],
  ['Islandia', '+354', 'IS', '🇮🇸'],
  ['India', '+91', 'IN', '🇮🇳'],
  ['Indonesia', '+62', 'ID', '🇮🇩'],
  ['Irán', '+98', 'IR', '🇮🇷'],
  ['Irak', '+964', 'IQ', '🇮🇶'],
  ['Irlanda', '+353', 'IE', '🇮🇪'],
  ['Isla de Man', '+44', 'IM', '🇮🇲'],
  ['Israel', '+972', 'IL', '🇮🇱'],
  ['Italia', '+39', 'IT', '🇮🇹'],
  ['Jamaica', '+1', 'JM', '🇯🇲'],
  ['Japón', '+81', 'JP', '🇯🇵'],
  ['Jersey', '+44', 'JE', '🇯🇪'],
  ['Jordania', '+962', 'JO', '🇯🇴'],
  ['Kazajistán', '+7', 'KZ', '🇰🇿'],
  ['Kenia', '+254', 'KE', '🇰🇪'],
  ['Kiribati', '+686', 'KI', '🇰🇮'],
  ['Kosovo', '+383', 'XK', '🇽🇰'],
  ['Kuwait', '+965', 'KW', '🇰🇼'],
  ['Kirguistán', '+996', 'KG', '🇰🇬'],
  ['Laos', '+856', 'LA', '🇱🇦'],
  ['Letonia', '+371', 'LV', '🇱🇻'],
  ['Líbano', '+961', 'LB', '🇱🇧'],
  ['Lesoto', '+266', 'LS', '🇱🇸'],
  ['Liberia', '+231', 'LR', '🇱🇷'],
  ['Libia', '+218', 'LY', '🇱🇾'],
  ['Liechtenstein', '+423', 'LI', '🇱🇮'],
  ['Lituania', '+370', 'LT', '🇱🇹'],
  ['Luxemburgo', '+352', 'LU', '🇱🇺'],
  ['Macao', '+853', 'MO', '🇲🇴'],
  ['Macedonia del Norte', '+389', 'MK', '🇲🇰'],
  ['Madagascar', '+261', 'MG', '🇲🇬'],
  ['Malaui', '+265', 'MW', '🇲🇼'],
  ['Malasia', '+60', 'MY', '🇲🇾'],
  ['Maldivas', '+960', 'MV', '🇲🇻'],
  ['Malí', '+223', 'ML', '🇲🇱'],
  ['Malta', '+356', 'MT', '🇲🇹'],
  ['Islas Marshall', '+692', 'MH', '🇲🇭'],
  ['Martinica', '+596', 'MQ', '🇲🇶'],
  ['Mauritania', '+222', 'MR', '🇲🇷'],
  ['Mauricio', '+230', 'MU', '🇲🇺'],
  ['Mayotte', '+262', 'YT', '🇾🇹'],
  ['México', '+52', 'MX', '🇲🇽'],
  ['Micronesia', '+691', 'FM', '🇫🇲'],
  ['Moldavia', '+373', 'MD', '🇲🇩'],
  ['Mónaco', '+377', 'MC', '🇲🇨'],
  ['Mongolia', '+976', 'MN', '🇲🇳'],
  ['Montenegro', '+382', 'ME', '🇲🇪'],
  ['Montserrat', '+1', 'MS', '🇲🇸'],
  ['Marruecos', '+212', 'MA', '🇲🇦'],
  ['Mozambique', '+258', 'MZ', '🇲🇿'],
  ['Myanmar', '+95', 'MM', '🇲🇲'],
  ['Namibia', '+264', 'NA', '🇳🇦'],
  ['Nauru', '+674', 'NR', '🇳🇷'],
  ['Nepal', '+977', 'NP', '🇳🇵'],
  ['Países Bajos', '+31', 'NL', '🇳🇱'],
  ['Nueva Caledonia', '+687', 'NC', '🇳🇨'],
  ['Nueva Zelanda', '+64', 'NZ', '🇳🇿'],
  ['Nicaragua', '+505', 'NI', '🇳🇮'],
  ['Níger', '+227', 'NE', '🇳🇪'],
  ['Nigeria', '+234', 'NG', '🇳🇬'],
  ['Niue', '+683', 'NU', '🇳🇺'],
  ['Isla Norfolk', '+672', 'NF', '🇳🇫'],
  ['Corea del Norte', '+850', 'KP', '🇰🇵'],
  ['Islas Marianas del Norte', '+1', 'MP', '🇲🇵'],
  ['Noruega', '+47', 'NO', '🇳🇴'],
  ['Omán', '+968', 'OM', '🇴🇲'],
  ['Pakistán', '+92', 'PK', '🇵🇰'],
  ['Palaos', '+680', 'PW', '🇵🇼'],
  ['Palestina', '+970', 'PS', '🇵🇸'],
  ['Panamá', '+507', 'PA', '🇵🇦'],
  ['Papúa Nueva Guinea', '+675', 'PG', '🇵🇬'],
  ['Paraguay', '+595', 'PY', '🇵🇾'],
  ['Perú', '+51', 'PE', '🇵🇪'],
  ['Filipinas', '+63', 'PH', '🇵🇭'],
  ['Polonia', '+48', 'PL', '🇵🇱'],
  ['Portugal', '+351', 'PT', '🇵🇹'],
  ['Puerto Rico', '+1', 'PR', '🇵🇷'],
  ['Catar', '+974', 'QA', '🇶🇦'],
  ['Reunión', '+262', 'RE', '🇷🇪'],
  ['Rumania', '+40', 'RO', '🇷🇴'],
  ['Rusia', '+7', 'RU', '🇷🇺'],
  ['Ruanda', '+250', 'RW', '🇷🇼'],
  ['San Bartolomé', '+590', 'BL', '🇧🇱'],
  ['Santa Elena', '+290', 'SH', '🇸🇭'],
  ['San Cristóbal y Nieves', '+1', 'KN', '🇰🇳'],
  ['Santa Lucía', '+1', 'LC', '🇱🇨'],
  ['San Martín', '+590', 'MF', '🇲🇫'],
  ['San Pedro y Miquelón', '+508', 'PM', '🇵🇲'],
  ['San Vicente y las Granadinas', '+1', 'VC', '🇻🇨'],
  ['Samoa', '+685', 'WS', '🇼🇸'],
  ['San Marino', '+378', 'SM', '🇸🇲'],
  ['Santo Tomé y Príncipe', '+239', 'ST', '🇸🇹'],
  ['Arabia Saudita', '+966', 'SA', '🇸🇦'],
  ['Senegal', '+221', 'SN', '🇸🇳'],
  ['Serbia', '+381', 'RS', '🇷🇸'],
  ['Seychelles', '+248', 'SC', '🇸🇨'],
  ['Sierra Leona', '+232', 'SL', '🇸🇱'],
  ['Singapur', '+65', 'SG', '🇸🇬'],
  ['Sint Maarten', '+1', 'SX', '🇸🇽'],
  ['Eslovaquia', '+421', 'SK', '🇸🇰'],
  ['Eslovenia', '+386', 'SI', '🇸🇮'],
  ['Islas Salomón', '+677', 'SB', '🇸🇧'],
  ['Somalia', '+252', 'SO', '🇸🇴'],
  ['Sudáfrica', '+27', 'ZA', '🇿🇦'],
  ['Corea del Sur', '+82', 'KR', '🇰🇷'],
  ['Sudán del Sur', '+211', 'SS', '🇸🇸'],
  ['España', '+34', 'ES', '🇪🇸'],
  ['Sri Lanka', '+94', 'LK', '🇱🇰'],
  ['Sudán', '+249', 'SD', '🇸🇩'],
  ['Surinam', '+597', 'SR', '🇸🇷'],
  ['Svalbard y Jan Mayen', '+47', 'SJ', '🇸🇯'],
  ['Esuatini', '+268', 'SZ', '🇸🇿'],
  ['Suecia', '+46', 'SE', '🇸🇪'],
  ['Suiza', '+41', 'CH', '🇨🇭'],
  ['Siria', '+963', 'SY', '🇸🇾'],
  ['Taiwán', '+886', 'TW', '🇹🇼'],
  ['Tayikistán', '+992', 'TJ', '🇹🇯'],
  ['Tanzania', '+255', 'TZ', '🇹🇿'],
  ['Tailandia', '+66', 'TH', '🇹🇭'],
  ['Timor Oriental', '+670', 'TL', '🇹🇱'],
  ['Togo', '+228', 'TG', '🇹🇬'],
  ['Tokelau', '+690', 'TK', '🇹🇰'],
  ['Tonga', '+676', 'TO', '🇹🇴'],
  ['Trinidad y Tobago', '+1', 'TT', '🇹🇹'],
  ['Túnez', '+216', 'TN', '🇹🇳'],
  ['Turquía', '+90', 'TR', '🇹🇷'],
  ['Turkmenistán', '+993', 'TM', '🇹🇲'],
  ['Islas Turcas y Caicos', '+1', 'TC', '🇹🇨'],
  ['Tuvalu', '+688', 'TV', '🇹🇻'],
  ['Islas Vírgenes de EE. UU.', '+1', 'VI', '🇻🇮'],
  ['Uganda', '+256', 'UG', '🇺🇬'],
  ['Ucrania', '+380', 'UA', '🇺🇦'],
  ['Emiratos Árabes Unidos', '+971', 'AE', '🇦🇪'],
  ['Reino Unido', '+44', 'GB', '🇬🇧'],
  ['Estados Unidos', '+1', 'US', '🇺🇸'],
  ['Uruguay', '+598', 'UY', '🇺🇾'],
  ['Uzbekistán', '+998', 'UZ', '🇺🇿'],
  ['Vanuatu', '+678', 'VU', '🇻🇺'],
  ['Ciudad del Vaticano', '+379', 'VA', '🇻🇦'],
  ['Venezuela', '+58', 'VE', '🇻🇪'],
  ['Vietnam', '+84', 'VN', '🇻🇳'],
  ['Wallis y Futuna', '+681', 'WF', '🇼🇫'],
  ['Sáhara Occidental', '+212', 'EH', '🇪🇭'],
  ['Yemen', '+967', 'YE', '🇾🇪'],
  ['Zambia', '+260', 'ZM', '🇿🇲'],
  ['Zimbabue', '+263', 'ZW', '🇿🇼']
] as const;

// Accent-insensitive lowercasing so "Mexico" matches "México" (and sorting
// doesn't depend on the runtime's ICU support).
const normalizeText = (text: string): string =>
  text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');

// Exported sorted alphabetically by Spanish name
export const countries = [...countryData].sort((a, b) =>
  normalizeText(a[0]).localeCompare(normalizeText(b[0]))
);

// Type for a country entry
export type Country = typeof countries[number];

// Filter countries by name (accent-insensitive), phone code, or ISO code
export const filterCountries = (query: string): Country[] => {
  const normalized = normalizeText(query.trim());
  if (!normalized) return countries;
  const digits = normalized.replace(/^\+/, '');
  return countries.filter(country =>
    normalizeText(country[0]).includes(normalized) ||
    (digits && country[1].replace('+', '').startsWith(digits)) ||
    country[2].toLowerCase() === normalized
  );
};

// Helper function to get country by ISO code
export const getCountryByIso = (iso: string): Country | undefined => {
  return countries.find(country => country[2] === iso);
};

// Helper function to get country by phone code
export const getCountryByPhoneCode = (code: string): Country | undefined => {
  return countries.find(country => country[1] === code);
};
