// Temporary mock data for the Financieras directory UI.
// Replace with a GraphQL-backed source once the backend lands.
//
// Every financiera supports USDC-Algorand (mandatory). Amounts in reviews are
// always USDC for now.

import { Financiera } from '../types/financiera';

export const MOCK_FINANCIERAS: Financiera[] = [
  // ── Venezuela ──────────────────────────────────────────────────────────────
  {
    id: 'f1',
    name: 'Cambios El Ávila',
    verified: true,
    countryIso: 'VE',
    state: 'Distrito Capital',
    city: 'Caracas',
    barrio: 'Chacao',
    whatsapp: '584141234567',
    services: ['usdc_algorand', 'help_confio'],
    avgRating: 4.8,
    reviewCount: 4,
    reviews: [
      { id: 'r1', rating: 5, sentUsdc: 100, receivedUsd: 98, comment: 'Rápido y en efectivo, sin vueltas.', createdAt: '2026-05-30' },
      { id: 'r2', rating: 5, sentUsdc: 200, receivedUsd: 196, comment: 'Me ayudaron a usar la app la primera vez.', createdAt: '2026-05-22' },
      { id: 'r3', rating: 4, sentUsdc: 100, receivedUsd: 97, createdAt: '2026-05-10' },
      { id: 'r4', rating: 5, sentUsdc: 500, receivedUsd: 492, comment: 'Confiable, ya es la tercera vez.', createdAt: '2026-04-28' },
    ],
  },
  {
    id: 'f2',
    name: 'Divisas La Castellana',
    verified: true,
    countryIso: 'VE',
    state: 'Distrito Capital',
    city: 'Caracas',
    barrio: 'La Castellana',
    whatsapp: '584149876543',
    services: ['usdc_algorand'],
    avgRating: 4.5,
    reviewCount: 3,
    reviews: [
      { id: 'r5', rating: 5, sentUsdc: 100, receivedUsd: 97, comment: 'Muy serios y profesionales.', createdAt: '2026-06-01' },
      { id: 'r6', rating: 4, sentUsdc: 300, receivedUsd: 290, createdAt: '2026-05-18' },
      { id: 'r7', rating: 4, sentUsdc: 150, receivedUsd: 145, comment: 'Buen trato, esperé unos minutos.', createdAt: '2026-05-05' },
    ],
  },
  {
    id: 'f3',
    name: 'Maracaibo Money',
    verified: true,
    countryIso: 'VE',
    state: 'Zulia',
    city: 'Maracaibo',
    barrio: 'Bella Vista',
    whatsapp: '584161112233',
    services: ['usdc_algorand', 'weekends'],
    avgRating: 4.2,
    reviewCount: 2,
    reviews: [
      { id: 'r8', rating: 4, sentUsdc: 100, receivedUsd: 96, comment: 'Efectivo en dólares al toque.', createdAt: '2026-05-27' },
      { id: 'r9', rating: 4, sentUsdc: 250, receivedUsd: 240, createdAt: '2026-05-12' },
    ],
  },
  {
    id: 'f4',
    name: 'Valencia Cambios',
    verified: true,
    countryIso: 'VE',
    state: 'Carabobo',
    city: 'Valencia',
    barrio: 'San José',
    whatsapp: '584125556677',
    services: ['usdc_algorand', 'home_service'],
    avgRating: 4.7,
    reviewCount: 3,
    reviews: [
      { id: 'r10', rating: 5, sentUsdc: 100, receivedUsd: 98, comment: 'Vinieron hasta mi oficina.', createdAt: '2026-06-02' },
      { id: 'r11', rating: 5, sentUsdc: 400, receivedUsd: 394, createdAt: '2026-05-19' },
      { id: 'r12', rating: 4, sentUsdc: 150, receivedUsd: 145, createdAt: '2026-05-03' },
    ],
  },
  {
    id: 'f5',
    name: 'Barquisimeto Divisas',
    verified: true,
    countryIso: 'VE',
    state: 'Lara',
    city: 'Barquisimeto',
    barrio: 'Este',
    whatsapp: '584148889900',
    services: ['usdc_algorand', 'help_confio'],
    avgRating: 4.4,
    reviewCount: 2,
    reviews: [
      { id: 'r13', rating: 5, sentUsdc: 100, receivedUsd: 97, comment: 'Pacientes, me explicaron todo.', createdAt: '2026-05-28' },
      { id: 'r14', rating: 4, sentUsdc: 200, receivedUsd: 193, createdAt: '2026-05-14' },
    ],
  },
  {
    id: 'f6',
    name: 'Aragua Express',
    verified: true,
    countryIso: 'VE',
    state: 'Aragua',
    city: 'Maracay',
    barrio: 'La Soledad',
    whatsapp: '584142223344',
    services: ['usdc_algorand'],
    avgRating: 4.1,
    reviewCount: 2,
    reviews: [
      { id: 'r15', rating: 4, sentUsdc: 100, receivedUsd: 95, createdAt: '2026-05-24' },
      { id: 'r16', rating: 4, sentUsdc: 300, receivedUsd: 288, comment: 'Todo bien, sin problemas.', createdAt: '2026-05-09' },
    ],
  },
  {
    id: 'f7',
    name: 'Táchira Cambios',
    verified: true,
    countryIso: 'VE',
    state: 'Táchira',
    city: 'San Cristóbal',
    barrio: 'Barrio Obrero',
    whatsapp: '584147778899',
    services: ['usdc_algorand', 'weekends'],
    avgRating: 4.6,
    reviewCount: 3,
    reviews: [
      { id: 'r17', rating: 5, sentUsdc: 100, receivedUsd: 98, comment: 'Abiertos el domingo, salvavidas.', createdAt: '2026-06-04' },
      { id: 'r18', rating: 4, sentUsdc: 250, receivedUsd: 242, createdAt: '2026-05-20' },
      { id: 'r19', rating: 5, sentUsdc: 150, receivedUsd: 148, createdAt: '2026-05-06' },
    ],
  },

  // ── Argentina ───────────────────────────────────────────────────────────────
  {
    id: 'f8',
    name: 'Cambio Palermo',
    verified: true,
    countryIso: 'AR',
    state: 'Capital Federal',
    city: 'Buenos Aires',
    barrio: 'Palermo',
    whatsapp: '5491134567890',
    services: ['usdc_algorand', 'help_confio'],
    avgRating: 4.9,
    reviewCount: 5,
    reviews: [
      { id: 'r20', rating: 5, sentUsdc: 100, receivedUsd: 99, comment: 'El mejor de la zona.', createdAt: '2026-06-03' },
      { id: 'r21', rating: 5, sentUsdc: 1000, receivedUsd: 988, comment: 'Operé fuerte, todo en regla.', createdAt: '2026-05-29' },
      { id: 'r22', rating: 5, sentUsdc: 200, receivedUsd: 198, createdAt: '2026-05-20' },
      { id: 'r23', rating: 4, sentUsdc: 100, receivedUsd: 98, createdAt: '2026-05-09' },
      { id: 'r24', rating: 5, sentUsdc: 300, receivedUsd: 297, comment: 'Atención impecable.', createdAt: '2026-04-30' },
    ],
  },
  {
    id: 'f9',
    name: 'Recoleta Cambio',
    verified: true,
    countryIso: 'AR',
    state: 'Capital Federal',
    city: 'Buenos Aires',
    barrio: 'Recoleta',
    whatsapp: '5491145678901',
    services: ['usdc_algorand'],
    avgRating: 4.6,
    reviewCount: 3,
    reviews: [
      { id: 'r25', rating: 5, sentUsdc: 100, receivedUsd: 98, createdAt: '2026-06-02' },
      { id: 'r26', rating: 4, sentUsdc: 500, receivedUsd: 490, comment: 'Rápidos y claros.', createdAt: '2026-05-21' },
      { id: 'r27', rating: 5, sentUsdc: 150, receivedUsd: 148, createdAt: '2026-05-08' },
    ],
  },
  {
    id: 'f10',
    name: 'Córdoba Divisas',
    verified: true,
    countryIso: 'AR',
    state: 'Córdoba',
    city: 'Córdoba',
    barrio: 'Nueva Córdoba',
    whatsapp: '5493514567890',
    services: ['usdc_algorand', 'weekends'],
    avgRating: 4.3,
    reviewCount: 2,
    reviews: [
      { id: 'r28', rating: 4, sentUsdc: 100, receivedUsd: 96, createdAt: '2026-05-25' },
      { id: 'r29', rating: 5, sentUsdc: 200, receivedUsd: 197, comment: 'Atienden los sábados.', createdAt: '2026-05-11' },
    ],
  },
  {
    id: 'f11',
    name: 'Rosario Cambios',
    verified: true,
    countryIso: 'AR',
    state: 'Santa Fe',
    city: 'Rosario',
    barrio: 'Centro',
    whatsapp: '5493415678902',
    services: ['usdc_algorand', 'home_service'],
    avgRating: 4.5,
    reviewCount: 2,
    reviews: [
      { id: 'r30', rating: 5, sentUsdc: 100, receivedUsd: 98, comment: 'Me llevaron el efectivo a casa.', createdAt: '2026-05-31' },
      { id: 'r31', rating: 4, sentUsdc: 300, receivedUsd: 291, createdAt: '2026-05-15' },
    ],
  },
  {
    id: 'f12',
    name: 'Mendoza Money',
    verified: true,
    countryIso: 'AR',
    state: 'Mendoza',
    city: 'Mendoza',
    barrio: 'Ciudad',
    whatsapp: '5492614567893',
    services: ['usdc_algorand'],
    avgRating: 4.2,
    reviewCount: 2,
    reviews: [
      { id: 'r32', rating: 4, sentUsdc: 100, receivedUsd: 96, createdAt: '2026-05-26' },
      { id: 'r33', rating: 4, sentUsdc: 250, receivedUsd: 241, createdAt: '2026-05-13' },
    ],
  },
];
