module p2p_trade::p2p_trade {
    use aptos_framework::fungible_asset::{Self, FungibleAsset, Metadata};
    use aptos_framework::primary_fungible_store;
    use aptos_framework::object::{Self, Object};
    use aptos_framework::signer::address_of;
    use aptos_framework::timestamp;
    use aptos_framework::event;
    use aptos_framework::table::{Self, Table};
    use std::error;
    use std::vector;
    use cusd::cusd;
    use confio::confio;

    // Error codes
    const E_NOT_AUTHORIZED: u64 = 1;
    const E_INVALID_AMOUNT: u64 = 2;
    const E_TRADE_NOT_FOUND: u64 = 3;
    const E_TRADE_ALREADY_ACCEPTED: u64 = 4;
    const E_TRADE_EXPIRED: u64 = 5;
    const E_TRADE_NOT_EXPIRED: u64 = 6;
    const E_TRADE_ALREADY_COMPLETED: u64 = 7;
    const E_TRADE_ALREADY_CANCELLED: u64 = 8;
    const E_TRADE_IN_DISPUTE: u64 = 9;
    const E_TRADE_NOT_IN_DISPUTE: u64 = 10;
    const E_INVALID_TRADE_STATE: u64 = 11;
    const E_SYSTEM_PAUSED: u64 = 12;
    const E_SELF_TRADE: u64 = 13;
    const E_NOT_ADMIN: u64 = 14;
    const E_TRADE_EXISTS: u64 = 15;

    // Constants
    const TRADE_WINDOW_MS: u64 = 900000000; // 15 minutes in microseconds
    const STATUS_PENDING: u8 = 0;
    const STATUS_ACTIVE: u8 = 1;
    const STATUS_COMPLETED: u8 = 2;
    const STATUS_CANCELLED: u8 = 3;
    const STATUS_DISPUTED: u8 = 4;
    const STATUS_EXPIRED: u8 = 5;

    // Resources
    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct AdminConfig has key {
        admin: address,
        is_paused: bool,
        // Statistics
        total_trades_created: u64,
        total_trades_completed: u64,
        total_trades_cancelled: u64,
        total_trades_disputed: u64,
        total_cusd_volume: u64,
        total_confio_volume: u64
    }

    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct TradeRegistry has key {
        trades: Table<vector<u8>, Trade>,
    }

    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct EscrowVault has key {
        cusd_balances: Table<vector<u8>, u64>,
        confio_balances: Table<vector<u8>, u64>,
    }

    struct Trade has store, copy, drop {
        // Trade participants
        seller: address,
        buyer: address,
        // Trade details
        amount: u64,
        token_type: vector<u8>, // "CUSD" or "CONFIO"
        // Fiat details (stored in Django, just reference here)
        fiat_amount: u64,
        fiat_currency: vector<u8>, // e.g., "VES", "ARS", "USD"
        // Timestamps
        created_at: u64,
        expires_at: u64,
        accepted_at: u64,
        // Status
        status: u8,
        // Dispute info
        dispute_reason: vector<u8>,
        dispute_opened_by: address,
        dispute_opened_at: u64
    }

    // Events
    #[event]
    struct TradeCreated has drop, store {
        trade_id: vector<u8>,
        seller: address,
        amount: u64,
        token_type: vector<u8>,
        fiat_amount: u64,
        fiat_currency: vector<u8>,
        expires_at: u64,
        timestamp: u64
    }

    #[event]
    struct TradeAccepted has drop, store {
        trade_id: vector<u8>,
        buyer: address,
        timestamp: u64
    }

    #[event]
    struct TradeCompleted has drop, store {
        trade_id: vector<u8>,
        seller: address,
        buyer: address,
        amount: u64,
        token_type: vector<u8>,
        timestamp: u64
    }

    #[event]
    struct TradeCancelled has drop, store {
        trade_id: vector<u8>,
        cancelled_by: address,
        reason: vector<u8>,
        timestamp: u64
    }

    #[event]
    struct DisputeOpened has drop, store {
        trade_id: vector<u8>,
        opened_by: address,
        reason: vector<u8>,
        timestamp: u64
    }

    #[event]
    struct DisputeResolved has drop, store {
        trade_id: vector<u8>,
        resolved_by: address,
        winner: address,
        timestamp: u64
    }

    #[event]
    struct TradeExpired has drop, store {
        trade_id: vector<u8>,
        timestamp: u64
    }

    // Initialize
    fun init_module(admin: &signer) {
        // Initialize admin config
        move_to(admin, AdminConfig {
            admin: address_of(admin),
            is_paused: false,
            total_trades_created: 0,
            total_trades_completed: 0,
            total_trades_cancelled: 0,
            total_trades_disputed: 0,
            total_cusd_volume: 0,
            total_confio_volume: 0
        });

        move_to(admin, TradeRegistry {
            trades: table::new(),
        });

        move_to(admin, EscrowVault {
            cusd_balances: table::new(),
            confio_balances: table::new(),
        });
    }

    // Create a new P2P trade offer (seller deposits crypto)
    public entry fun create_cusd_trade(
        seller: &signer,
        amount: u64,
        trade_id: vector<u8>, // Generated by Django
        fiat_amount: u64,
        fiat_currency: vector<u8>,
    ) acquires AdminConfig, TradeRegistry, EscrowVault {
        let admin_config = borrow_global_mut<AdminConfig>(@p2p_trade);
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        assert!(amount > 0, error::invalid_argument(E_INVALID_AMOUNT));
        
        let registry = borrow_global_mut<TradeRegistry>(@p2p_trade);
        assert!(!table::contains(&registry.trades, trade_id), error::already_exists(E_TRADE_EXISTS));
        
        let current_time = timestamp::now_microseconds();
        let expires_at = current_time + TRADE_WINDOW_MS;
        
        // Create trade record
        let trade = Trade {
            seller: address_of(seller),
            buyer: @0x0, // Will be set when accepted
            amount,
            token_type: b"CUSD",
            fiat_amount,
            fiat_currency,
            created_at: current_time,
            expires_at,
            accepted_at: 0,
            status: STATUS_PENDING,
            dispute_reason: vector::empty(),
            dispute_opened_by: @0x0,
            dispute_opened_at: 0
        };
        
        // Store trade
        table::add(&mut registry.trades, trade_id, trade);
        
        // Escrow the funds by transferring to module account
        let cusd_metadata = cusd::get_metadata();
        primary_fungible_store::transfer(seller, cusd_metadata, @p2p_trade, amount);
        
        let vault = borrow_global_mut<EscrowVault>(@p2p_trade);
        table::add(&mut vault.cusd_balances, trade_id, amount);
        
        // Update statistics
        admin_config.total_trades_created = admin_config.total_trades_created + 1;
        
        // Emit event
        event::emit(TradeCreated {
            trade_id,
            seller: address_of(seller),
            amount,
            token_type: b"CUSD",
            fiat_amount,
            fiat_currency,
            expires_at,
            timestamp: current_time
        });
    }

    // Create CONFIO trade
    public entry fun create_confio_trade(
        seller: &signer,
        amount: u64,
        trade_id: vector<u8>,
        fiat_amount: u64,
        fiat_currency: vector<u8>,
    ) acquires AdminConfig, TradeRegistry, EscrowVault {
        let admin_config = borrow_global_mut<AdminConfig>(@p2p_trade);
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        assert!(amount > 0, error::invalid_argument(E_INVALID_AMOUNT));
        
        let registry = borrow_global_mut<TradeRegistry>(@p2p_trade);
        assert!(!table::contains(&registry.trades, trade_id), error::already_exists(E_TRADE_EXISTS));
        
        let current_time = timestamp::now_microseconds();
        let expires_at = current_time + TRADE_WINDOW_MS;
        
        // Create trade record
        let trade = Trade {
            seller: address_of(seller),
            buyer: @0x0,
            amount,
            token_type: b"CONFIO",
            fiat_amount,
            fiat_currency,
            created_at: current_time,
            expires_at,
            accepted_at: 0,
            status: STATUS_PENDING,
            dispute_reason: vector::empty(),
            dispute_opened_by: @0x0,
            dispute_opened_at: 0
        };
        
        // Store trade
        table::add(&mut registry.trades, trade_id, trade);
        
        // Escrow the funds by transferring to module account
        let confio_metadata = confio::get_metadata();
        primary_fungible_store::transfer(seller, confio_metadata, @p2p_trade, amount);
        
        let vault = borrow_global_mut<EscrowVault>(@p2p_trade);
        table::add(&mut vault.confio_balances, trade_id, amount);
        
        // Update statistics
        admin_config.total_trades_created = admin_config.total_trades_created + 1;
        
        // Emit event
        event::emit(TradeCreated {
            trade_id,
            seller: address_of(seller),
            amount,
            token_type: b"CONFIO",
            fiat_amount,
            fiat_currency,
            expires_at,
            timestamp: current_time
        });
    }

    // Buyer accepts the trade
    public entry fun accept_trade(
        buyer: &signer,
        trade_id: vector<u8>,
    ) acquires AdminConfig, TradeRegistry {
        let admin_config = borrow_global<AdminConfig>(@p2p_trade);
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        
        let registry = borrow_global_mut<TradeRegistry>(@p2p_trade);
        assert!(table::contains(&registry.trades, trade_id), error::not_found(E_TRADE_NOT_FOUND));
        
        let trade = table::borrow_mut(&mut registry.trades, trade_id);
        assert!(trade.status == STATUS_PENDING, error::invalid_state(E_INVALID_TRADE_STATE));
        assert!(trade.seller != address_of(buyer), error::invalid_argument(E_SELF_TRADE));
        
        let current_time = timestamp::now_microseconds();
        assert!(current_time <= trade.expires_at, error::invalid_state(E_TRADE_EXPIRED));
        
        // Update trade
        trade.buyer = address_of(buyer);
        trade.status = STATUS_ACTIVE;
        trade.accepted_at = current_time;
        
        // Emit event
        event::emit(TradeAccepted {
            trade_id,
            buyer: address_of(buyer),
            timestamp: current_time
        });
    }

    // Seller confirms payment received
    public entry fun confirm_payment_received(
        seller: &signer,
        trade_id: vector<u8>,
    ) acquires AdminConfig, TradeRegistry, EscrowVault {
        let admin_config = borrow_global_mut<AdminConfig>(@p2p_trade);
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        
        let registry = borrow_global_mut<TradeRegistry>(@p2p_trade);
        assert!(table::contains(&registry.trades, trade_id), error::not_found(E_TRADE_NOT_FOUND));
        
        let trade = table::borrow_mut(&mut registry.trades, trade_id);
        assert!(trade.seller == address_of(seller), error::permission_denied(E_NOT_AUTHORIZED));
        assert!(trade.status == STATUS_ACTIVE, error::invalid_state(E_INVALID_TRADE_STATE));
        
        let current_time = timestamp::now_microseconds();
        
        // Mark as completed
        trade.status = STATUS_COMPLETED;
        
        // Release funds to buyer
        let buyer = trade.buyer;
        let amount = trade.amount;
        let token_type = trade.token_type;
        
        let vault = borrow_global_mut<EscrowVault>(@p2p_trade);
        
        // Note: In production, implement proper escrow mechanism
        // For now, we track amounts and assume admin manages transfers
        if (token_type == b"CUSD") {
            let locked_amount = table::remove(&mut vault.cusd_balances, trade_id);
            
            admin_config.total_cusd_volume = admin_config.total_cusd_volume + locked_amount;
        } else {
            let locked_amount = table::remove(&mut vault.confio_balances, trade_id);
            
            admin_config.total_confio_volume = admin_config.total_confio_volume + locked_amount;
        };
        
        admin_config.total_trades_completed = admin_config.total_trades_completed + 1;
        
        // Emit event
        event::emit(TradeCompleted {
            trade_id,
            seller: trade.seller,
            buyer,
            amount,
            token_type,
            timestamp: current_time
        });
    }

    // Cancel trade (by seller before acceptance or after expiry)
    public entry fun cancel_trade(
        canceller: &signer,
        trade_id: vector<u8>,
        reason: vector<u8>,
    ) acquires AdminConfig, TradeRegistry, EscrowVault {
        let admin_config = borrow_global_mut<AdminConfig>(@p2p_trade);
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        
        let registry = borrow_global_mut<TradeRegistry>(@p2p_trade);
        assert!(table::contains(&registry.trades, trade_id), error::not_found(E_TRADE_NOT_FOUND));
        
        let trade = table::borrow_mut(&mut registry.trades, trade_id);
        let current_time = timestamp::now_microseconds();
        
        // Check authorization and conditions
        if (trade.status == STATUS_PENDING) {
            // Seller can cancel pending trade
            assert!(trade.seller == address_of(canceller), error::permission_denied(E_NOT_AUTHORIZED));
        } else if (trade.status == STATUS_ACTIVE && current_time > trade.expires_at) {
            // Anyone can cancel expired active trade
        } else {
            abort error::invalid_state(E_INVALID_TRADE_STATE)
        };
        
        // Mark as cancelled
        trade.status = STATUS_CANCELLED;
        
        // Return funds to seller
        let seller = trade.seller;
        let token_type = trade.token_type;
        
        let vault = borrow_global_mut<EscrowVault>(@p2p_trade);
        
        // Note: In production, implement proper escrow mechanism
        // For now, we track amounts and assume admin manages transfers
        if (token_type == b"CUSD") {
            let locked_amount = table::remove(&mut vault.cusd_balances, trade_id);
        } else {
            let locked_amount = table::remove(&mut vault.confio_balances, trade_id);
        };
        
        admin_config.total_trades_cancelled = admin_config.total_trades_cancelled + 1;
        
        // Emit event
        event::emit(TradeCancelled {
            trade_id,
            cancelled_by: address_of(canceller),
            reason,
            timestamp: current_time
        });
    }

    // Open dispute (by buyer or seller)
    public entry fun open_dispute(
        disputer: &signer,
        trade_id: vector<u8>,
        reason: vector<u8>,
    ) acquires AdminConfig, TradeRegistry {
        let admin_config = borrow_global_mut<AdminConfig>(@p2p_trade);
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        
        let registry = borrow_global_mut<TradeRegistry>(@p2p_trade);
        assert!(table::contains(&registry.trades, trade_id), error::not_found(E_TRADE_NOT_FOUND));
        
        let trade = table::borrow_mut(&mut registry.trades, trade_id);
        assert!(trade.status == STATUS_ACTIVE, error::invalid_state(E_INVALID_TRADE_STATE));
        assert!(trade.seller == address_of(disputer) || trade.buyer == address_of(disputer), error::permission_denied(E_NOT_AUTHORIZED));
        
        let current_time = timestamp::now_microseconds();
        
        // Mark as disputed
        trade.status = STATUS_DISPUTED;
        trade.dispute_reason = reason;
        trade.dispute_opened_by = address_of(disputer);
        trade.dispute_opened_at = current_time;
        
        admin_config.total_trades_disputed = admin_config.total_trades_disputed + 1;
        
        // Emit event
        event::emit(DisputeOpened {
            trade_id,
            opened_by: address_of(disputer),
            reason,
            timestamp: current_time
        });
    }

    // Resolve dispute (admin only)
    public entry fun resolve_dispute(
        admin: &signer,
        trade_id: vector<u8>,
        winner: address, // Either seller or buyer
    ) acquires AdminConfig, TradeRegistry, EscrowVault {
        let admin_config = borrow_global_mut<AdminConfig>(@p2p_trade);
        assert!(address_of(admin) == admin_config.admin, error::permission_denied(E_NOT_ADMIN));
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        
        let registry = borrow_global_mut<TradeRegistry>(@p2p_trade);
        assert!(table::contains(&registry.trades, trade_id), error::not_found(E_TRADE_NOT_FOUND));
        
        let trade = table::borrow_mut(&mut registry.trades, trade_id);
        assert!(trade.status == STATUS_DISPUTED, error::invalid_state(E_TRADE_NOT_IN_DISPUTE));
        assert!(winner == trade.seller || winner == trade.buyer, error::invalid_argument(E_NOT_AUTHORIZED));
        
        let current_time = timestamp::now_microseconds();
        
        // Mark as completed
        trade.status = STATUS_COMPLETED;
        
        // Release funds to winner
        let amount = trade.amount;
        let token_type = trade.token_type;
        
        let vault = borrow_global_mut<EscrowVault>(@p2p_trade);
        
        // Note: In production, implement proper escrow mechanism
        // For now, we track amounts and assume admin manages transfers
        if (token_type == b"CUSD") {
            let locked_amount = table::remove(&mut vault.cusd_balances, trade_id);
            
            if (winner == trade.buyer) {
                admin_config.total_cusd_volume = admin_config.total_cusd_volume + locked_amount;
            };
        } else {
            let locked_amount = table::remove(&mut vault.confio_balances, trade_id);
            
            if (winner == trade.buyer) {
                admin_config.total_confio_volume = admin_config.total_confio_volume + locked_amount;
            };
        };
        
        admin_config.total_trades_completed = admin_config.total_trades_completed + 1;
        
        // Emit event
        event::emit(DisputeResolved {
            trade_id,
            resolved_by: address_of(admin),
            winner,
            timestamp: current_time
        });
    }

    // Admin functions
    public entry fun pause(admin: &signer) acquires AdminConfig {
        let admin_config = borrow_global_mut<AdminConfig>(@p2p_trade);
        assert!(address_of(admin) == admin_config.admin, error::permission_denied(E_NOT_ADMIN));
        assert!(!admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        admin_config.is_paused = true;
    }

    public entry fun unpause(admin: &signer) acquires AdminConfig {
        let admin_config = borrow_global_mut<AdminConfig>(@p2p_trade);
        assert!(address_of(admin) == admin_config.admin, error::permission_denied(E_NOT_ADMIN));
        assert!(admin_config.is_paused, error::invalid_state(E_SYSTEM_PAUSED));
        admin_config.is_paused = false;
    }

    // View functions
    #[view]
    public fun get_trade(trade_id: vector<u8>): Trade acquires TradeRegistry {
        let registry = borrow_global<TradeRegistry>(@p2p_trade);
        assert!(table::contains(&registry.trades, trade_id), error::not_found(E_TRADE_NOT_FOUND));
        *table::borrow(&registry.trades, trade_id)
    }

    #[view]
    public fun is_trade_expired(
        trade_id: vector<u8>
    ): bool acquires TradeRegistry {
        let registry = borrow_global<TradeRegistry>(@p2p_trade);
        if (!table::contains(&registry.trades, trade_id)) {
            return false
        };
        
        let trade = table::borrow(&registry.trades, trade_id);
        let current_time = timestamp::now_microseconds();
        
        current_time > trade.expires_at
    }

    #[view]
    public fun get_stats(): (u64, u64, u64, u64, u64, u64) acquires AdminConfig {
        let admin_config = borrow_global<AdminConfig>(@p2p_trade);
        (
            admin_config.total_trades_created,
            admin_config.total_trades_completed,
            admin_config.total_trades_cancelled,
            admin_config.total_trades_disputed,
            admin_config.total_cusd_volume,
            admin_config.total_confio_volume
        )
    }

    // Test only
    #[test_only]
    public fun test_init(admin: &signer) {
        init_module(admin)
    }
}