# Generated by Django 4.2.20 on 2025-07-21 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=20)),
                ('rates_fetched', models.IntegerField(default=0, help_text='Number of rates successfully fetched')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='API response time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='exchange_ra_source_5cd3b8_idx'), models.Index(fields=['created_at'], name='exchange_ra_created_e00594_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(default='VES', help_text='Source currency (e.g., VES)', max_length=3)),
                ('target_currency', models.CharField(default='USD', help_text='Target currency (e.g., USD)', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='How many source_currency per 1 target_currency', max_digits=15)),
                ('rate_type', models.CharField(choices=[('official', 'Official Rate'), ('parallel', 'Parallel Market Rate'), ('black_market', 'Black Market Rate'), ('average', 'Average Rate')], default='parallel', max_length=20)),
                ('source', models.CharField(choices=[('dolartoday', 'DolarToday'), ('yadio', 'Yadio.io'), ('exchangerate_api', 'ExchangeRate-API'), ('bcv', 'Banco Central de Venezuela'), ('manual', 'Manual Entry')], max_length=50)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently valid')),
                ('raw_data', models.JSONField(blank=True, help_text='Raw API response for debugging', null=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['source_currency', 'target_currency', 'rate_type'], name='exchange_ra_source__93518e_idx'), models.Index(fields=['fetched_at'], name='exchange_ra_fetched_f26108_idx'), models.Index(fields=['is_active', 'rate_type'], name='exchange_ra_is_acti_fc9492_idx')],
                'unique_together': {('source_currency', 'target_currency', 'rate_type', 'source', 'fetched_at')},
            },
        ),
    ]
