# Generated by Django 5.2 on 2026-10-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0002_alter_exchangerate_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('source', models.CharField(default='binance_p2p', max_length=50)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Units of currency per 1 USD', max_digits=15)),
                ('fetched_at', models.DateTimeField(help_text='When the underlying ExchangeRate was fetched')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'currency', 'source'), name='uniq_daily_rate_snapshot')],
            },
        ),
    ]
