# Generated by Django 4.2.20 on 2025-07-30 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0048_remove_ambassadoractivity_ambassador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_broadcast', models.BooleanField(default=False)),
                ('broadcast_target', models.CharField(blank=True, help_text="Target audience: 'all', 'verified', 'business', etc.", max_length=50, null=True)),
                ('notification_type', models.CharField(choices=[('SEND_RECEIVED', 'Send Received'), ('SEND_SENT', 'Send Sent'), ('SEND_INVITATION_SENT', 'Send Invitation Sent'), ('SEND_INVITATION_CLAIMED', 'Send Invitation Claimed'), ('SEND_INVITATION_EXPIRED', 'Send Invitation Expired'), ('SEND_FROM_EXTERNAL', 'Send from External Wallet'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_SENT', 'Payment Sent'), ('INVOICE_PAID', 'Invoice Paid'), ('P2P_OFFER_RECEIVED', 'P2P Offer Received'), ('P2P_OFFER_ACCEPTED', 'P2P Offer Accepted'), ('P2P_OFFER_REJECTED', 'P2P Offer Rejected'), ('P2P_TRADE_STARTED', 'P2P Trade Started'), ('P2P_PAYMENT_CONFIRMED', 'P2P Payment Confirmed'), ('P2P_CRYPTO_RELEASED', 'P2P Crypto Released'), ('P2P_TRADE_COMPLETED', 'P2P Trade Completed'), ('P2P_TRADE_CANCELLED', 'P2P Trade Cancelled'), ('P2P_TRADE_DISPUTED', 'P2P Trade Disputed'), ('CONVERSION_COMPLETED', 'Conversion Completed'), ('CONVERSION_FAILED', 'Conversion Failed'), ('USDC_DEPOSIT_PENDING', 'USDC Deposit Pending'), ('USDC_DEPOSIT_COMPLETED', 'USDC Deposit Completed'), ('USDC_DEPOSIT_FAILED', 'USDC Deposit Failed'), ('USDC_WITHDRAWAL_PENDING', 'USDC Withdrawal Pending'), ('USDC_WITHDRAWAL_COMPLETED', 'USDC Withdrawal Completed'), ('USDC_WITHDRAWAL_FAILED', 'USDC Withdrawal Failed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('SECURITY_ALERT', 'Security Alert'), ('NEW_LOGIN', 'New Login Detected'), ('BUSINESS_EMPLOYEE_ADDED', 'Added as Business Employee'), ('BUSINESS_EMPLOYEE_REMOVED', 'Removed from Business'), ('BUSINESS_PERMISSION_CHANGED', 'Business Permissions Changed'), ('PROMOTION', 'Promotion'), ('SYSTEM', 'System Notification'), ('ANNOUNCEMENT', 'Announcement')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action_url', models.CharField(blank=True, help_text='Deep link for notification action', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.account')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_transactions', models.BooleanField(default=True)),
                ('push_p2p', models.BooleanField(default=True)),
                ('push_security', models.BooleanField(default=True)),
                ('push_promotions', models.BooleanField(default=True)),
                ('push_announcements', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_transactions', models.BooleanField(default=True)),
                ('in_app_p2p', models.BooleanField(default=True)),
                ('in_app_security', models.BooleanField(default=True)),
                ('in_app_promotions', models.BooleanField(default=True)),
                ('in_app_announcements', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'notification'], name='notificatio_user_id_5919d8_idx')],
                'unique_together': {('notification', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_broadcast', '-created_at'], name='notificatio_is_broa_8fc0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['account', '-created_at'], name='notificatio_account_f92a45_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['business', '-created_at'], name='notificatio_busines_94bf1b_idx'),
        ),
    ]
