# Generated by Django 5.2 on 2025-09-02 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='FCM token - can be shared by multiple users')),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=255)),
                ('device_name', models.CharField(blank=True, help_text='Device model/name', max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_failure', models.DateTimeField(blank=True, null=True)),
                ('last_failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_broadcast', models.BooleanField(default=False)),
                ('broadcast_target', models.CharField(blank=True, help_text="Target audience: 'all', 'verified', 'business', etc.", max_length=50, null=True)),
                ('notification_type', models.CharField(choices=[('SEND_RECEIVED', 'Send Received'), ('SEND_SENT', 'Send Sent'), ('INVITE_RECEIVED', 'Invite Received'), ('SEND_INVITATION_SENT', 'Send Invitation Sent'), ('SEND_INVITATION_CLAIMED', 'Send Invitation Claimed'), ('SEND_INVITATION_EXPIRED', 'Send Invitation Expired'), ('SEND_FROM_EXTERNAL', 'Send from External Wallet'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_SENT', 'Payment Sent'), ('INVOICE_PAID', 'Invoice Paid'), ('P2P_OFFER_RECEIVED', 'P2P Offer Received'), ('P2P_OFFER_ACCEPTED', 'P2P Offer Accepted'), ('P2P_OFFER_REJECTED', 'P2P Offer Rejected'), ('P2P_TRADE_STARTED', 'P2P Trade Started'), ('P2P_PAYMENT_CONFIRMED', 'P2P Payment Confirmed'), ('P2P_CRYPTO_RELEASED', 'P2P Crypto Released'), ('P2P_TRADE_COMPLETED', 'P2P Trade Completed'), ('P2P_TRADE_CANCELLED', 'P2P Trade Cancelled'), ('P2P_TRADE_DISPUTED', 'P2P Trade Disputed'), ('P2P_DISPUTE_RESOLVED', 'P2P Dispute Resolved'), ('CONVERSION_COMPLETED', 'Conversion Completed'), ('CONVERSION_FAILED', 'Conversion Failed'), ('USDC_DEPOSIT_PENDING', 'USDC Deposit Pending'), ('USDC_DEPOSIT_COMPLETED', 'USDC Deposit Completed'), ('USDC_DEPOSIT_FAILED', 'USDC Deposit Failed'), ('USDC_WITHDRAWAL_PENDING', 'USDC Withdrawal Pending'), ('USDC_WITHDRAWAL_COMPLETED', 'USDC Withdrawal Completed'), ('USDC_WITHDRAWAL_FAILED', 'USDC Withdrawal Failed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('SECURITY_ALERT', 'Security Alert'), ('NEW_LOGIN', 'New Login Detected'), ('BUSINESS_EMPLOYEE_ADDED', 'Added as Business Employee'), ('BUSINESS_EMPLOYEE_REMOVED', 'Removed from Business'), ('BUSINESS_PERMISSION_CHANGED', 'Business Permissions Changed'), ('ACHIEVEMENT_EARNED', 'Achievement Earned'), ('PROMOTION', 'Promotion'), ('SYSTEM', 'System Notification'), ('ANNOUNCEMENT', 'Announcement'), ('PRESALE_PURCHASE_CONFIRMED', 'Presale Purchase Confirmed')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action_url', models.CharField(blank=True, help_text='Deep link for notification action', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_transactions', models.BooleanField(default=True)),
                ('push_p2p', models.BooleanField(default=True)),
                ('push_security', models.BooleanField(default=True)),
                ('push_promotions', models.BooleanField(default=True)),
                ('push_announcements', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_transactions', models.BooleanField(default=True)),
                ('in_app_p2p', models.BooleanField(default=True)),
                ('in_app_security', models.BooleanField(default=True)),
                ('in_app_promotions', models.BooleanField(default=True)),
                ('in_app_announcements', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
