# Generated by Django 4.2.20 on 2025-07-30 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=255)),
                ('device_name', models.CharField(blank=True, help_text='Device model/name', max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_failure', models.DateTimeField(blank=True, null=True)),
                ('last_failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_514985_idx'), models.Index(fields=['token'], name='notificatio_token_edf1ba_idx'), models.Index(fields=['device_id'], name='notificatio_device__054b76_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
