# Generated by Django 5.2 on 2025-09-02 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.account'),
        ),
        migrations.AddField(
            model_name='notification',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.business'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='users.account'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='users.business'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fcmdevicetoken',
            index=models.Index(fields=['user', 'is_active'], name='fcm_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmdevicetoken',
            index=models.Index(fields=['token', 'is_active'], name='fcm_token_active_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmdevicetoken',
            index=models.Index(fields=['device_id'], name='notificatio_device__054b76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fcmdevicetoken',
            unique_together={('user', 'token')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_broadcast', '-created_at'], name='notificatio_is_broa_8fc0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['account', '-created_at'], name='notificatio_account_f92a45_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['business', '-created_at'], name='notificatio_busines_94bf1b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['user', 'notification'], name='notificatio_user_id_5919d8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['user', 'account', 'business'], name='notif_user_acc_bus_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationread',
            constraint=models.UniqueConstraint(fields=('notification', 'user', 'account', 'business'), name='unique_notification_read_per_context'),
        ),
    ]
