# Generated by Django 5.2 on 2025-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SEND_RECEIVED', 'Send Received'), ('SEND_SENT', 'Send Sent'), ('INVITE_RECEIVED', 'Invite Received'), ('SEND_INVITATION_SENT', 'Send Invitation Sent'), ('SEND_INVITATION_CLAIMED', 'Send Invitation Claimed'), ('SEND_INVITATION_EXPIRED', 'Send Invitation Expired'), ('SEND_FROM_EXTERNAL', 'Send from External Wallet'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_SENT', 'Payment Sent'), ('INVOICE_PAID', 'Invoice Paid'), ('P2P_OFFER_RECEIVED', 'P2P Offer Received'), ('P2P_OFFER_ACCEPTED', 'P2P Offer Accepted'), ('P2P_OFFER_REJECTED', 'P2P Offer Rejected'), ('P2P_TRADE_STARTED', 'P2P Trade Started'), ('P2P_PAYMENT_CONFIRMED', 'P2P Payment Confirmed'), ('P2P_CRYPTO_RELEASED', 'P2P Crypto Released'), ('P2P_TRADE_COMPLETED', 'P2P Trade Completed'), ('P2P_TRADE_CANCELLED', 'P2P Trade Cancelled'), ('P2P_TRADE_DISPUTED', 'P2P Trade Disputed'), ('P2P_DISPUTE_RESOLVED', 'P2P Dispute Resolved'), ('CONVERSION_COMPLETED', 'Conversion Completed'), ('CONVERSION_FAILED', 'Conversion Failed'), ('USDC_DEPOSIT_PENDING', 'USDC Deposit Pending'), ('USDC_DEPOSIT_COMPLETED', 'USDC Deposit Completed'), ('USDC_DEPOSIT_FAILED', 'USDC Deposit Failed'), ('USDC_WITHDRAWAL_PENDING', 'USDC Withdrawal Pending'), ('USDC_WITHDRAWAL_COMPLETED', 'USDC Withdrawal Completed'), ('USDC_WITHDRAWAL_FAILED', 'USDC Withdrawal Failed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('SECURITY_ALERT', 'Security Alert'), ('NEW_LOGIN', 'New Login Detected'), ('BUSINESS_EMPLOYEE_ADDED', 'Added as Business Employee'), ('BUSINESS_EMPLOYEE_REMOVED', 'Removed from Business'), ('BUSINESS_PERMISSION_CHANGED', 'Business Permissions Changed'), ('ACHIEVEMENT_EARNED', 'Achievement Earned'), ('REFERRAL_FRIEND_JOINED', 'Referral Friend Joined'), ('REFERRAL_FIRST_TRANSACTION', 'Referral First Transaction'), ('REFERRAL_ACTION_REMINDER', 'Referral Action Reminder'), ('REFERRAL_EVENT_TOP_UP', 'Referral Event - Top Up'), ('REFERRAL_EVENT_CONVERSION', 'Referral Event - Conversion'), ('REFERRAL_EVENT_SEND', 'Referral Event - Send'), ('REFERRAL_EVENT_PAYMENT', 'Referral Event - Payment'), ('REFERRAL_EVENT_P2P_TRADE', 'Referral Event - P2P Trade'), ('REFERRAL_REWARD_READY', 'Referral Reward Ready'), ('REFERRAL_REWARD_CLAIMED', 'Referral Reward Claimed'), ('PROMOTION', 'Promotion'), ('SYSTEM', 'System Notification'), ('ANNOUNCEMENT', 'Announcement'), ('PRESALE_PURCHASE_CONFIRMED', 'Presale Purchase Confirmed')], max_length=50),
        ),
    ]
