# Generated by Django 4.2.11 on 2025-07-30 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('notifications', '0002_add_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationread',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='users.account'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='users.business'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='notificationread',
            constraint=models.UniqueConstraint(fields=('notification', 'user', 'account', 'business'), name='unique_notification_read_per_context'),
        ),
        migrations.AlterField(
            model_name='notificationread',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['user', 'account', 'business'], name='notif_user_acc_bus_idx'),
        ),
    ]